### PR TITLE
layout: center floating window at cursor when picked up from fullscreen

### LINKED ISSUE #9779: fullscreening a floating window and then picking it up makes it float
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Not a regression - it's an old bug

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.48.0 built from branch main at commit 7374a023eff964817c9e5fbe75a661540516f798  (renderer/opengl: Extract shaders from source (9600)).
Date: Fri Mar 28 20:19:35 2025
Tag: v0.48.0-20-g7374a023e, commits: 5942
built against:
 aquamarine 0.8.0
 hyprlang 0.6.0
 hyprutils 0.5.2
 hyprcursor 0.1.12
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: iwuvyou
Release: 6.13.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 23 Mar 2025 17:17:30 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
0f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

if u pick up a floating window after fullscreening it it goes back to floating in its original position, but the problem with this is that the cursor will be and can be no where near the window

### How to reproduce

pick up a floating -> fullscreened window

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [ ] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

_No response_

### PR DESCRIPTION
**Pull request by nnyyxxxx**
when picking up a floating window after it had been fullscreened before it would return to its previous position which looked ugly because the cursor could be no where near the windows original position, this patch makes it so that the window is returned to the users current cursor position

video of the previous behavior:

https://github.com/hyprwm/Hyprland/issues/9779#issuecomment-2763122913

it's wayyy better now

fixes #9779

### CODE REVIEW

File: src/layout/IHyprLayout.cpp [hunk 1]
```diff
@@ -240,8 +240,10 @@ void IHyprLayout::onBeginDragWindow() {
         return;
     }
 
+    bool wasFullscreen = false;
```
Comment (vaxerski) [inline src/layout/IHyprLayout.cpp:243]: const bool WAS_FULLSCREEN = DRAGGINGWINDOW->isFullscreen()
if (WAS_FULLSCREEN)

Comment (nnyyxxxx) [reply src/layout/IHyprLayout.cpp]: here sir [b749602](https://github.com/hyprwm/Hyprland/pull/9780/commits/b74960213011a7ebabe2b0f56ab3a4f09ebf99ef)

**Review by vaxerski — APPROVED** [review]
