### PR TITLE
Fix greedy mouse grab from keyboard_interactive layer

### LINKED ISSUE #2017: Strange mouse grab on layers with keyboard interactivity
I think this is probably a bug, found it testing the eww sys tray https://github.com/elkowar/eww/pull/743#issuecomment-1501716248

there are multiple ways to reproduce, enable `:focusable` in an eww window or just run any layer-shell example like below with keyboard interactivity

I have  `follow_mouse = 2`

the smithay example is with OnDemand but its same with Exclusive too

```
git clone https://github.com/Smithay/client-toolkit/
cd client_toolkit 
cargo run --release --example simple_layer
```

expecatation:
mouse events only go to the layer surface if the cursor is over the surface, if its over another surface events go to that other surface

actual:
mouse events seem to go to the layer surface no matter where i click on the screen

sway: mouse clicks go to the intended target surface, not to the layer if mouse is not over the layer surface
does not happen with kb interactivity disabled

so I'm wondering what might keyboard interactivity have to do with mouse events

### PR DESCRIPTION
**Pull request by earboxer**
#### Describe your PR, what does it fix/add?

Fixes #2017

This allows you to use your mouse on other (not covered) surfaces even when you have a keyboard_interactive layer active.

The bug was that a keyboard_interactive layer would always take precedence over everything else (even without KEYBOARD_INTERACTIVITY_EXCLUSIVE). The fix makes that layer not take precedence, and instead makes `refocus` respect KEYBOARD_INTERACTIVITY_EXCLUSIVE (i.e. the correct behavior).

So, you can
* use wvkbd to type into bemenu
   * click on an eww element even when rofi is open
* click or scroll another window when (some other keyboard_interactive layer) is open
    * this will not steal the keyboard focus from a KEYBOARD_INTERACTIVITY_EXCLUSIVE layer

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

One case I found where the KEYBOARD_INTERACTIVITY_EXCLUSIVE is not respected:

* keyboard focus will still be stolen (from the layer to a window) when you switch focus using movefocus (e.g. $mainMod, left)

this is an existing bug/feature (it may be intended behavior). Maybe it should be fixed now (so KEYBOARD_INTERACTIVITY_EXCLUSIVE layers keep the keyboard), or maybe fix it some other day?

#### Is it ready for merging, or does it need work?

This is ready. It fixes the unexpected and incorrect behavior that bothers me. (the existing movefocus behavior can be changed some other time, if that's what we want.)

### CODE REVIEW

File: src/managers/input/InputManager.cpp [hunk 1]
```diff
@@ -421,7 +421,7 @@ void CInputManager::mouseMoveUnified(uint32_t time, bool refocus) {
             m_bLastFocusOnLS = false;
             return; // don't enter any new surfaces
         } else {
-            if (((FOLLOWMOUSE != 3 && allowKeyboardRefocus) && (*PMOUSEREFOCUS || m_pLastMouseFocus != pFoundWindow)) || refocus) {
+            if ((FOLLOWMOUSE != 3 && allowKeyboardRefocus) && ((*PMOUSEREFOCUS || m_pLastMouseFocus != pFoundWindow) || refocus)) {
```
Comment (earboxer) [inline src/managers/input/InputManager.cpp:424]: (not completely sure this is completely right (haven't tested with FOLLOWMOUSE = 3). Just wanted to make `refocus` respect `allowKeyboardRefocus`)

Comment (vaxerski) [reply src/managers/input/InputManager.cpp:424]: why is this even in this MR? doesn't seem related

**Comment by vaxerski** [comment]
from a glimpse I don't think this will work well?

Some cases:
 - open a launcher, hit a keybind to `movefocus,l` to a window. LS will get completely unfocused...?
 - open a launcher and click on an OSK, will the launcher still have kb focus?

**Comment by earboxer** [comment]
On Wed Jan 10, 2024 at 9:11 AM EST, Vaxry wrote:
>  - open a launcher, hit a keybind to `movefocus,l` to a window. LS will get completely unfocused...?
Yes, until you mouse over it. This is an existing bug (though currently its only unfocused until you wiggle the mouse).

>  - open a launcher and click on an OSK, will the launcher still have kb focus?
Yes, launcher will have focus. Existing code ensures that a non-keyboard layer can't take keyboard focus.

**Comment by vaxerski** [comment]
fair enough.

File: src/managers/input/InputManager.cpp (hunk 1 above)
Comment (vaxerski) [reply src/managers/input/InputManager.cpp:424]: I also don't understand the point here?

Comment (earboxer) [reply src/managers/input/InputManager.cpp]: I tweaked the logic so that this won't change how FOLLOWMOUSE = 3 behaves.

File: src/managers/input/InputManager.cpp [hunk 2]
```diff
@@ -421,7 +421,7 @@ void CInputManager::mouseMoveUnified(uint32_t time, bool refocus) {
             m_bLastFocusOnLS = false;
             return; // don't enter any new surfaces
         } else {
-            if (((FOLLOWMOUSE != 3 && allowKeyboardRefocus) && (*PMOUSEREFOCUS || m_pLastMouseFocus != pFoundWindow)) || refocus) {
+            if (allowKeyboardRefocus && ((FOLLOWMOUSE != 3 && (*PMOUSEREFOCUS || m_pLastMouseFocus != pFoundWindow)) || refocus)) {
```
Comment (earboxer) [inline src/managers/input/InputManager.cpp:424]: The idea is only allow 'refocus' if allowKeyboardRefocus is true.

(I could have changed `refocus` to `(allowKeyboardRefocus && refocus)`, but I just extracted allowKeyboardRefocus to the front since it's required in both cases)

File: src/managers/input/InputManager.cpp (hunk 1 above)
Comment (earboxer) [reply src/managers/input/InputManager.cpp]: The point is that we shouldn't refocus (change keyboard focus) when `allowKeyboardRefocus` is false (even on a click/force refocus), because there's a layer that has grabbed the keyboard.

Comment (vaxerski) [reply src/managers/input/InputManager.cpp]: ok

**Review by vaxerski — APPROVED** [review]
lgtm

**Comment by feschber** [comment]
#4465

**Comment by feschber** [comment]
From my testing, the offending change is this:
```diff
diff --git a/src/managers/input/InputManager.cpp b/src/managers/input/InputManager.cpp
index 8bfdb65c..ce7e2b30 100644
--- a/src/managers/input/InputManager.cpp
+++ b/src/managers/input/InputManager.cpp
@@ -359,7 +359,7 @@ void CInputManager::mouseMoveUnified(uint32_t time, bool refocus) {
 
     bool allowKeyboardRefocus = true;
 
-    if (g_pCompositor->m_pLastFocus) {
+    if (!refocus && g_pCompositor->m_pLastFocus) {
         const auto PLS = g_pCompositor->getLayerSurfaceFromSurface(g_pCompositor->m_pLastFocus);
 
         if (PLS && PLS->layerSurface->current.keyboard_interactive == ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_EXCLUSIVE)
```

**Comment by earboxer** [comment]
There is a partial regression from the two commits discussed here

https://github.com/hyprwm/Hyprland/issues/4465#issuecomment-1913149150

(If I open bemenu/rofi/nwggrid while there's no window open, it won't get keyboard events from wvkbd)
