### PR TITLE
helpers: properly support next/prev for workspace switching 

### LINKED ISSUE #9922: When the previous workspace doesn't exist, focusworkspaceoncurrentmonitor previous fails.
### Discussion Link
https://github.com/hyprwm/Hyprland/discussions/9883

## Description
When the previous workspace doesn't exist (empty and removed), calling focusworkspaceoncurrentmonitor previous returns `focusWorkspaceOnCurrentMonitor invalid workspace!`.

## Repro steps
- move to empty workspace x
- move to a different workspace
- call `hyprctl dispatch focusworkspaceoncurrentmonitor previous`

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes #9922

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
this is more broad than i thought, next also fails..

**Comment by nnyyxxxx** [comment]
@vaxerski isnt focusworkspaceoncurrentmonitor just a duplicate of the workspace dispatcher

**Comment by vaxerski** [comment]
@3333juul care to test this MR?

**Comment by nnyyxxxx** [comment]
@vaxerski bump

File: src/helpers/MiscFunctions.cpp [hunk 1]
```diff
@@ -170,12 +170,34 @@ SWorkspaceIDName getWorkspaceIDNameFromString(const std::string& in) {
...
 
-        if (!PLASTWORKSPACE)
+        if (PREVID == -1)
             return {WORKSPACE_INVALID};
 
+        const auto PLASTWORKSPACE = g_pCompositor->getWorkspaceByID(PREVID);
+
+        if (!PLASTWORKSPACE) {
+            Debug::log(LOG, "previous workspace {} doesn't exist yet", PREVID);
+            return {PREVID, ""};
```
Comment (vaxerski) [inline src/helpers/MiscFunctions.cpp:182]: what about named workspaces? `-1337,hello`?

File: src/helpers/MiscFunctions.cpp [hunk 2]
```diff
@@ -170,12 +170,34 @@ SWorkspaceIDName getWorkspaceIDNameFromString(const std::string& in) {
...
+        }
+
+        auto        PCURRENTWORKSPACE = g_pCompositor->m_pLastMonitor->activeWorkspace;
+        auto        PCURRMONITOR      = g_pCompositor->m_pLastMonitor;
+
+        WORKSPACEID nextId = PCURRENTWORKSPACE->m_iID;
+
+        nextId      = PCURRENTWORKSPACE->m_iID + 1;
+        result.id   = nextId;
+        result.name = std::to_string(nextId);
```
Comment (vaxerski) [inline src/helpers/MiscFunctions.cpp:199]: has the same problem, -1338 is a named.

Comment (nnyyxxxx) [reply src/helpers/MiscFunctions.cpp:199]: i dont think next is feasible for named workspaces

Comment (vaxerski) [reply src/helpers/MiscFunctions.cpp:199]: well then return a not found and not a weird result

File: src/helpers/MiscFunctions.cpp (hunk 1 above)
Comment (nnyyxxxx) [reply src/helpers/MiscFunctions.cpp]: fixed

**Review by vaxerski — APPROVED** [review]

**Comment by vaxerski** [comment]
oop conflice

**Review by vaxerski — APPROVED** [review]
