### PR TITLE
dwindle: fix windows being created at incorrect position when cursor is over reserved area

### LINKED ISSUE #4519: smart_split incorrect direction of new windows when hovering over reserved area
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch main at commit b86ed02d8ae7c955e1f42cc27a19fe18d82c50b7 dirty (keybinds: avoid duplicated held keys, only use last, remove all).
Date: Fri Jan 19 19:09:32 2024
Tag: v0.34.0-55-gb86ed02d

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.7.0-arch3-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c3) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When `dwindle:smart_split=1` is set, hovering over reserved area (such a waybar) at the bottom of the screen creates windows towards top and not towards bottom.

### How to reproduce

1. have waybar at the bottom
2. set `dwindle:smart_split=1`
3. create a new window
3. hover over waybar
4. create a second window

Actual:
the second window is created at the top of the screen

Expected:
the second window is created at the bottom of the screen

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/44318430/3482c2ce-b125-4aa8-9150-075bc9695e87

### PR DESCRIPTION
**Pull request by rszyma**
#### Describe your PR, what does it fix/add?

~~Partially~~ fixes #4519

~~Partially fixed, because new windows are created towards the cursor. 
Partially still broken, because the parent node is not the one that has focus, but one closest to `(0, 0)`~~

~~See the video with this PR applied (for comparison with video in #4519):~~

(the video only applies to the first commit, it became outdated after the second one) 

https://github.com/hyprwm/Hyprland/assets/44318430/d26c29e9-18df-4ad9-b366-a0be9cdca4f7

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

no

#### Is it ready for merging, or does it need work?

~~imo could be merged as is, unless we want to fix the other issue right now too~~

ready

### CODE REVIEW

**Comment by rszyma** [comment]
`TARGETCOORDS` is broken and reporting `(0, 0) when hovering over reserved area, so instead I used `MOUSECOORDS`.

**Comment by rszyma** [comment]
to fix the second part, this https://github.com/hyprwm/Hyprland/blob/4e84ab6595ef263f933c4a3512a53229f983d6af/src/layout/DwindleLayout.cpp#L263-L265 

needs to change to assign `OPENINGON` to closest node to cursor, instead of first node in workspace

**Comment by rszyma** [comment]
alright, i fixed the second issue, it works perfectly from my testing.

ready for review

File: src/helpers/Box.cpp [hunk 1]
```diff
@@ -124,6 +124,14 @@ Vector2D CBox::size() const {
     return {w, h};
 }
 
+double CBox::distance(const Vector2D& point) const {
+    Vector2D p1 = pos();
+    Vector2D p2 = pos() + Vector2D(w, 0);
+    Vector2D p3 = pos() + size();
+    Vector2D p4 = pos() + Vector2D(0, h);
+    return std::min({point.distanceFromSegment(p1, p2), point.distanceFromSegment(p2, p3), point.distanceFromSegment(p3, p4), point.distanceFromSegment(p4, p1)});
```
Comment (vaxerski) [inline src/helpers/Box.cpp:132]: Why not just https://stackoverflow.com/questions/5254838/calculating-distance-between-a-point-and-a-rectangular-box-nearest-point

and return `Squared`?

Comment (rszyma) [reply src/helpers/Box.cpp:132]: yes, and even we already had a helper function for that

Comment (rszyma) [reply src/helpers/Box.cpp:132]: 72cfefb

**Comment by rszyma** [comment]
changed title, as this fix appplies to dwindle overall, not just when `smart_split` is enabled

**Comment by vaxerski** [comment]
fgjdylssbvdi

**Comment by rszyma** [comment]
I agree

**Comment by rszyma** [comment]
@vaxerski anything else you want me to change?

**Comment by vaxerski** [comment]
gimme a homie kiss?

oh wait change in this MR

**Review by vaxerski — APPROVED** [review]
lgtm
