### PR TITLE
core: fix artifacts when fullscreening

### LINKED ISSUE #9673: artifacts when fullscreening
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch main at commit 5cef2f44fed662c8cac256877b0a7141b9ce2440  (renderer: allow commits when buffer is unchanged but cursor changed (9648)).
Date: Mon Mar 17 08:06:58 2025
Tag: v0.47.0-153-g5cef2f44f, commits: 5895
built against:
 aquamarine 0.8.0
 hyprlang 0.6.0
 hyprutils 0.5.2
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: iwuvyou
Release: 6.13.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 27 Feb 2025 18:09:44 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
0f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

artifacts when fullscreening

### How to reproduce

fullscreen a window that is between 2 monitors

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [ ] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

_No response_

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes an issue where fullscreening a floating window that is between two monitors causes artifacts to appear on the monitor where it did not become fullscreened on

fixes #9673

### CODE REVIEW

File: src/Compositor.cpp [hunk 1]
```diff
@@ -2308,6 +2308,13 @@ void CCompositor::setWindowFullscreenState(const PHLWINDOW PWINDOW, SFullscreenS
     const eFullscreenMode CURRENT_EFFECTIVE_MODE = (eFullscreenMode)std::bit_floor((uint8_t)PWINDOW->m_sFullscreenState.internal);
     const eFullscreenMode EFFECTIVE_MODE         = (eFullscreenMode)std::bit_floor((uint8_t)state.internal);
 
+    if (PWINDOW->m_bIsFloating && CURRENT_EFFECTIVE_MODE == FSMODE_NONE && EFFECTIVE_MODE != FSMODE_NONE) {
```
Comment (vaxerski) [inline src/Compositor.cpp:2311]: why not just gprenderer->dmaagewindow(pwindow)?

Comment (nnyyxxxx) [reply src/Compositor.cpp:2311]: that makes more sense ig

Comment (nnyyxxxx) [reply src/Compositor.cpp]: [6d716ee](https://github.com/hyprwm/Hyprland/pull/9778/commits/6d716ee5a2f7acb4f9716e47dbabeacde0a7c651)

**Review by vaxerski — APPROVED** [review]
