### PR TITLE
fix(subsurface): dont try to access popup surfaces when handling subsurface updates

### LINKED ISSUE #9419: CPopup errors forcing unexpected exit
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Probably not a regression / I don't remember it happening before

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: omarch
Release: 6.13.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 08 Feb 2025 18:54:55 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

twice within a week I've experienced sudden random exits to the login screen. 

### How to reproduce

I'm not sure what I've done to force the issue as I was mostly idling with firefox and tmux/neovim open on two different screens.

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [x] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprlandCrashReport797.txt](https://github.com/user-attachments/files/18812772/hyprlandCrashReport797.txt)
[hyprlandCrashReport804.txt](https://github.com/user-attachments/files/18812771/hyprlandCrashReport804.txt)
[journal_error.log](https://github.com/user-attachments/files/18812773/journal_error.log)

[hyprland_config_dump.txt](https://github.com/user-attachments/files/18812777/hyprland_config_dump.txt)

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes #9419

### CODE REVIEW

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/18816256/patch.txt)
doesnt this achieve the same with less loc changed and less useless props (inert)

**Comment by nnyyxxxx** [comment]
mine prevents invalid popups from being processed, allat patch does is just add null checks

mine better

**Comment by nnyyxxxx** [comment]
also my changes are at the source

**Comment by nnyyxxxx** [comment]
less loc doesnt mean better lol

File: src/desktop/Subsurface.cpp [hunk 1]
```diff
@@ -124,7 +124,7 @@ void CSubsurface::onCommit() {
         // g_pHyprRenderer->damageBox(box);
 
         CBox box;
-        if (m_pPopupParent)
+        if (m_pPopupParent && !m_pPopupParent->inert() && m_pPopupParent->m_pWLSurface && m_pPopupParent->m_pWLSurface->exists())
```
Comment (vaxerski) [inline src/desktop/Subsurface.cpp:127]: exists() is redundant

File: src/desktop/Subsurface.cpp [hunk 2]
```diff
@@ -107,7 +107,7 @@ void CSubsurface::onCommit() {
 
     g_pHyprRenderer->damageSurface(m_pWLSurface->resource(), COORDS.x, COORDS.y);
 
-    if (m_pPopupParent)
+    if (m_pPopupParent && !m_pPopupParent->inert() && m_pPopupParent->m_pWLSurface && m_pPopupParent->m_pWLSurface->exists())
```
Comment (vaxerski) [inline src/desktop/Subsurface.cpp:110]: these checks are misplaced. Instead, recheckTree() should perform them

File: src/desktop/Popup.hpp [hunk 3]
```diff
@@ -34,6 +34,9 @@ class CPopup {
     void           recheckTree();
 
     bool           visible();
+    bool           inert() const {
```
Comment (vaxerski) [inline src/desktop/Popup.hpp:37]: defs go to cpp files

**Review by vaxerski — DISMISSED** [review]

**Comment by vaxerski** [comment]
woops "approved" by accident

**Review by vaxerski — APPROVED** [review]
thanks!
