### PR TITLE
Close keymap files.

### LINKED ISSUE #2904: Hyprland leaks FILE* when input.kb_file is set.
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

In both places where Hyprland calls xkb_keymap_new_from_file, it calls fopen() on the keymap file, and then doesn't close it. xkb_keymap_new_from_file doesn't it automatically. 

### How to reproduce

Set kb_file in the input section of the config to a keymap file, and reload configuration a few times, to leak the file multiple times. Then check how many open files Hyprland has in `/proc/$HYPRLANDS_PID/fd`.

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by MichaelPachec0**
#### Describe your PR, what does it fix/add?
It was brought up in #2904 that keymap fd's are not properly closed, leading to memory leaks. This fixes #2904.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I do not personally use keymap files but this looked like a simple enough fix. Just need a pair of eyeballs to see if this is correct and I did not screw this simple thing up.

Also there is no error handling on fopen or fclose, as it stands there was no error handling anyways so i tried to be minimal with this change as possible. If there is a need to handle errors here, I can rewrite this to include so.

#### Is it ready for merging, or does it need work?
Should be ready for merging given a review and the above answered.

### CODE REVIEW

File: src/managers/KeybindManager.cpp [hunk 1]
```diff
@@ -141,9 +141,11 @@ void CKeybindManager::updateXKBTranslationState() {
     xkb_rule_names rules = {.rules = RULES.c_str(), .model = MODEL.c_str(), .layout = LAYOUT.c_str(), .variant = VARIANT.c_str(), .options = OPTIONS.c_str()};
 
     const auto     PCONTEXT = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
+    FILE           *KEYMAP_FILE = fopen(FILEPATH.c_str(), "r");
```
Comment (vaxerski) [inline src/managers/KeybindManager.cpp:144]: no snake, also, can be made `const` (that's what capital names mean)

```
FILE* const KEYMAPFILE = fopen(FILEPATH.c_str(), "r");
```

File: src/managers/input/InputManager.cpp [hunk 2]
```diff
@@ -786,8 +786,11 @@ void CInputManager::applyConfigToKeyboard(SKeyboard* pKeyboard) {
 
         if (!std::filesystem::exists(path))
             Debug::log(ERR, "input:kb_file= file doesnt exist");
-        else
-            KEYMAP = xkb_keymap_new_from_file(CONTEXT, fopen(path.c_str(), "r"), XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
+        else {
+            FILE *KEYMAP_FILE = fopen(FILEPATH.c_str(), "r");
```
Comment (vaxerski) [inline src/managers/input/InputManager.cpp:790]: ditto

**Review by vaxerski — COMMENTED** [review]
rest alr

**Comment by MichaelPachec0** [comment]
Thanks for the review, just pushed with the above fixes.

**Comment by vaxerski** [comment]
you forgot to run clang-format

**Comment by MichaelPachec0** [comment]
> you forgot to run clang-format

done

**Review by vaxerski — APPROVED** [review]
gangsta

**Comment by maaarghk** [comment]
not quite gangsta ~

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f9757e8e8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f9757e3e668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f9757e264b8 in __GI_abort () at abort.c:79
#4  0x0000557a9d647e26 in  ()
#5  0x00007f9757e3e710 in <signal handler called> () at /usr/lib/libc.so.6
#6  0x00007f9757e77578 in _IO_new_fclose (fp=0x0) at iofclose.c:48
#7  0x0000557a9d7222a0 in CKeybindManager::updateXKBTranslationState() ()
#8  0x0000557a9d68e3c1 in CConfigManager::dispatchExecOnce() ()
#9  0x0000557a9d77c272 in CHyprRenderer::renderMonitor(CMonitor*) ()
#10 0x0000557a9d6efcbc in handleWrapped(wl_listener*, void*) ()
#11 0x00007f975881401e in wl_signal_emit_mutable (signal=<optimized out>, data=0x557aa06ca660) at ../wayland-1.22.0/src/wayland-server.c:2241
#12 0x00007f9758815a23 in wl_event_loop_dispatch_idle (loop=loop@entry=0x557a9f80f2c0) at ../wayland-1.22.0/src/event-loop.c:969
#13 0x00007f9758815b3d in wl_event_loop_dispatch (loop=0x557a9f80f2c0, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1032
#14 0x00007f97588162d7 in wl_display_run (display=0x557a9f80f1d0) at ../wayland-1.22.0/src/wayland-server.c:1493
#15 0x0000557a9d637a66 in main ()
```

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11 (Segmentation fault)

Version: cebab759d52747c2067217d93096b47281722e57
Tag: v0.28.0-13-gcebab759

System info:
        System name: Linux
        Node name: applecross
        Release: 6.4.8-2-MANJARO
        Version: #1 SMP PREEMPT_DYNAMIC Thu Aug  3 19:18:34 UTC 2023

GPU:
        00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])


Log tail:
[wlr] [types/output/output.c:886] sending frame to eDP-1
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
[LOG] Process Created with pid 68747
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 waybar
[LOG] Process Created with pid 68749
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 pasystray --notify=all
[LOG] Process Created with pid 68752
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 dunst
[LOG] Process Created with pid 68754
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
[LOG] Process Created with pid 68756
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Video Bus"
[LOG] ApplyConfigToKeyboard for "video-bus-1", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Video Bus"
[LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Power Button"
[LOG] ApplyConfigToKeyboard for "sleep-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Sleep Button"
[LOG] ApplyConfigToKeyboard for "keychron-keychron-q3", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3"
[LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-system-control", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 System Control"
[LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-consumer-control", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 Consumer Control"
[LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 Keyboard"
[LOG] ApplyConfigToKeyboard for "sof-soundwire-headset-jack", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "sof-soundwire Headset Jack"
[LOG] ApplyConfigToKeyboard for "intel-hid-events", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Intel HID events"
[LOG] ApplyConfigToKeyboard for "intel-hid-5-button-array", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Intel HID 5 button array"
[LOG] ApplyConfigToKeyboard for "dell-wmi-hotkeys", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "Dell WMI hotkeys"
[LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to gb and variant to  for keyboard "AT Translated Set 2 keyboard"
```


confirmed problem does not exist in  deeeb33c5f919ad5499a10526772b617f24d72ab

**Comment by MichaelPachec0** [comment]
> not quite gangsta ~
> 
> ```
> (gdb) bt
> #0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
> #1  0x00007f9757e8e8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
> #2  0x00007f9757e3e668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
> #3  0x00007f9757e264b8 in __GI_abort () at abort.c:79
> #4  0x0000557a9d647e26 in  ()
> #5  0x00007f9757e3e710 in <signal handler called> () at /usr/lib/libc.so.6
> #6  0x00007f9757e77578 in _IO_new_fclose (fp=0x0) at iofclose.c:48
> #7  0x0000557a9d7222a0 in CKeybindManager::updateXKBTranslationState() ()
> #8  0x0000557a9d68e3c1 in CConfigManager::dispatchExecOnce() ()
> #9  0x0000557a9d77c272 in CHyprRenderer::renderMonitor(CMonitor*) ()
> #10 0x0000557a9d6efcbc in handleWrapped(wl_listener*, void*) ()
> #11 0x00007f975881401e in wl_signal_emit_mutable (signal=<optimized out>, data=0x557aa06ca660) at ../wayland-1.22.0/src/wayland-server.c:2241
> #12 0x00007f9758815a23 in wl_event_loop_dispatch_idle (loop=loop@entry=0x557a9f80f2c0) at ../wayland-1.22.0/src/event-loop.c:969
> #13 0x00007f9758815b3d in wl_event_loop_dispatch (loop=0x557a9f80f2c0, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1032
> #14 0x00007f97588162d7 in wl_display_run (display=0x557a9f80f1d0) at ../wayland-1.22.0/src/wayland-server.c:1493
> #15 0x0000557a9d637a66 in main ()
> ```
> 
> ```
> --------------------------------------------
>    Hyprland Crash Report
> --------------------------------------------
> All these computers...
> 
> Hyprland received signal 11 (Segmentation fault)
> 
> Version: cebab759d52747c2067217d93096b47281722e57
> Tag: v0.28.0-13-gcebab759
> 
> System info:
>         System name: Linux
>         Node name: applecross
>         Release: 6.4.8-2-MANJARO
>         Version: #1 SMP PREEMPT_DYNAMIC Thu Aug  3 19:18:34 UTC 2023
> 
> GPU:
>         00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
> 
> 
> Log tail:
> [wlr] [types/output/output.c:886] sending frame to eDP-1
> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
> [LOG] Process Created with pid 68747
> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 waybar
> [LOG] Process Created with pid 68749
> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 pasystray --notify=all
> [LOG] Process Created with pid 68752
> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 dunst
> [LOG] Process Created with pid 68754
> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
> [LOG] Process Created with pid 68756
> [LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Video Bus"
> [LOG] ApplyConfigToKeyboard for "video-bus-1", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Video Bus"
> [LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Power Button"
> [LOG] ApplyConfigToKeyboard for "sleep-button", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Sleep Button"
> [LOG] ApplyConfigToKeyboard for "keychron-keychron-q3", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3"
> [LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-system-control", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 System Control"
> [LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-consumer-control", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 Consumer Control"
> [LOG] ApplyConfigToKeyboard for "keychron-keychron-q3-keyboard", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Keychron Keychron Q3 Keyboard"
> [LOG] ApplyConfigToKeyboard for "sof-soundwire-headset-jack", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "sof-soundwire Headset Jack"
> [LOG] ApplyConfigToKeyboard for "intel-hid-events", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Intel HID events"
> [LOG] ApplyConfigToKeyboard for "intel-hid-5-button-array", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Intel HID 5 button array"
> [LOG] ApplyConfigToKeyboard for "dell-wmi-hotkeys", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "Dell WMI hotkeys"
> [LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
> [LOG] Attempting to create a keymap for layout gb with variant  (rules: , model: , options: )
> [LOG] Set the keyboard layout to gb and variant to  for keyboard "AT Translated Set 2 keyboard"
> ```
> 
> 
> confirmed problem does not exist in  deeeb33c5f919ad5499a10526772b617f24d72ab

Will take a look, any chance you share your config to try and repro?

**Comment by maaarghk** [comment]
cool. I suspect it's to do with having two keybs (an external and an inbuilt) but I guess you already worked that out.  I can test your PR tomorrow if you don't have two available yourself

**Comment by MichaelPachec0** [comment]
> cool. I suspect it's to do with having two keybs (an external and an inbuilt) but I guess you already worked that out. I can test your PR tomorrow if you don't have two available yourself

check #2908 which should fix the error. It was based on a incorrect assumption on my part.
