### PR TITLE
rules/windowRuleApplicator: fix min/max size effects

### LINKED ISSUE #12412: min_size doesn't work since rules v3
### Discussion link
https://github.com/hyprwm/Hyprland/discussions/12386

## Description

```
windowrule = match:class kitty, min_size 200 200
```

no work

### PR DESCRIPTION
**Pull request by vaxerski**
Fixes #12412

### CODE REVIEW

File: src/desktop/rule/windowRule/WindowRuleApplicator.cpp [hunk 1]
```diff
@@ -288,17 +286,16 @@ CWindowRuleApplicator::SRuleResult CWindowRuleApplicator::applyDynamicRule(const
...
                     if (VEC.x < 1 || VEC.y < 1) {
                         Debug::log(ERR, "Invalid size for maxsize");
                         break;
                     }
 
                     m_minSize.first = Types::COverridableVar(VEC, Types::PRIORITY_WINDOW_RULE);
-                    m_window->clampWindowSize(std::nullopt, m_minSize.first.value());
+
+                    if (*PCLAMP_TILED || m_window->m_isFloating)
+                        m_window->clampWindowSize(std::nullopt, m_minSize.first.value());
```
Comment (EvilLary) [inline src/desktop/rule/windowRule/WindowRuleApplicator.cpp]: arguments are flipped, they're also flipped in   https://github.com/hyprwm/Hyprland/blob/7e1e24fea615503a3cc05218c12b06c1b6cabdc7/src/managers/KeybindManager.cpp#L3168

File: src/desktop/rule/windowRule/WindowRuleApplicator.cpp [hunk 2]
```diff
@@ -265,18 +265,16 @@ CWindowRuleApplicator::SRuleResult CWindowRuleApplicator::applyDynamicRule(const
...
                     if (VEC.x < 1 || VEC.y < 1) {
                         Debug::log(ERR, "Invalid size for maxsize");
                         break;
                     }
 
                     m_maxSize.first = Types::COverridableVar(VEC, Types::PRIORITY_WINDOW_RULE);
-                    m_window->clampWindowSize(std::nullopt, m_maxSize.first.value());
 
+                    if (*PCLAMP_TILED || m_window->m_isFloating)
+                        m_window->clampWindowSize(std::nullopt, m_minSize.first.value());
```
Comment (EvilLary) [inline src/desktop/rule/windowRule/WindowRuleApplicator.cpp]: copy paste :P

File: src/desktop/rule/windowRule/WindowRuleApplicator.cpp (hunk 1 above)
Comment (vaxerski) [reply src/desktop/rule/windowRule/WindowRuleApplicator.cpp]: what did you just call me

**Comment by tannerellen** [comment]
Is this one still waiting on fixes? Would love to see it in main as some of my dialogs open small and a min-size widow rule could fix it.

**Comment by vaxerski** [comment]
yeah I just couldnt please the tests I'll try tmr

**Comment by vaxerski** [comment]
fuck the tests

**Comment by kRHYME7** [comment]
@vaxerski  


```
hyprctl version                                                                                                                                                             12:28 
Hyprland 0.52.0 built from branch main at commit a8452705d6512da36f66e4a7d6e7799afbc7ffdd clean (gitignore: add hyprland.desktop generated by cmake).
Date: Sat Dec 27 21:23:32 2025
Tag: v0.52.0-195-ga8452705d, commits: 6754

Libraries:
Hyprgraphics: built against 0.4.0, system has 0.4.0
Hyprutils: built against 0.11.0, system has 0.11.0
Hyprcursor: built against 0.1.13, system has 0.1.13
Hyprlang: built against 0.6.7, system has 0.6.7
Aquamarine: built against 0.10.0, system has 0.10.0

Version ABI string: a8452705d6512da36f66e4a7d6e7799afbc7ffdd_aq_0.10_hu_0.11_hg_0.4_hc_0.1_hlg_0.6
no flags were set
```


This config breaks tiling  `windowrule = match:float true, max_size 1300 900`. 
- When enabled it prevents a floating  window to tile. 

https://github.com/user-attachments/assets/79eccf18-3e0d-4339-a05f-54759ef9659c

**Comment by kRHYME7** [comment]
Maybe the above vid is borke


https://github.com/user-attachments/assets/77065372-16fe-4c96-9cdf-0210b01fe308


* Looks like min_size is working perfectly fine as targeted for this PR. But max_size breaks 


  1. Float the window ✅ (works)
  2. Limit it to 1300x900 when floating ✅ (works)
  3. Allow tiling when you manually toggle tiling ❌ (BROKEN) - the maxsize constraint should either be ignored for tiled windows


BTW  size_limits_tiled is disabled

image

**Comment by kRHYME7** [comment]
Moreover, I observed that it is layout specific issue.  The values just latched to the set size.   

I tried `hyprscrolling` and the floating/tiling works fine. However,  dwindle and master layout doesn't

**Comment by vaxerski** [comment]
that might be a pita to solve, because layouts pop out windows when the tile would be too big

**Comment by kRHYME7** [comment]
Might make the codebase messy, but how about we have a separate/specific max size for floating windows? 

That's intuitive IMO, layouts like dwindle,master and scrolling have algorithms to where to position/resize on the screen. While Floating is too random.(last tile size which might be too big e.g dolphin and many more)


Setting a general max floating size should solve all of the randomness. 

However I understand if this contradicts any protocol(including future ones). Hard coding them all in our configs is an option too.🥲
