### PR TITLE
fix crash

### LINKED ISSUE #711: New crash!
This is not that easy to reproduce, but i get it to crash eventually if i try long enough.
It  happens when i group all 3 windows of a workspace together.
Than activate fullscreen, changegroupactive a few times and then finally togglegroup makes it crash.
As mentioned this is happening not every time, sometimes it does the first try, sometimes it takes a while.
[coredump.log](https://github.com/hyprwm/Hyprland/files/9624444/coredump.log)

### PR DESCRIPTION
**Pull request by Dickby**
#### Describe your PR, what does it fix/add?
Fixes #711

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I'm pretty shure this is not how you would do it!
there is a problem in toggleWindowGroup if that group is in fullscreen mode.
I think the pPrevious- and pNextGroupMember of the first window are set to nullptr, after that 
the nextGroupMember calls getGroupMemberCount, but with a Pointer to a group member that
has it's next prev pointers nulled, getGroupMemberCount will crash.
Since it is a crashing bug, if you don't have time to fix it yourself, use this first?

#### Is it ready for merging, or does it need work?
I think yes.
It's not a big change, look at it, what could possibly go wrong!?

### CODE REVIEW

File: src/layout/DwindleLayout.cpp [hunk 1]
```diff
@@ -818,9 +818,18 @@ void CHyprDwindleLayout::toggleWindowGroup(CWindow* pWindow) {
 
             PWINDOW->m_bHidden = false;
         }
+	    
+	if(PHEAD->pPreviousGroupMember)
+	{
```
Comment (vaxerski) [inline src/layout/DwindleLayout.cpp:823]: style: indent is 4 and braces are not on newlines

Comment (Dickby) [reply src/layout/DwindleLayout.cpp]: done?

Comment (vaxerski) [reply src/layout/DwindleLayout.cpp]: ugh

Comment (Dickby) [reply src/layout/DwindleLayout.cpp]: what?

Comment (vaxerski) [reply src/layout/DwindleLayout.cpp]: fixed it for you. Why cant you just look around how code looks like..

Comment (Dickby) [reply src/layout/DwindleLayout.cpp]: well thanks, i guess.
I will try harder next time!
