### PR TITLE
Bug fix for hyprctl --batch doesn't work with exec rules

### LINKED ISSUE #1820: hyprctl --batch doesn't work with exec rules
I'm trying to do something like this:
```bash
hyprctl --batch "\
dispatch exec [noanim;float;workspace name:$SELECTED silent] kitty;\
etc..."
```

The rules for exec in square brackets don't work because the semicolon is used as delimiter for the batch command as well.

### PR DESCRIPTION
**Pull request by Jakenv**
#### Describe your PR, what does it fix/add?
Fixes #1820 by ignoring ';' inside brackets [ ]

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

For some reason the only app that was problematic when testing using commands like this -> 
`hyprctl --batch 'dispatch exec [noanim;float;workspace 7 silent] appname; dispatch exec [noanim;float;workspace 6 silent] appname; dispatch exec appname;'` 
was Wezterm, it would spawn on whatever workspace, other than that everything else worked without issues

#### Is it ready for merging, or does it need work?
Yeah, I was testing it with different apps and different combinations of commands and as mentioned above only Wezterm was problematic

### CODE REVIEW

File: src/debug/HyprCtl.cpp [hunk 1]
```diff
@@ -1150,34 +1150,28 @@ static std::string cursorPosRequest(eHyprCtlOutputFormat format, std::string req
...
+        else if (ch == ']')
+            --bracket;
+        else if (ch == ';' && bracket == 0) {
+            curitem = trim(curitem);
+            if (!curitem.empty())
+                reply += g_pHyprCtl->getReply(curitem).append(DELIMITER);
+            curitem.clear();
+            continue;
+        }
+        curitem += ch;
```
Comment (vaxerski) [inline src/debug/HyprCtl.cpp:1174]: this will do a lot of potential reallocs, wouldn't it be better to keep an idx and substring when encountering a ';'?

Comment (Jakenv) [reply src/debug/HyprCtl.cpp]: Yeah, valid. I updated it and removed the constant clearing in favor of substrings. Dunno why I didn't think of it in the first place

File: src/debug/HyprCtl.cpp [hunk 2]
```diff
@@ -1150,34 +1150,26 @@ static std::string cursorPosRequest(eHyprCtlOutputFormat format, std::string req
...
+
+    for (size_t i = 0; i <= request.size(); ++i) {
+        char ch = (i < request.size()) ? request[i] : ';';
+        if (ch == '[')
+            ++bracket;
+        else if (ch == ']')
+            --bracket;
+        else if (ch == ';' && bracket == 0) {
+            if (idx < i)
+                reply += g_pHyprCtl->getReply(trim(request.substr(idx, i - idx))).append(DELIMITER);
```
Comment (vaxerski) [inline src/debug/HyprCtl.cpp:1169]: what about the last argument?
`cmda ; cmdb ; cmdc`
won't cmdc not be parsed? it doesn't have a `;` at the end that we can find.

Comment (Jakenv) [reply src/debug/HyprCtl.cpp:1169]: That is why on line 1162 there is ternary to add virtual ';' for last command, without it last command would get ignored. From my testing everything from commands that end in no ';' or even with multiple ';' in case of miss input will just work.

So stuff like `cmda ; cmdb ; cmdc` or `cmda ; cmdb ; cmdc;;;;;;;` will return "ok" 3 times, ofc if the commands itself do have proper syntax

Comment (Jakenv) [reply src/debug/HyprCtl.cpp:1169]: Let me know if this approach in general is ok for you for this bug fix. This is my first pull request ever so I kinda don't know the dynamics of this lol

Comment (vaxerski) [reply src/debug/HyprCtl.cpp:1169]: right, I am blind.

**Review by vaxerski — APPROVED** [review]
