### PR TITLE
fix(xwayland): prevent clipboard race condition

### LINKED ISSUE #9393: xwayland: Clipboard listener sometimes receives empty content
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Not a regression - it's an old bug

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch main at commit f83fe9986b34c53c67b113a015d54fe8c084e9bd dirty (protocols: add version 2 of ext-idle-notify-v1 protocol  (8959)).
Date: Tue Feb 11 14:58:43 2025
Tag: v0.47.0-66-gf83fe9986, commits: 5808
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: Arch
Release: 6.13.2-2-cachyos
Version: #1 SMP PREEMPT_DYNAMIC Sat, 08 Feb 2025 11:26:09 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When copying continuously in an Xwayland client, the clipboard listener sometimes receives empty content. When selecting text in an xwayland client, there is no information similar to `zwlr_data_control_device_v1#3.data_offer`, whereas KDE does have it.

<details>
<summary>log</summary>

```bash
WAYLAND_DEBUG=1 wl-paste --watch bash -c 'echo -e "\e[32m-----BEGIN-----\e[0m"; cat </dev/stdin; echo -e "\n\e[32m------END------\e[0m"'
[2931506.752] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[2931506.761] {Default Queue}  -> wl_display#1.sync(new id wl_callback#3)
[2931506.918] {Display Queue} wl_display#1.delete_id(3)
[2931506.928] {Default Queue} wl_registry#2.global(1, "wl_seat", 9)
[2931506.933] {Default Queue}  -> wl_registry#2.bind(1, "wl_seat", 2, new id [unknown]#4)
[2931506.936] {Default Queue} wl_registry#2.global(2, "wl_data_device_manager", 3)
[2931506.939] {Default Queue}  -> wl_registry#2.bind(2, "wl_data_device_manager", 1, new id [unknown]#5)
[2931506.941] {Default Queue} wl_registry#2.global(3, "wl_compositor", 6)
[2931506.943] {Default Queue}  -> wl_registry#2.bind(3, "wl_compositor", 2, new id [unknown]#6)
[2931506.946] {Default Queue} wl_registry#2.global(4, "wl_subcompositor", 1)
[2931506.948] {Default Queue} wl_registry#2.global(5, "wl_shm", 1)
[2931506.950] {Default Queue}  -> wl_registry#2.bind(5, "wl_shm", 1, new id [unknown]#7)
[2931506.952] {Default Queue} wl_registry#2.global(6, "wp_viewporter", 1)
[2931506.954] {Default Queue} wl_registry#2.global(7, "wp_tearing_control_manager_v1", 1)
[2931506.956] {Default Queue} wl_registry#2.global(8, "wp_fractional_scale_manager_v1", 1)
[2931506.960] {Default Queue} wl_registry#2.global(9, "zxdg_output_manager_v1", 3)
[2931506.962] {Default Queue} wl_registry#2.global(10, "wp_cursor_shape_manager_v1", 1)
[2931506.964] {Default Queue} wl_registry#2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[2931506.966] {Default Queue} wl_registry#2.global(12, "zwp_relative_pointer_manager_v1", 1)
[2931506.974] {Default Queue} wl_registry#2.global(13, "zxdg_decoration_manager_v1", 1)
[2931506.976] {Default Queue} wl_registry#2.global(14, "wp_alpha_modifier_v1", 1)
[2931506.980] {Default Queue} wl_registry#2.global(15, "zwlr_gamma_control_manager_v1", 1)
[2931506.984] {Default Queue} wl_registry#2.global(16, "ext_foreign_toplevel_list_v1", 1)
[2931506.987] {Default Queue} wl_registry#2.global(17, "zwp_pointer_gestures_v1", 3)
[2931506.990] {Default Queue} wl_registry#2.global(18, "zwlr_foreign_toplevel_manager_v1", 3)
[2931506.995] {Default Queue} wl_registry#2.global(19, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2931506.998] {Default Queue} wl_registry#2.global(20, "zwp_text_input_manager_v1", 1)
[2931507.002] {Default Queue} wl_registry#2.global(21, "zwp_text_input_manager_v3", 1)
[2931507.006] {Default Queue} wl_registry#2.global(22, "zwp_pointer_constraints_v1", 1)
[2931507.009] {Default Queue} wl_registry#2.global(23, "zwlr_output_power_manager_v1", 1)
[2931507.013] {Default Queue} wl_registry#2.global(24, "xdg_activation_v1", 1)
[2931507.016] {Default Queue}  -> wl_registry#2.bind(24, "xdg_activation_v1", 1, new id [unknown]#8)
[2931507.021] {Default Queue} wl_registry#2.global(25, "ext_idle_notifier_v1", 2)
[2931507.024] {Default Queue} wl_registry#2.global(26, "hyprland_lock_notifier_v1", 1)
[2931507.030] {Default Queue} wl_registry#2.global(27, "ext_session_lock_manager_v1", 1)
[2931507.034] {Default Queue} wl_registry#2.global(28, "zwp_input_method_manager_v2", 1)
[2931507.038] {Default Queue} wl_registry#2.global(29, "zwp_virtual_keyboard_manager_v1", 1)
[2931507.041] {Default Queue} wl_registry#2.global(30, "zwlr_virtual_pointer_manager_v1", 2)
[2931507.045] {Default Queue} wl_registry#2.global(31, "zwlr_output_manager_v1", 4)
[2931507.049] {Default Queue} wl_registry#2.global(32, "org_kde_kwin_server_decoration_manager", 1)
[2931507.053] {Default Queue} wl_registry#2.global(33, "hyprland_focus_grab_manager_v1", 1)
[2931507.056] {Default Queue} wl_registry#2.global(34, "zwp_tablet_manager_v2", 1)
[2931507.061] {Default Queue} wl_registry#2.global(35, "zwlr_layer_shell_v1", 5)
[2931507.064] {Default Queue} wl_registry#2.global(36, "wp_presentation", 1)
[2931507.067] {Default Queue} wl_registry#2.global(37, "xdg_wm_base", 6)
[2931507.070] {Default Queue}  -> wl_registry#2.bind(37, "xdg_wm_base", 1, new id [unknown]#9)
[2931507.075] {Default Queue} wl_registry#2.global(38, "zwlr_data_control_manager_v1", 2)
[2931507.079] {Default Queue}  -> wl_registry#2.bind(38, "zwlr_data_control_manager_v1", 2, new id [unknown]#10)
[2931507.082] {Default Queue} wl_registry#2.global(39, "zwp_primary_selection_device_manager_v1", 1)
[2931507.086] {Default Queue}  -> wl_registry#2.bind(39, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]#11)
[2931507.091] {Default Queue} wl_registry#2.global(40, "xwayland_shell_v1", 1)
[2931507.096] {Default Queue} wl_registry#2.global(41, "zwlr_screencopy_manager_v1", 3)
[2931507.098] {Default Queue} wl_registry#2.global(42, "hyprland_toplevel_export_manager_v1", 2)
[2931507.100] {Default Queue} wl_registry#2.global(43, "hyprland_global_shortcuts_manager_v1", 1)
[2931507.103] {Default Queue} wl_registry#2.global(44, "xdg_dialog_v1", 1)
[2931507.108] {Default Queue} wl_registry#2.global(45, "wp_single_pixel_buffer_manager_v1", 1)
[2931507.110] {Default Queue} wl_registry#2.global(46, "wp_security_context_manager_v1", 1)
[2931507.112] {Default Queue} wl_registry#2.global(47, "hyprland_ctm_control_manager_v1", 2)
[2931507.114] {Default Queue} wl_registry#2.global(48, "hyprland_surface_manager_v1", 2)
[2931507.116] {Default Queue} wl_registry#2.global(49, "wp_content_type_manager_v1", 1)
[2931507.122] {Default Queue} wl_registry#2.global(50, "wp_drm_lease_device_v1", 1)
[2931507.124] {Default Queue} wl_registry#2.global(51, "wp_linux_drm_syncobj_manager_v1", 1)
[2931507.126] {Default Queue} wl_registry#2.global(52, "wl_drm", 2)
[2931507.128] {Default Queue} wl_registry#2.global(53, "zwp_linux_dmabuf_v1", 5)
[2931507.130] {Default Queue} wl_registry#2.global(54, "wl_output", 4)
[2931507.134] {Default Queue} wl_callback#3.done(2918)
[2931507.142] {Default Queue}  -> wl_display#1.sync(new id wl_callback#3)
[2931507.312] {Display Queue} wl_display#1.delete_id(3)
[2931507.315] {Default Queue} wl_seat#4.name("Hyprland")
[2931507.317] {Default Queue} wl_seat#4.capabilities(3)
[2931507.319] {Default Queue} discarded wl_shm#7.format(0)
[2931507.321] {Default Queue} discarded wl_shm#7.format(1)
[2931507.323] {Default Queue} discarded wl_shm#7.format(875709016)
[2931507.324] {Default Queue} discarded wl_shm#7.format(875708993)
[2931507.329] {Default Queue} discarded wl_shm#7.format(808669784)
[2931507.331] {Default Queue} discarded wl_shm#7.format(808669761)
[2931507.332] {Default Queue} discarded wl_shm#7.format(808665688)
[2931507.334] {Default Queue} discarded wl_shm#7.format(808665665)
[2931507.335] {Default Queue} wl_callback#3.done(2918)
[2931507.338] {Default Queue}  -> zwlr_data_control_manager_v1#10.get_data_device(new id zwlr_data_control_device_v1#3, wl_seat#4)
[2931507.417] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190080)
[2931507.421] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("SAVE_TARGETS")
[2931507.423] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("MULTIPLE")
[2931507.425] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("STRING")
[2931507.426] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("text/plain")
[2931507.428] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("text/plain;charset=utf-8")
[2931507.430] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("chromium/x-source-url")
[2931507.432] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("chromium/x-web-custom-data")
[2931507.434] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("text/html")
[2931507.436] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("text/plain")
[2931507.438] {Default Queue} zwlr_data_control_offer_v1#4278190080.offer("text/plain;charset=utf-8")
[2931507.440] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190080)
[2931507.448] {Default Queue}  -> zwlr_data_control_offer_v1#4278190080.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
static
------END------
[2931509.819] {Default Queue}  -> zwlr_data_control_offer_v1#4278190080.destroy()
[2931509.830] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2931509.832] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("TEXT")
[2931509.834] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2931509.836] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("UTF8_STRING")
[2931509.838] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2931509.839] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2931509.841] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2931509.842] {Default Queue} zwlr_data_control_device_v1#3.primary_selection(zwlr_data_control_offer_v1#4278190081)
[2931509.845] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2937740.384] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2937740.402] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2937740.408] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2937740.413] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2937740.418] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2937740.424] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2937740.431] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2937740.435] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2937740.439] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2937740.444] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2937740.449] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2937740.453] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2937740.474] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
clipboard
------END------
[2937743.042] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2939350.825] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2939350.839] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2939350.844] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2939350.845] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2939350.848] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2939350.849] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2939350.852] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2939350.855] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2939350.857] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2939350.860] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2939350.862] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2939350.865] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2939350.876] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
window
------END------
[2939352.847] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2940612.580] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2940612.608] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2940612.620] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2940612.630] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2940612.638] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2940612.644] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2940612.652] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2940612.660] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2940612.665] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2940612.675] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2940612.684] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2940612.691] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2940612.725] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
xcb_create_window
------END------
[2940614.773] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2943657.645] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2943657.666] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2943657.674] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2943657.680] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2943657.685] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2943657.690] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2943657.696] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2943657.701] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2943657.706] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2943657.711] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2943657.716] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2943657.721] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2943657.742] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
mask
------END------
[2943659.697] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2945486.946] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2945486.965] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2945486.971] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2945486.975] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2945486.977] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2945486.981] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2945486.983] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2945486.987] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2945486.991] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2945486.995] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2945486.999] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2945487.002] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2945487.021] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
XCB_XFIXES_SELECTION_EVENT_MASK_SET_SELECTION_OWNER
------END------
[2945489.491] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2947400.911] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2947400.940] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2947400.952] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2947400.961] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2947400.969] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2947400.976] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2947400.984] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2947400.992] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2947400.999] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2947401.006] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2947401.014] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2947401.023] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2947401.050] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
clipboard
------END------
[2947403.982] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2948674.970] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2948674.988] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2948674.993] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2948674.998] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2948675.002] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2948675.006] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2948675.010] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2948675.014] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2948675.018] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2948675.021] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2948675.025] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2948675.029] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2948675.043] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
listeners
------END------
[2948677.754] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2951486.564] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2951486.577] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2951486.580] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2951486.585] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2951486.588] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2951486.596] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2951486.599] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2951486.605] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2951486.608] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2951486.613] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2951486.615] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2951486.620] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2951486.636] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
dndSelection
------END------
[2951489.016] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2953685.022] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2953685.038] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2953685.041] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2953685.044] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2953685.046] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2953685.048] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2953685.050] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2953685.051] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2953685.053] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2953685.055] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2953685.057] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2953685.059] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2953685.071] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----

------END------
[2953688.086] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2956047.411] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2956047.438] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2956047.449] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2956047.455] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2956047.464] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2956047.472] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2956047.481] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2956047.488] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2956047.495] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2956047.503] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2956047.510] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2956047.517] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2956047.544] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
xcb_change_property
------END------
[2956050.069] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2961208.385] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2961208.400] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2961208.403] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2961208.406] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2961208.408] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2961208.410] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2961208.412] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2961208.414] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2961208.415] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2961208.417] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2961208.422] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2961208.424] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2961208.437] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----

------END------
[2961210.979] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
[2965549.383] {Default Queue} zwlr_data_control_device_v1#3.data_offer(new id zwlr_data_control_offer_v1#4278190081)
[2965549.399] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("SAVE_TARGETS")
[2965549.406] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("MULTIPLE")
[2965549.410] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("STRING")
[2965549.415] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2965549.419] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2965549.424] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-source-url")
[2965549.428] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("chromium/x-web-custom-data")
[2965549.434] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/html")
[2965549.436] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain")
[2965549.439] {Default Queue} zwlr_data_control_offer_v1#4278190081.offer("text/plain;charset=utf-8")
[2965549.441] {Default Queue} zwlr_data_control_device_v1#3.selection(zwlr_data_control_offer_v1#4278190081)
[2965549.465] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.receive("text/plain;charset=utf-8", fd 6)
-----BEGIN-----
source
------END------
[2965551.922] {Default Queue}  -> zwlr_data_control_offer_v1#4278190081.destroy()
```
</details>

### How to reproduce

1. `pkill wl-paste`
2. Run command `WAYLAND_DEBUG=1 wl-paste --watch bash -c 'echo -e "\e[32m-----BEGIN-----\e[0m"; cat </dev/stdin; echo -e "\n\e[32m------END------\e[0m"'`
3. Copying continuously in an XWayland client and viewing the terminal output.

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [ ] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

_No response_

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes #9393

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
this is ready

File: src/xwayland/XDataSource.cpp [hunk 1]
```diff
@@ -71,19 +71,20 @@ void CXDataSource::send(const std::string& mime, CFileDescriptor fd) {
...
-    xcb_convert_selection(g_pXWayland->pWM->connection, selection.transfer->incomingWindow, HYPRATOMS["CLIPBOARD"], mimeAtom, HYPRATOMS["_WL_SELECTION"], XCB_TIME_CURRENT_TIME);
+    xcb_convert_selection(g_pXWayland->pWM->connection, transfer->incomingWindow, HYPRATOMS["CLIPBOARD"], mimeAtom, HYPRATOMS["_WL_SELECTION"], XCB_TIME_CURRENT_TIME);
 
     xcb_flush(g_pXWayland->pWM->connection);
 
     //TODO: make CFileDescriptor setflags take SETFL aswell
     fcntl(fd.get(), F_SETFL, O_WRONLY | O_NONBLOCK);
-    selection.transfer->wlFD = std::move(fd);
+    transfer->wlFD = std::move(fd);
+    selection.transfers.push_back(std::move(transfer));
```
Comment (vaxerski) [inline src/xwayland/XDataSource.cpp:87]: emplace

File: src/xwayland/XWM.cpp [hunk 2]
```diff
@@ -1177,17 +1177,50 @@ static int writeDataSource(int fd, uint32_t mask, void* data) {
 void CXWM::getTransferData(SXSelection& sel) {
     Debug::log(LOG, "[xwm] getTransferData");
 
-    sel.transfer->getIncomingSelectionProp(true);
+    auto it = std::find_if(sel.transfers.begin(), sel.transfers.end(), [](const auto& t) { return !t->propertyReply; });
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:1180]: use ranges

File: src/xwayland/XWM.cpp [hunk 3]
```diff
@@ -1290,16 +1323,21 @@ void SXSelection::onKeyboardFocus() {
 }
 
 int SXSelection::onRead(int fd, uint32_t mask) {
-    // TODO: support INCR
+    auto it = std::find_if(transfers.begin(), transfers.end(), [fd](const auto& t) { return t->wlFD.get() == fd; });
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:1326]: use ranges

File: src/xwayland/XWM.cpp [hunk 4]
```diff
@@ -1368,18 +1406,26 @@ bool SXSelection::sendData(xcb_selection_request_event_t* e, std::string mime) {
     selection->send(mime, CFileDescriptor{p[1]});
 
     transfer->eventSource = wl_event_loop_add_fd(g_pCompositor->m_sWLEventLoop, transfer->wlFD.get(), WL_EVENT_READABLE, ::readDataSource, this);
+    transfers.push_back(std::move(transfer));
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:1409]: emplace

File: src/xwayland/XWM.cpp [hunk 5]
```diff
@@ -1368,18 +1406,26 @@ bool SXSelection::sendData(xcb_selection_request_event_t* e, std::string mime) {
...
 
     return true;
 }
 
 int SXSelection::onWrite() {
+    auto it = std::find_if(transfers.begin(), transfers.end(), [](const auto& t) { return t->propertyReply; });
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:1415]: ranges

**Comment by nnyyxxxx** [comment]
@vaxerski all done

File: src/xwayland/XWM.cpp [hunk 6]
```diff
@@ -571,9 +571,9 @@ void CXWM::handleSelectionNotify(xcb_selection_notify_event_t* e) {
     SXSelection* sel = getSelection(e->selection);
 
     if (e->property == XCB_ATOM_NONE) {
-        if (sel->transfer) {
+        if (!sel->transfers.empty()) {
             Debug::log(TRACE, "[xwm] converting selection failed");
-            sel->transfer.reset();
+            sel->transfers.clear();
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:576]: are you sure this should clear _all_ transfers and not just the one that failed?

**Review by vaxerski — COMMENTED** [review]
other than that ok

File: src/xwayland/XWM.cpp (hunk 6 above)
Comment (nnyyxxxx) [reply src/xwayland/XWM.cpp:576]: probably

Comment (vaxerski) [reply src/xwayland/XWM.cpp:576]: well I don't think it should unless we have no other option

Comment (nnyyxxxx) [reply src/xwayland/XWM.cpp:576]: okay...

Comment (nnyyxxxx) [reply src/xwayland/XWM.cpp]: all done sir

**Review by vaxerski — APPROVED** [review]
thanku
