### PR TITLE
syncobj: dont crash compositor on protocol errors

### LINKED ISSUE #9624: Wezterm causing Hyprland to crash
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

I don't know, I started using Hyprland only recently

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch main at commit f4315db50f058df3620b1e03a75aa2192aa08c81  (nix: mesa -> libgbm (9612)).
Date: Fri Mar 14 18:24:55 2025
Tag: v0.47.0-144-gf4315db5, commits: 5886
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.2
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: UsesArchBtw
Release: 6.13.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 07 Mar 2025 20:19:00 +0000


GPU information: 
2d:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD103 [GeForce RTX 4080 SUPER] [10de:2702] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  570.124.04  Tue Feb 25 04:12:12 UTC 2025


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

- When I open Wezterm I immediately crash and get sent to a black/blank terminal.

### How to reproduce

1. Open Wezterm (-git version)
2. Crash

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [x] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland_config_dump.txt](https://github.com/user-attachments/files/19256191/hyprland_config_dump.txt)

[hyprlandCrashReport117317.txt](https://github.com/user-attachments/files/19256195/hyprlandCrashReport117317.txt)

### PR DESCRIPTION
**Pull request by gulafaran**
dont call a member on null pointer if client misbehaves. as in the weak pointer being expired.

fixes #9624

wezterm is broken itself.
https://github.com/wezterm/wezterm/issues/6645

### CODE REVIEW

File: src/protocols/DRMSyncobj.cpp [hunk 1]
```diff
@@ -177,14 +177,19 @@ bool CDRMSyncobjSurfaceResource::protocolError() {
...
     }
 
-    if (surface->pending.buffer->acquire->timeline() == surface->pending.buffer->release->timeline()) {
+    if (!surface->pending.buffer->release || !surface->pending.buffer->release->timeline()) {
+        resource->error(WP_LINUX_DRM_SYNCOBJ_SURFACE_V1_ERROR_NO_RELEASE_POINT, "Missing release timeline");
+        surface->pending.rejected = true;
+        return true;
+    }
+
+    if (surface->pending.buffer->acquire->timeline().lock() == surface->pending.buffer->release->timeline().lock()) {
```
Comment (vaxerski) [inline src/protocols/DRMSyncobj.cpp:192]: double .lock() is redundant

Comment (gulafaran) [reply src/protocols/DRMSyncobj.cpp]: removed.

**Review by vaxerski — APPROVED** [review]
