### PR TITLE
fix(renderer): clamp rounding_power

### LINKED ISSUE #10779: rounding_power is not clamped
### Discussion link
https://github.com/hyprwm/Hyprland/discussions/10778

## Description

Things get weird when you forcefully set it too high.

### PR DESCRIPTION
**Pull request by rrvsh**
#### Describe your PR, what does it fix/add?

Simple fix to clamp rounding_power from 2.0 to 10.0 as noted in the wiki https://wiki.hypr.land/Configuring/Variables/#decoration

Closes #10779

### CODE REVIEW

File: src/desktop/Window.cpp [hunk 1]
```diff
@@ -1186,7 +1186,9 @@ float CWindow::rounding() {
 float CWindow::roundingPower() {
     static auto PROUNDINGPOWER = CConfigValue<Hyprlang::FLOAT>("decoration:rounding_power");
 
-    return m_windowData.roundingPower.valueOr(*PROUNDINGPOWER);
+    float       value = *PROUNDINGPOWER;
+    value             = std::clamp(value, 2.0f, 10.0f);
```
Comment (vaxerski) [inline src/desktop/Window.cpp]: why shooting it out into 2 lines? `const float value = std::clamp(*PROUNDINGPOWER, ...)`

You could even make it into one line by combining with the valueOr bewlow

Comment (rrvsh) [reply src/desktop/Window.cpp]: left in from debugging lol

**Comment by rrvsh** [comment]
force push to make the diff more concise and rebased to latest commit on main
