### PR TITLE
bind: new long press option

### LINKED ISSUE #8245: Long press bind(not repeat)
### Description

So I want to:
Press XF86AudioNext then play next,
long press XF86AudioNext then skip 15sec

which binde will not work becuz:
1. its different command
2. it just repeat instead of executing it after long press

### PR DESCRIPTION
**Pull request by littleblack111**
#### Describe your PR, what does it fix/add?
closes #8245, described there too

#### Is it ready for merging, or does it need work?
ready

### CODE REVIEW

File: src/managers/KeybindManager.cpp [hunk 1]
```diff
@@ -701,6 +715,16 @@ SDispatchResult CKeybindManager::handleKeybinds(const uint32_t modmask, const SP
             }
         }
 
+		if (k.longPress) {
+            m_pActiveKeybind            = &k;
+            m_pActiveKeybindEventSource = wl_event_loop_add_timer(g_pCompositor->m_sWLEventLoop, longPressHandler, &m_pActiveKeybind);
+
+            const auto PACTIVEKEEB = g_pSeatManager->keyboard.lock();
+
+            wl_event_source_timer_update(m_pActiveKeybindEventSource, PACTIVEKEEB->repeatDelay);
```
Comment (vaxerski) [inline src/managers/KeybindManager.cpp:724]: please don't use event sources. See managers/eventLoop/EventLoopTimer.

File: src/managers/KeybindManager.cpp [hunk 2]
```diff
@@ -567,6 +567,20 @@ int repeatKeyHandler(void* data) {
     return 0;
 }
 
+int longPressHandler(void* data) {
+    SKeybind** ppActiveKeybind = (SKeybind**)data;
+
+    if (!*ppActiveKeybind || g_pSeatManager->keyboard.expired())
```
Comment (vaxerski) [inline src/managers/KeybindManager.cpp:573]: kinda sucks. Why not remove the timer on key up?

File: src/config/ConfigManager.cpp [hunk 3]
```diff
@@ -2184,6 +2185,8 @@ std::optional<std::string> CConfigManager::handleBind(const std::string& command
             ignoreMods = true;
         } else if (arg == 's') {
             multiKey = true;
+		} else if (arg == 'o') {
+			longPress = true;
```
Comment (vaxerski) [inline src/config/ConfigManager.cpp:2189]: requires a check for incompatibilities. for example, long press + release makes no sense.

further down you'll see some checks that return an error

**Review by vaxerski — COMMENTED** [review]
also needs a clang-format

File: src/managers/KeybindManager.cpp (hunk 1 above)
Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: do you want me to include "eventLoop/EventLoopTimer.hpp"?

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: ye

File: src/managers/KeybindManager.cpp (hunk 2 above)
Comment (vaxerski) [reply src/managers/KeybindManager.cpp:573]: no, if there is a long press pending and any key is pressed/released it should reset the timer, probably. Though idk how that will work with transient ones.... actually leave it as is I guess.

File: src/managers/KeybindManager.cpp (hunk 1 above)
Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: shall i do it in the hpp or cpp?

File: src/managers/KeybindManager.cpp (hunk 2 above)
Comment (littleblack111) [reply src/managers/KeybindManager.cpp:573]: > Though idk how that will work with transient ones
wdym? should i try implement it and check via armed() func(from CEventLoopTimer)?

File: src/managers/KeybindManager.cpp (hunk 1 above)
Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: i tried:
```
            m_pActiveKeybind            = &k;

            const auto PACTIVEKEEB = g_pSeatManager->keyboard.lock();

			m_pLongPressTimer = makeShared<CEventLoopTimer>(
				std::chrono::milliseconds(PACTIVEKEEB->repeatDelay),
				longPressHandler,
				&m_pActiveKeybind
			);

			g_pEventLoopManager->addTimer(m_pLongPressTimer);
```

not sure why now it doesn't work anymore.
(m_pLongPressTimer is in the .hpp file)

File: src/managers/KeybindManager.cpp (hunk 2 above)
Comment (vaxerski) [reply src/managers/KeybindManager.cpp:573]: na dw

File: src/managers/KeybindManager.cpp (hunk 1 above)
Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: the timer should be created in the constructor, then here you'd call setTimeout instead

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: im sorry that im not very familiar with the codebase, but adding the timer in the constructor and calling updateTimer later in k.longPress doesn't seem to trigger the handler(as i cant see it from the log)

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: See here:
https://github.com/hyprwm/Hyprland/blob/180c26ada6233c3c59c331cb14a64aac1eeb2941/src/managers/AnimationManager.cpp#L31-L32

instead of the timeout, here we'd do `std::nullopt` instead as there is no initial time.

```cpp
m_pLongPressTimer = makeShared<CEventLoopTimer>(
				std::nullopt,
				longPressHandler,
				nullptr
			);

			g_pEventLoopManager->addTimer(m_pLongPressTimer);
```

in the ctor.

Then, here, instead:
```cpp
m_pLongPressTimer->updateTimeout(std::chrono::milliseconds(repeatDelay));
m_pLastLongPressKeybind = &k;
```

now, in the handler, just check if `m_pLastKeybind == m_pLastLongPressKeybind`

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: i see. do i define the longpresshandler in the constructure too then? and what is m_pLastKeybind? and should i pass in `this` instead of nullptr since i'd need to access the p_activekeybind

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: >  in the constructure too then(since it'd be out of scope otherwise)

you can throw it into a lambda, sure.

> And what is m_pLastKeybind

you used it yourself, a member of CKeybindManager. `m_pLastLongPressKeybind` is a new one I added for the sake of this functionality

> and should i pass in this instead of nullptr since i'd need to access the m_pactivekeybind

Nope! Throw it into a lambda and use an explicit `this` catch with `[this]`

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: >  >And what is m_pLastKeybind

> you used it yourself, a member of CKeybindManager. m_pLastLongPressKeybind is a new one I added for the sake of this functionality

wait, you meant m_pActiveKeybind?

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: Ok, after trying to directly reference the class functions in a [this] lambda func.
this is what happens,
```
			if (!m_pActiveKeybind)
				return 0;
```
result in
```
(EE) failed to read Wayland events: Broken pipe
[1]    1217210 illegal hardware instruction (core dumped)  ./build/Hyprland
```
stuff using it:
```
			SKeybind** ppActiveKeybind = (SKeybind**)m_pActiveKeybind;
        if (!*ppActiveKeybind)
return 0
```
raises SEGEV

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: I need to see the entire code

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: here:
```
	m_pLongPressTimer = makeShared<CEventLoopTimer>(
		std::nullopt,
		[this](SP<CEventLoopTimer> self, void* data) {
			SKeybind** ppActiveKeybind = (SKeybind**)m_pActiveKeybind;

			if (!m_pActiveKeybind) // wayland broken pipe then crash
				return 0;

			if (!*ppActiveKeybind || g_pSeatManager->keyboard.expired()) // SEGEV
				return 0;

			// const auto DISPATCHER = g_pKeybindManager->m_mDispatchers.find((*ppActiveKeybind)->handler);

			// Debug::log(LOG, "Keybind long press triggered, calling dispatcher.");
			// DISPATCHER->second((*ppActiveKeybind)->arg);
		},
		nullptr
	);

```

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: you didn't add it in the ctor `g_pEventLoopManager->addTimer`

Comment (littleblack111) [reply src/managers/KeybindManager.cpp:724]: sry, didn't specify but i did add it...

Comment (vaxerski) [reply src/managers/KeybindManager.cpp:724]: push the code and I'll fix it

Comment (littleblack111) [reply src/managers/KeybindManager.cpp]: sure, here

Comment (vaxerski) [reply src/managers/KeybindManager.cpp]: remind me tomorrow if I don't fix it, I'm quite busy today but should be able to fix this in the deep evening

Comment (littleblack111) [reply src/managers/KeybindManager.cpp]: ya you forgot lol. @vaxerski

Comment (vaxerski) [reply src/managers/KeybindManager.cpp]: I'll do it tomorrow, super tired today, dw I have this open in a separate tab

**Comment by vaxerski** [comment]
fixed and rebased, check now.

**Comment by littleblack111** [comment]
lgtm, ready for merge

**Review by vaxerski — DISMISSED** [review]
needs a wiki mr

**Comment by littleblack111** [comment]
wait no, bindo should make the other bind = not work unless its released before the timer.

i.e. if i have a bind = playerctl position +5 and a bindo = playerctl next
in this example, it might be not obv since if u want to go next, u'd prob not care abt current progress.

solution i can think of rn: bind need to check if theres a bindo for the keybind and if so, only execute the action if on release the timer is not trigger yet, effectively making it bindr(i.e. make bind act like bindr if theres a bindo for it)

**Comment by littleblack111** [comment]
sorry, i don't know how should i make it still call the dispatcher after the `continue;`(on release)

**Comment by littleblack111** [comment]
alright then

**Comment by vaxerski** [comment]
idk tbh but I have a feeling this is unnecessary clutter for an already cluttered and messy system

**Comment by littleblack111** [comment]
alright then. lets just finish it here, pls review the wiki pr

**Comment by vaxerski** [comment]
by that I kinda meant this entire PR.

**Comment by littleblack111** [comment]
...idk, but I do feel like this is a quite basic functionality for binds

**Comment by vaxerski** [comment]
idk, can you name a single other wayland environment that has this...?

**Comment by littleblack111** [comment]
No.. but hyprland advertised
> Not afraid to provide bleeding-edge features
Also, I'm pretty sure people will want this

**Comment by vaxerski** [comment]
fair

**Review by vaxerski — APPROVED** [review]

**Comment by Havner** [comment]
Just FYI, I've stumbled upon this PR when configuring long presses in Hyprland. I don't know if there is any well know solution for long press inhibiting the short one but I didn't find any.

> hm... at this point, you're better off just scripting it I believe. It's completely possible with transparent binds, no?
>
> ```ini
> bindt = SUPER, O, exec, ~/myScript.sh DOWN
> bindrt = SUPER, O, exec, ~/myScript.sh UP
> ```
> 
> Then your script on UP calculates the Δt and does a `hyprctl dispatch` with your command of choice

I had a go at this idea: https://github.com/Havner/hyprlong/blob/orig/src/main.rs
And it worked, but unintuitevely. You had to release the press for long press to trigger which meant you actually didn't know if the long time has passed or not until you released.

The simpler idea actually utilizing this PR is this: https://github.com/Havner/hyprlong

Again, just FYI if someone stumbles upon this. Maybe there is something simpler I haven't found.
