### PR TITLE
fix setting xwayland title prop

### LINKED ISSUE #6790: XWayland windows won't change title or class
### Regression?

Yes, first bad commit is addd3e7f

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: levi-machine
Release: 6.9.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000


GPU information: 
1f:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/levi/.config/hypr/hyprland.conf: Read Succeeded


#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#


# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-3,1920x1080,0x0,1
monitor=HDMI-A-1,1920x1080,1920x0,1
monitor=DP-2,1920x1080,3840x0,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = waybar & hyprpaper
exec-once = hypridle
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

# Some default env vars.
env = XCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = QT_QPA_PLATFORM,wayland
env = WLR_DRM_NO_ATOMIC,1
# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:none
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

debug {
	disable_logs = false
}
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true 
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 to disable the anime mascot wallpapers
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, exec, firefox 
bind = $mainMod SHIFT, Escape, exit 
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod SHIFT, Space, togglefloating, 
bind = $mainMod, D, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, T, togglesplit, # dwindle
bind = $mainMod, F, fullscreen, 0
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, L, exec, hyprlock
# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, left, movewindow,l
bind = $mainMod SHIFT, up, movewindow,u
bind = $mainMod SHIFT, down, movewindow, d 
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = ,XF86AudioRaiseVolume, exec, pulsemixer --change-volume +5
bind = ,XF86AudioLowerVolume, exec, pulsemixer --change-volume -5
bind = ,XF86AudioMute, exec, pulsemixer --toggle-mute
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Livesplit hotkeys
bind = ,Numpad0, pass, title:.*LiveSplit.*
bind = ,Numpad1, pass, title:.*LiveSplit.*
bind = ,Numpad2, pass, title:.*LiveSplit.*
bind = ,Numpad3, pass, title:.*LiveSplit.*
bind = ,Numpad4, pass, title:.*LiveSplit.*
bind = ,Numpad5, pass, title:.*LiveSplit.*
bind = ,Numpad6, pass, title:.*LiveSplit.*
bind = ,Numpad7, pass, title:.*LiveSplit.*
bind = ,Numpad8, pass, title:.*LiveSplit.*
bind = ,Numpad9, pass, title:.*LiveSplit.*

bind = $mainMod,x, exec, ~/undertale1.01/run.sh
windowrule = rounding 0, title:.*Livesplit.*
windowrule = float, title:.*Livesplit.*

windowrule = float, title:UNDERTALE
windowrule = immediate, title:UNDERTALE

======Config-End========
```

</details>

### Description

When an XWayland window tries to update it's title or class, the title and class do not update

### How to reproduce

1. Open discord, or another XWayland app that regularly changes it's window title.
2. Observe the window title
3. Switch to a different channel
4. Observe that the window title doesn't change.

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes #6790

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
other props were also not being set so there may be some more xwayland bugs revealed now

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

File: src/xwayland/XWM.cpp [hunk 1]
```diff
@@ -172,8 +172,10 @@ void CXWM::readProp(SP<CXWaylandSurface> XSURF, uint32_t atom, xcb_get_property_
             XSURF->state.appid.pop_back();
         XSURF->events.metadataChanged.emit();
     } else if (atom == XCB_ATOM_WM_NAME || atom == HYPRATOMS["_NET_WM_NAME"]) {
-        size_t len         = xcb_get_property_value_length(reply);
-        char*  string      = (char*)xcb_get_property_value(reply);
+        size_t len    = xcb_get_property_value_length(reply);
+        char*  string = (char*)xcb_get_property_value(reply);
+        if (reply->type != HYPRATOMS["UTF8_STRING"])
```
Comment (vaxerski) [inline src/xwayland/XWM.cpp:177]: what about `TEXT`?

Comment (ikalco) [reply src/xwayland/XWM.cpp]: also added XCB_ATOM_STRING cause it was showing up in logs and was still utf8

**Review by vaxerski — APPROVED** [review]
thanks!
