### PR TITLE
fix(xwayland): prevent invalid window configurations for X11 apps

### LINKED ISSUE #9252: XTerm do longer works with 0.47.1
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.1 built from branch  at commit 75dff7205f6d2bd437abfb4196f700abee92581a  (version: bump to 0.47.1).
Date: Wed Jan 29 23:19:39 2025
Tag: v0.47.1, commits: 5756
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: tdc-mm
Release: 6.12.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 18 Jan 2025 02:26:57 +0000


GPU information: 
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104M [GeForce RTX 4080 Max-Q / Mobile] [10de:27e0] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.77  Release Build  (archlinux-builder@tdc-mm)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

After updating to 0.47.1, I noticed that I cannot use XTerm any longer. Trying to run XTerm opens its window for a split second and XTerm then dies with the following error:

```
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
xterm: warning, error event received:
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  446
  Current serial number in output stream:  612
```

This definitely worked with 0.46, I don't know about 0.47.0.

### How to reproduce

1. Launch Hyprland
2. Try to start `xterm`

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland_config_dump.txt](https://github.com/user-attachments/files/18614811/hyprland_config_dump.txt)

[hyprland.log](https://github.com/user-attachments/files/18614813/hyprland.log)

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes #9252

### CODE REVIEW

**Comment by PaideiaDilemma** [comment]
Wait letting size be 1x1 is a weird fix. Wouldn't it be better to avoid sending this configure in the first place?

File: src/desktop/Window.cpp [hunk 1]
```diff
@@ -1717,6 +1717,8 @@ void CWindow::sendWindowSize(Vector2D size, bool force, std::optional<Vector2D>
         windowPos += PMONITOR->vecXWaylandPosition;
     }
 
+    windowPos = windowPos.clamp(Vector2D{0, 0}, Vector2D{std::numeric_limits<double>::infinity(), std::numeric_limits<double>::infinity()});
```
Comment (PaideiaDilemma) [inline src/desktop/Window.cpp:1720]: negative window positions should be ok right?

**Comment by nnyyxxxx** [comment]
> Wait letting size be 1x1 is a weird fix. Wouldn't it be better to avoid sending this configure in the first place?

1x1 min size is actually correct x11 doesnt allow 0x0 sizes

**Comment by nnyyxxxx** [comment]
https://github.com/hyprwm/Hyprland/commit/445acec2a29adbb30196d8b92f86270a038b7ee5

**Review by vaxerski — APPROVED** [review]

**Comment by PaideiaDilemma** [comment]
> 1x1 min size is actually correct x11 doesnt allow 0x0 sizes

Yeah but this function is not xwayland exclusive and honestly why would we ever want to configure a window with size 1x1??

**Comment by nnyyxxxx** [comment]
well not sending it results in the same error as #9252 , i think 1x1 is a great size for this..
