### PR TITLE
fix(exec): redirect app output to /dev/null

### LINKED ISSUE #9278: After exit I get Error if I left a application open
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect), Probably not a regression / I don't remember it happening before, I don't know, I started using Hyprland only recently

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.1 built from branch  at commit 75dff7205f6d2bd437abfb4196f700abee92581a  (version: bump to 0.47.1).
Date: Wed Jan 29 23:19:39 2025
Tag: v0.47.1, commits: 5756
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: KURBAN
Release: 6.12.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 18 Jan 2025 02:26:57 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28a1] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 0b) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.77  Wed Nov 27 23:33:08 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When I don't close up app It kepps give error. As display manager I use LY so every error messed up with screen.

### How to reproduce

1. Open any app (Steam, A Steam Game, Firefox, etc..)
2. Close Hyprland 

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland.log](https://github.com/user-attachments/files/18629494/hyprland.log)
[config.txt](https://github.com/user-attachments/files/18629498/config.txt)

### PR DESCRIPTION
**Pull request by nnyyxxxx**
fixes #9278 

this is a better approach to #1000 and yes waybar opens lol unlike #1013

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
image

left is after, right is before

File: src/managers/KeybindManager.cpp [hunk 1]
```diff
@@ -967,6 +967,14 @@ uint64_t CKeybindManager::spawnRawProc(std::string args, PHLWORKSPACE pInitialWo
                 setenv(e.first.c_str(), e.second.c_str(), 1);
             }
             setenv("WAYLAND_DISPLAY", g_pCompositor->m_szWLDisplaySocket.c_str(), 1);
+
+            int devnull = open("/dev/null", O_WRONLY | O_CLOEXEC);
```
Comment (PaideiaDilemma) [inline src/managers/KeybindManager.cpp:971]: Dosn't that mean that childs will not have a valid STDOUT/STDERR at all (cause O_CLOEXEC)?

Comment (nnyyxxxx) [reply src/managers/KeybindManager.cpp:971]: no

Comment (nnyyxxxx) [reply src/managers/KeybindManager.cpp:971]: the flag only applies to the original file descriptor, dup2 creates new file descriptors that are copies of devnull but the new descriptors do not retain the O_CLOEXEC flag

Comment (PaideiaDilemma) [reply src/managers/KeybindManager.cpp:971]: Makes sense but then why set the flag if you close it manually below?

Comment (PaideiaDilemma) [reply src/managers/KeybindManager.cpp:971]: Ups wait you only do if it's -1 xD

Comment (nnyyxxxx) [reply src/managers/KeybindManager.cpp:971]: habbit, future changes could affect this. good to just set it for caution

**Comment by PaideiaDilemma** [comment]
Also it is the same as #1000 right?
Both MRs leave STDIN open. Is there a reason why? It still points to the tty I think.

I also looked into this (and generally process spawning)
Tried to figure out why #1000 originally caused problem without success. Whatever caused waybar not to start, has probably been fixed.
I think it having both point to /dev/null should not cause any problems.

**Comment by nnyyxxxx** [comment]
i have tried before and after, this one fixes the problem where waybar does not spawn, the other one still has the same problem.

not the same

not sure why the original one causes the issue either tbh

**Comment by nnyyxxxx** [comment]
heres an updated version of #1000 if you want to test for yourself

[diff.txt](https://github.com/user-attachments/files/18809230/diff.txt)

**Comment by PaideiaDilemma** [comment]
I used this on latest commit
```diff
diff --git a/src/managers/KeybindManager.cpp b/src/managers/KeybindManager.cpp
index 8daa6838..768f3198 100644
--- a/src/managers/KeybindManager.cpp
+++ b/src/managers/KeybindManager.cpp
@@ -24,6 +24,8 @@
 #include <string>
 #include <string_view>
 #include <cstring>
+#include <fcntl.h>
+#include <paths.h>
 
 #include <hyprutils/string/String.hpp>
 #include <hyprutils/os/FileDescriptor.hpp>
@@ -967,6 +969,22 @@ uint64_t CKeybindManager::spawnRawProc(std::string args, PHLWORKSPACE pInitialWo
                 setenv(e.first.c_str(), e.second.c_str(), 1);
             }
             setenv("WAYLAND_DISPLAY", g_pCompositor->m_szWLDisplaySocket.c_str(), 1);
+            close(STDOUT_FILENO);
+            close(STDERR_FILENO);
+
+            int devnull = open(_PATH_DEVNULL, O_WRONLY);
+            if (devnull == -1) {
+                Debug::log(LOG, "Unable to open /dev/null for writing");
+            }
+
+            if (dup2(devnull, STDOUT_FILENO) == -1) {
+                Debug::log(LOG, "Unable to duplicate /dev/null to stdout");
+            }
+            if (dup2(devnull, STDERR_FILENO) == -1) {
+                Debug::log(LOG, "Unable to duplicate /dev/null to stderr");
+            }
+
+            close(devnull);
             execl("/bin/sh", "/bin/sh", "-c", args.c_str(), nullptr);
             // exit grandchild
             _exit(0);
```

And waybar opens just fine ???

**Comment by PaideiaDilemma** [comment]
Shouldn't they be functionally equivalent?

Maybe opening devnull failes??

**Comment by nnyyxxxx** [comment]
i think the issue is that it does not open with an exec-once, not the fact that it doesnt open in general

**Comment by nnyyxxxx** [comment]
could you clarify which way you are talking about? ^^

**Comment by PaideiaDilemma** [comment]
shi* I forgot that I wrapped waybar in uwsm :upside_down_face: 
Ok yeah I can repo and how the f does your patch work xDDD

**Comment by nnyyxxxx** [comment]
skillz

**Comment by PaideiaDilemma** [comment]
is it `_PATH_DEVNULL`?

**Comment by nnyyxxxx** [comment]
nope

**Comment by PaideiaDilemma** [comment]
It's actually the closing of the stdin and stdout that breaks it.
That is pretty weird.

**Comment by PaideiaDilemma** [comment]
But if it works it works I guess. And stdin? Is it best to just leave it pointing to the tty/pts?

**Comment by nnyyxxxx** [comment]
ye

**Review by PaideiaDilemma — APPROVED** [review]

**Review by vaxerski — APPROVED** [review]
I feel alive
