### PR TITLE
fix(groups): deactivate unfocused windows in groups

### LINKED ISSUE #9294: Cannot paste into right kitty instance in same hyprland group
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Not a regression - it's an old bug

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch  at commit 04ac46c54357278fc68f0a95d26347ea0db99496  (version: bump to 0.47.0).
Date: Mon Jan 27 11:43:43 2025
Tag: v0.47.0, commits: 5742
built against:
 aquamarine 0.7.1
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: vbm
Release: 6.6.72-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 Jan 2025 14:04:26 +0000


GPU information: 
c2:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

I had created an issue [Issue in the Kitty repo](https://github.com/kovidgoyal/kitty/issues/8047#issuecomment-2629442427), that occurs when using 2 Kitty instances on Hyprland. The maintainer @kovidgoyal analyzed the logs and concluded that it is bug on Hyperland's side (see his comments).

See @kovidgoyal's comments in the issue for his analysis of the log output.

### How to reproduce

1. Open 2 Kitty instances with **--single-instance**  in a Hyprland session
2. Move both instances into the same hyprland group
3. Copy text from the left Kitty instance. (i.e. from Tab that is in the same group)
4. Pasting text into the right instance causes the text to be pasted into the left instance

Explanation Step 2:
Add something like this to your ~/.config/hypr/hyprland.conf.
```
# ########################## Tabs ############################
# T
bind = ALT, T, togglegroup
# M
bind = Alt, M, moveintogroup, r
# M
bind = Alt SHIFT, code:58, moveoutofgroup
```
* Move both kitty instances into tabbed mode via focusing each instance and for each pressing `ALT+T`
* Select/focus the left kitty instance and move int into the other kitty's group via `ALT+M`

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[HyprlandConfig.txt](https://github.com/user-attachments/files/18633067/HyprlandConfig.txt)

### PR DESCRIPTION
**Pull request by ghost**
fixes #9294 

deactivates unfocused windows in groups, probably improves performance as well

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
can you _not_ add it to XWaylandMgr? I want to get rid of it some day

**Comment by nnyyxxxx** [comment]
where then

**Comment by nnyyxxxx** [comment]
window?

**Comment by nnyyxxxx** [comment]
moved to window

**Comment by nnyyxxxx** [comment]
any other nits, or is this good? @vaxerski

**Comment by vaxerski** [comment]
chill out man

File: src/Compositor.cpp [hunk 1]
```diff
@@ -1189,6 +1189,9 @@ void CCompositor::focusWindow(PHLWINDOW pWindow, SP<CWLSurfaceResource> pSurface
 
     if (*PFOLLOWMOUSE == 0)
         g_pInputManager->sendMotionEventsToFocused();
+
+    if (pWindow->m_sGroupData.pNextWindow.lock())
```
Comment (vaxerski) [inline src/Compositor.cpp:1193]: lock redundant

Comment (nnyyxxxx) [reply src/Compositor.cpp:1193]: right

Comment (nnyyxxxx) [reply src/Compositor.cpp:1193]: we cant remove this?

Comment (nnyyxxxx) [reply src/Compositor.cpp:1193]: or am i missing something

Comment (nnyyxxxx) [reply src/Compositor.cpp:1193]: returns nullptr without lock and group

Comment (nnyyxxxx) [reply src/Compositor.cpp:1193]: [hyprlandCrashReport2845.txt](https://github.com/user-attachments/files/18698362/hyprlandCrashReport2845.txt)

log for reference ( without the lock )

Comment (nnyyxxxx) [reply src/Compositor.cpp]: nvm im dumb xd
