### PR TITLE
[Scroll Wheel] discrete round away from zero + high res scrolling

### LINKED ISSUE #6278: Mouse doesn't scroll the right amount
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a60c7283e677ed81a466d1c0c864c8a05e192cac  (xwayland: verify new xsurf is valid in prop reads).
Date: Wed May 29 09:34:25 2024
Tag: v0.40.0-144-ga60c7283, commits: 4750

flags: (if any)


System Information:
System name: Linux
Node name: kamack38-rogstrixg533qs
Release: 6.9.2-arch1-1.1-g14
Version: #1 SMP PREEMPT_DYNAMIC Mon, 27 May 2024 06:10:00 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] [10de:249c] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux


plugins:

======Config-Start======


Config File: /home/kamack38/.config/hypr/hyprland.conf: Read Succeeded
# #### Monitor
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highrr,auto,1
# monitor=DP-1,disable

# Rotate 90deg
# monitor=DP-1,highrr,auto,1,transform,1

# Enable vrr
# monitor=DP-1,highrr,auto,1,vrr,1

# #### Autostart
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $HOME/.config/hypr/portals.sh
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpaper
exec-once = $HOME/.config/hypr/bar.sh
exec-once = dunst
exec-once = wl-paste --type text --watch cliphist store  # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swayidle -w timeout 300 'lock' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
exec-once = wl-mpris-idle-inhibit

# #### Variables
# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    accel_profile = flat

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(38a3a5ff) rgba(57cc99ff) 0deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
    allow_tearing = false
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    drop_shadow = false
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
    no_gaps_when_only = 2
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
    no_gaps_when_only = 2
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = on
    workspace_swipe_distance = 300
}

misc {
    vfr = no
    disable_hyprland_logo = true
}

# ### Environment variables

# #### Nvidia
# env LIBVA_DRIVER_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
# export WLR_DRM_DEVICES=/dev/dri/card0 # set to card1 to use nvidia

# #### Apps
env = QT_QPA_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland
env = MOZ_ENABLE_WAYLAND,1

# #### Windowrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = workspace 4 silent, class:^(discord)$

# Tile rules
windowrule = tile, neovide
windowrulev2 = tile, class:^(Spotify)$

# Float rules
windowrule = float,org.kde.polkit-kde-authentication-agent-1
windowrulev2 = float,class:^(firefoxdeveloperedition)$,title:^(Picture-in-Picture)$ # Firefox PIP fix
windowrulev2 = float,title:^(Send File — Dolphin)$
windowrulev2 = float,class:^(org.kde.bluedevilsendfile)$

# Btop - system monitor
windowrule = float,system_monitor
windowrule = center,system_monitor
windowrule = animation slide,system_monitor
windowrule = size 1000 760,system_monitor

# Waybar - package update
windowrule = float,package_update
windowrule = center,package_update
windowrule = animation slide,package_update

# Firefox - passwrod prompt
windowrule = float,title:^Password Required
windowrule = stayfocused,title:^Password Required
windowrule = size 400 150,title:^Password Required
windowrule = center,title:^Password Required

# Dolphin - new folder
windowrule = stayfocused,title:^New Folder — Dolphin

# wlogout
windowrule = float,wlogout
windowrule = fullscreen,wlogout
windowrule = noanim,wlogout
windowrule = stayfocused,wlogout

# Rofi
windowrule = float,Rofi
windowrule = center,Rofi
windowrule = animation none,Rofi
windowrule = stayfocused,Rofi

# XWayland video bridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

# #### Layerrules
bezier = easeOut,0.33, 1, 0.68, 1
animation = layers,1,2,easeOut

# Dunst (notifications)
layerrule = animation slide,notifications

# Rofi (app launcher)
layerrule = animation popin,rofi

# ##### Vars
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
$browser = firefox-developer-edition
$private_browser = firefox-developer-edition --private-window
$powermenu = wlogout
$term = kitty
$file_browser = dolphin
$system_monitor = $term --class system_monitor -e btop

# ## Volume
# $raiseVolume = pamixer -i 2
# $lowerVolume = pamixer -d 2
# $muteAudio = pamixer -t
$raiseVolume = volume -i 2
$lowerVolume = volume -d 2
$muteAudio = volume -t

# $toggleMicMute = pactl list sources | grep -oP "Name: \S+" | grep "input" | cut -d' ' -f2 | xargs -I{} pactl set-source-mute {} toggle
$toggleMicMute = microphone -t
$raiseMicVolume = microphone -i 2
$lowerMicVolume = microphone -d 2

# ## Brightness
# $increaseBrightness = brightnessctl set 5%+ -q
# $decreaseBrightness = brightnessctl set 5%- -q
$increaseBrightness = brightness set 5%+ -q
$decreaseBrightness = brightness set 5%- -q

# ##### Binds
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod SHIFT, Q, exit, 
bind = $mainMod, F1, exec, ~/.config/hypr/gamemode.sh
bind = $mainMod SHIFT, Z, exec, toggle_zoom

# ## Apps
bind = $mainMod, grave, exec, $term
bind = $mainMod, E, exec, $file_browser
bind = $mainMod, B, exec, $browser
bind = $mainMod SHIFT, B, exec, $private_browser
bind = $mainMod SHIFT, M, exec, $system_monitor
bind = $mainMod, Escape, exec, $powermenu
bind = ALT, Space, exec, killall rofi || rofi -show drun -no-default-config -config ~/.config/rofi/main.rasi
bind = $mainMod, period, exec, killall rofi || rofi -show emoji -emoji-format "{emoji}" -modi emoji -theme ~/.config/rofi/global/emoji
bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# #### Screenshot
bind = , Print, exec, grimblast --notify --cursor copysave output
$screenshotarea = hyprctl keyword animation "fadeOut,0,0,default"; grimblast --notify copysave area; hyprctl keyword animation "fadeOut,1,4,default"
bind = SUPER SHIFT, S, exec, $screenshotarea

# ## Window state
bind = $mainMod, X, killactive, 
bind = $mainMod, SPACE, togglefloating, 
bind = $mainMod, F, fullscreen, 0 
bind = $mainMod, M, fullscreen, 1 
bind = $mainMod, T, pin,
bind = $mainMod, P, pseudo, # dwindle
# bind = $mainMod, J, togglesplit, # dwindle

# ## Cycling through windows
bind = ALT, TAB, cyclenext,
bind = ALT SHIFT, TAB, cyclenext, prev

# ## Moving window
bind = $mainMod MOD5, H, movewindow, l # MOD5 is actually right ALT
bind = $mainMod MOD5, left, movewindow, l
bind = $mainMod MOD5, J, movewindow, d 
bind = $mainMod MOD5, down, movewindow, d 
bind = $mainMod MOD5, K, movewindow, u 
bind = $mainMod MOD5, up, movewindow, u 
bind = $mainMod MOD5, L, movewindow, r 
bind = $mainMod MOD5, right, movewindow, r 

# ## Moving window through monitors
bind = $mainMod SHIFT, H, movewindow, mon:-1 
bind = $mainMod SHIFT, L, movewindow, mon:+1 
bind = $mainMod SHIFT, left, movewindow, mon:-1 
bind = $mainMod SHIFT, rifght, movewindow, mon:+1 

# ## Focus
bind = $mainMod, Tab, cyclenext,
bind = $mainMod, left, movefocus, l
bind = $mainMod, H, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, L, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, K, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, J, movefocus, d

# ## Focusing monitors
bind = $mainMod SHIFT, K, focusmonitor, +1
bind = $mainMod SHIFT, J, focusmonitor, -1

# ## Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# ## Moving window throughout workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# ## Cycling through workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, TAB, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod SHIFT, TAB, workspace, e-1

# ## Resizing window
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# ## Window groups
bind = $mainMod, G, togglegroup 
bind = $mainMod, N, changegroupactive, f
bind = $mainMod SHIFT, N, changegroupactive, b
bind = $mainMod SHIFT, Escape, moveoutofgroup

# ## Brightness control
binde = , XF86MonBrightnessUp, exec, $increaseBrightness
binde = , XF86MonBrightnessDown, exec, $decreaseBrightness

# ## Audio keybindings
bind = , XF86AudioPlay, exec, playerctl play-pause && mpris-noti
bind = , XF86AudioPause, exec, playerctl pause && mpris-noti
bind = , XF86AudioStop, exec, playerctl stop && mpris-noti

bind = SHIFT, XF86AudioPlay, exec, mpris-noti # Show currently playing song

bind = , XF86AudioNext, exec, playerctl next && mpris-noti
bind = , XF86AudioPrev, exec, playerctl previous && mpris-noti

binde = SHIFT, XF86AudioNext, exec, playerctl position 5+ && mpris-noti
binde = SHIFT, XF86AudioPrev, exec, playerctl position 5- && mpris-noti

bind = , XF86AudioMute, exec, $muteAudio
binde = , XF86AudioRaiseVolume, exec, $raiseVolume
binde = , XF86AudioLowerVolume, exec, $lowerVolume

binde = SHIFT, XF86AudioRaiseVolume, exec, playerctl volume 0.02+ && mpris-noti
binde = SHIFT, XF86AudioLowerVolume, exec, playerctl volume 0.02- && mpris-noti

# ## Microphone
binde = CTRL, XF86AudioRaiseVolume, exec, $raiseMicVolume
binde = CTRL, XF86AudioLowerVolume, exec, $lowerMicVolume
bind = , XF86AudioMicMute, exec, $toggleMicMute # Toggle mute on all
bind = SHIFT, XF86AudioMicMute, exec, pactl list sources | grep -oP "Name: \S+" | grep "input" | cut -d' ' -f2 | xargs -I{} pactl set-source-mute {} false # Unmute all

# ## Launch keybindings
bind = , XF86Launch4, exec, asusctl profile -n && notify-send "$(asusctl profile -p)" -r 68

======Config-End========
```

</details>

### Bug or Regression?

Regression

### Description

I've noticed that the mouse scroll doesn't scroll the right amount or doesn't work at all. For example scrolling on the waybar changes the volume by 8-10 instead of 2. Additionally, scrolling in kitty doesn't work (scrolls two or three lines and then stops) and in pagers in it.

### How to reproduce

I noticed that scrolling by one produces this in wev:
```
[04:         wl_seat] name: Hyprland
[04:         wl_seat] capabilities: pointer keyboard 
[10:    xdg_toplevel] configure: width: 1280; height: 1404
                      tiled-left tiled-right tiled-top tiled-bottom 
[09:     xdg_surface] configure: serial: 114
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 66475
[14:     wl_keyboard] repeat_info: rate: 25 keys/sec; delay: 600 ms
[10:    xdg_toplevel] configure: width: 1280; height: 1404
                      tiled-left tiled-right tiled-top tiled-bottom maximized 
[10:    xdg_toplevel] configure: width: 1265; height: 1384
                      tiled-left tiled-right tiled-top tiled-bottom maximized 
[14:     wl_keyboard] enter: serial: 118; surface: 3
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[11:  wl_data_device] selection: (cleared)
[10:    xdg_toplevel] configure: width: 1265; height: 1384
                      tiled-left tiled-right tiled-top tiled-bottom maximized activated 
[10:    xdg_toplevel] configure: width: 1261; height: 1380
                      tiled-left tiled-right tiled-top tiled-bottom maximized activated 
[13:      wl_pointer] enter: serial: 121; surface: 3, x, y: 1134.000000, 742.000000
[13:      wl_pointer] frame
[09:     xdg_surface] configure: serial: 115
[14:     wl_keyboard] key: serial: 122; time: 713344; key: 36; state: 0 (released)
                      sym: Return       (65293), utf8: ''
[13:      wl_pointer] axis: time: 716798; axis: 0 (vertical), value: 7.500000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 1
[13:      wl_pointer] frame
[13:      wl_pointer] axis: time: 716804; axis: 0 (vertical), value: 1.875000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 0
[13:      wl_pointer] frame
[13:      wl_pointer] axis: time: 716807; axis: 0 (vertical), value: 1.875000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 0
[13:      wl_pointer] frame
[13:      wl_pointer] axis: time: 716811; axis: 0 (vertical), value: 1.875000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 0
[13:      wl_pointer] frame
[13:      wl_pointer] axis: time: 716814; axis: 0 (vertical), value: 1.875000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 0
[13:      wl_pointer] frame
[13:      wl_pointer] axis: time: 716820; axis: 0 (vertical), value: 1.875000
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 0
[13:      wl_pointer] frame
```

Everything works on v0.40. Here's the output of doing the same thing:
```
[08:         wl_seat] name: seat0
[08:         wl_seat] capabilities: pointer keyboard 
[10:    xdg_toplevel] configure: width: 1280; height: 1404
[09:     xdg_surface] configure: serial: 140
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 66475
[14:     wl_keyboard] repeat_info: rate: 25 keys/sec; delay: 600 ms
[14:     wl_keyboard] enter: serial: 144; surface: 3
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[11:  wl_data_device] selection: (cleared)
[13:      wl_pointer] enter: serial: 147; surface: 3, x, y: 1155.000000, 436.000000
[13:      wl_pointer] frame
[10:    xdg_toplevel] configure: width: 1261; height: 1380
                      maximized activated tiled-left tiled-right tiled-top tiled-bottom 
[09:     xdg_surface] configure: serial: 141
[14:     wl_keyboard] key: serial: 148; time: 816931; key: 36; state: 0 (released)
                      sym: Return       (65293), utf8: ''
[13:      wl_pointer] frame
[13:      wl_pointer] frame
[13:      wl_pointer] frame
[13:      wl_pointer] frame
[13:      wl_pointer] axis_source: 0 (wheel)
[13:      wl_pointer] axis_stop: axis: 0 (vertical), discrete: 1
[13:      wl_pointer] axis: time: 818486; axis: 0 (vertical), value: 15.000000
[13:      wl_pointer] frame
```

### Crash reports, logs, images, videos

_No response_

### LINKED ISSUE #6299: Scroll wheel only triggers once in wayland apps(and kitty for unknown reasons)
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a54ab301602e205f273969c093cf494d38ba4a98 dirty (cmake: make xcb-errors required).
Date: Sat Jun 1 04:07:00 2024
Tag: v0.40.0-146-ga54ab301, commits: 4752

flags: (if any)


System Information:
System name: Linux
Node name: CielPC
Release: 6.9.2-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:09 +0000


GPU information: 
0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/ciel/.config/hypr/hyprland.conf: Read Succeeded
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
# monitor=DP-2,3840x2160@143.988,0x0,1
monitor=DP-1,3840x2160@144Hz,0x0,1,bitdepth,10
monitor=DP-2,1920x1080@144Hz,3840x0,1,transform,3
monitor=,preferred,auto,1

workspace = DP-1,1
workspace = DP-2,2

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# Status bar
exec = killall waybar;waybar
# Wallpaper
exec-once = hyprpaper

# exec-once=/home/ciel/portals.sh
exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user import-environment QT_QPA_PLATFORMTHEME

# Browser
exec-once = [workspace 2; noanim] firefox
# Notification Daemon
# exec-once = mako
exec-once = swaync
# Authentication agent
exec-once=/usr/lib/polkit-kde-authentication-agent-1
# Password manager
exec-once=1password --silent
# Sync files
exec-once=syncthing --no-browser
# Airplay keepalive fix
# exec-once=~/airplay_fix.fish
# Discord in special workspace
# exec-once=[workspace special silent] discord-ptb
exec-once=[workspace special silent] discord --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime 
exec-once=$(ls ~/Applications/Cider*.AppImage)

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24
# env = HYPRCURSOR_THEME,capitaine-cursors
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
#env = SDL_VIDEODRIVER,wayland,x11
env = CLUTTER_BACKEND,wayland

# env = XDG_CURRENT_DESKTOP,Hyprland
# Technically incorrect, but dark mode is fucked in kde apps without this so
env = XDG_CURRENT_DESKTOP,kde
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = MOZ_ENABLE_WAYLAND,1

env = QT_IM_MODULE=fcitx
env = XMODIFIERS=@im=fcitx
# env = GTK_IM_MODULE,wayland
# env = GTK_IM_MODULE,fcitx
env = SDL_IM_MODULE,fcitx

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    #follow_mouse = 0

    touchpad {
        natural_scroll = false
    }

    numlock_by_default = true

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    tablet {
        output = DP-1
    }
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 1
    #col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border = rgba(33ccffee)
    #col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)

    #no_cursor_warps = true

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = on
    }

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = true
    # enabled = false

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = no # you probably want this
    # special_scale_factor = 0.8
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    #focus_on_activate = true
    #force_hypr_chan = true
    disable_splash_rendering = true
}

debug {
    disable_logs = false
}


# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = tile,class:neovide
windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1
windowrulev2 = noblur,class:^8dpLpcU3aynKff
windowrulev2 = noborder,class:^8dpLpcU3aynKff
windowrulev2 = float,class:^8dpLpcU3aynKff

windowrulev2 = workspace special silent,class:discord
windowrulev2 = workspace special silent,class:Cider

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# bind = $mainMod SHIFT, n, exec, swaync-client -t

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# bind = $mainMod, ENTER, exec, kitty
bind = $mainMod SHIFT, Q, killactive, 
bind = $mainMod SHIFT, M, exit, 
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, BACKSLASH, exec, firefox
bind = $mainMod, T, exec, neovide 
#bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating, 
# bind = $mainMod, D, exec, anyrun
bind = $mainMod, D, exec, pgrep anyrun && pkill anyrun || anyrun
windowrulev2 = forceinput,class:jetbrains-studio
# windowrulev2 = forceinput,class:^(krunner)$
#windowrulev2 = center,class:^(krunner)$
#bind = $mainMod, D, exec, qdbus org.kde.krunner /App display && hyprctl dispatch focuswindow krunner
#exec-once = 
#bind = $mainMod, D, exec, qdbus org.kde.krunner / && krunner && hyprctl dispatch focuswindow krunner
windowrulev2 = stayfocused, class:^(krunner)$

bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, togglesplit, # dwindle

# Move focus with mainMod + hjkl
bind = $mainMod, h, movefocus, l
bind = $mainMod, n, movefocus, d
bind = $mainMod, e, movefocus, u
bind = $mainMod, i, movefocus, r

# Move window with mainmod + shift + hjkl
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, n, movewindow, d
bind = $mainMod SHIFT, e, movewindow, u
bind = $mainMod SHIFT, i, movewindow, r
binde=$mainMod CTRL SHIFT,h,resizeactive,-10 0
binde=$mainMod CTRL SHIFT,n,resizeactive,0 10
binde=$mainMod CTRL SHIFT,e,resizeactive,0 -10
binde=$mainMod CTRL SHIFT,i,resizeactive,10 0

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Fullscreen
bind=$mainMod,F,fullscreen

# Scroll through existing workspaces with mainMod + scroll
# bind = $mainMod, mouse_down, workspace, e+1
# bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
# bindm = $mainMod, mouse:272, movewindow
# bindm = $mainMod, mouse:273, resizewindow

# Volume control
$WOBSOCK = $XDG_RUNTIME_DIR/wob.sock
exec-once = rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob

bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+ && pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}'  $WOBSOCK
bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%- && pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > $WOBSOCK
bind = ,XF86AudioMute, exec, wpctl set-volume @DEFAULT_SINK@ 0%
bind = ,XF86AudioPlay, exec, playerctl play-pause

# Screenshot
bind = $mainMod SHIFT, p, exec, grim -g "$(slurp -d)" - | wl-copy

# Input method
exec = fcitx5 -d --replace
# bindl = $mainMod, Space, pass, fcitx5

# Special workspace
workspace=special:special,gapsout:100

bind=$mainMod CTRL,SPACE,movetoworkspace,e+0
bind=$mainMod SHIFT,MINUS,movetoworkspace,special
bind=$mainMod ,MINUS,togglespecialworkspace,

# Keybind passthough
# bind=CTRL SHIFT,SPACE,pass,^1password$

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# cursor {
#     no_hardware_cursors = true
# }

======Config-End========
```

</details>

### Bug or Regression?

Regression? Bug? Idk actually

### Description

In Xwayland apps, when you continuously scroll down, it only happens once, it will only scroll once again if you stop scrolling and start scrolling.

It's almost as if it's scrolling on the derivative, except moving to neutral doesn't trigger one in the reverse direction.

It is also noted that Kitty, despite being a wayland app, still exhibits the same behavior, but until more recently, to a lesser extent, it went

Normal scrolling -> xwayland app broken + kitty scrolls very slowly(1 line per scroll compared to ~5 when it was normal) -> now both broken

### How to reproduce

Scroll in steam/Krita

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by Agent00Ming**
#### Describe your PR, what does it fix/add?
Fixes #6278 and fixes #6299

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Fixed an unnoticed bug where setting `input:scroll_factor` too low would cause discrete axis events to round to zero.  

#### Is it ready for merging, or does it need work?
Ready for merging but could use some more testing.

### CODE REVIEW

**Comment by darkiox** [comment]
Scrolling now works without issues using wireless mouse, can confirm that sensitivity is way too high hahah. Here are some logs, if they are useful for anything.

Thanks @Agent00Ming !!!
[hyprland_wev_scroll.log](https://github.com/user-attachments/files/15526985/hyprland_wev_scroll.log)

**Comment by Ciel-MC** [comment]
Works in Kitty, way too high, testing  xwayland now

**Comment by Agent00Ming** [comment]
I think there's a better approach but this works as a band-aid fix for now. Applications have their own interpretation of discrete scrolling... the higher frequency of discrete scroll events works great in Firefox but not for terminal emulators and other apps...

**Comment by Agent00Ming** [comment]
@darkiox @Ciel-MC have a look at it now, it should be in a much better shape now. Blender still zooms in/out with crazy high sens because is doesn't support high resolution scrolling but kitty's scrolling seems much more reasonable now.

**Comment by Agent00Ming** [comment]
note that this should not affect low resolution scrolling (most common wired mice) with the exception of fixing an unnoticed bug where putting your `input:scroll_factor` too low would cause discrete scroll events to be rounded down to 0.

**Comment by darkiox** [comment]
Just tested, still feels a bit fast for my liking.
Tried changing `input:scroll_factor` and it did work on Wayland apps, but XWayland apps don't change the scroll speed. (Is that intended? Don't know for sure)

**Comment by Agent00Ming** [comment]
I'm afraid there isn't much we can do about xwayland clients, they take the scroll events at face value or something to that effect and don't support the wayland high resolution scrolling signals.

**Comment by darkiox** [comment]
> I'm afraid there isn't much we can do about xwayland clients, they take the scroll events at face value or something to that effect and don't support the wayland high resolution scrolling signals.

Yeah I guess so, that's why there is worlds of difference between applications. Firefox for example works great (launched on X just to test) but kitty still flies lmao. Tried on Minecraft too (games running on Xwayland also suffer from this), and noticed it scrolls 6 steps each scroll of the wheel.
This is good enough for me to be honest, if you need more testing just lmk.

File: src/layout/IHyprLayout.cpp [hunk 1]
```diff
@@ -147,7 +147,7 @@ void IHyprLayout::onWindowCreatedFloating(PHLWINDOW pWindow) {
                 pWindow->m_vRealPosition = pWindow->m_pXDGSurface->toplevel->parent->window->m_vRealPosition.goal() +
                     pWindow->m_pXDGSurface->toplevel->parent->window->m_vRealSize.goal() / 2.F - desiredGeometry.size() / 2.F;
             else
-                pWindow->m_vRealPosition = PMONITOR->vecPosition + desiredGeometry.size() / 2.F;
+                pWindow->m_vRealPosition = PMONITOR->vecPosition + PMONITOR->vecSize / 2.F - desiredGeometry.size() / 2.F;
```
Comment (vaxerski) [inline src/layout/IHyprLayout.cpp:150]: unintentional? rebase on main plox

**Review by vaxerski — APPROVED** [review]
lgtm thanks!

**Comment by Sewer56** [comment]
The scroll speed in xwayland applications certainly is a hassle though.

There's a good number of applications (unfortunately proprietary) that are stuck in this state on my end, and not being able to scale it really is far from ideal.

Anyway, I managed to run into here while wondering what might have changed to make these apps scroll so fast.

**Comment by tecknogyk** [comment]
Yeah, this is just unusable for me.  Discord, Easy Effects, Nautilus, and Dolphin all scroll way too fast.  Unless something changes Hyprland is just not something I can use anymore.  Everything was fine before I updated.

**Comment by Ciel-MC** [comment]
> Yeah, this is just unusable for me. Discord, Easy Effects, Nautilus, and Dolphin all scroll way too fast. Unless something changes Hyprland is just not something I can use anymore. Everything was fine before I updated.

All expect easy effects for me has Wayland support for which the scrolling is not broken, it’s currently only ruined on xwayland apps, try to make them launch under wayland
