### PR TITLE
window: move size reporting to animation begin callback

### LINKED ISSUE #9256: some xwayland windows open not scaled until input is received
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch main at commit ef03f6911694413b1b06aba727ad9ab089a511f7  (xwayland: handle window coords correctly (9238)).
Date: Thu Jan 30 16:36:42 2025
Tag: v0.47.0-21-gef03f691, commits: 5763
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: iwuvyou
Release: 6.12.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 18 Jan 2025 02:26:57 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
0f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Some xwayland windows open not scaled until input is received causing them to look malformed.

### How to reproduce

I've encountered this issue with file pickers, open a file picker repeatedly until its deformed

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[sysinformation.txt](https://github.com/user-attachments/files/18615528/sysinformation.txt)

### LINKED ISSUE #9279: Moving fullscreened workspaces between (differently scaled) monitors
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.1 built from branch  at commit 75dff7205f6d2bd437abfb4196f700abee92581a  (version: bump to 0.47.1).
Date: Wed Jan 29 23:19:39 2025
Tag: v0.47.1, commits: 5756
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: archlinux
Release: 6.6.72-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 Jan 2025 14:04:26 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix4 [1002:1901] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Description

(I'm trying to see if I can git bisect rn, I'll update when I finish)
Moving a fullscreen window/workspace between monitors that have a different scale does not resize the window (afaict it seems to keep the same effective pixel size)

If moving from a higher scaling to a lower one, only the top left bit of the monitor is filled with the window, the rest is wallpapered.
If moving the other way around it becomes impossible to interact with the lower and right section of the window.

Unfullscreening and refullscreening fixes the issue.

### How to reproduce

1. Set up two monitors side by side, one scaled, for example at 1.2, the other at 1 (I don't think the exact ratio matters)
2. fullscreen a window
3. move the workspace with that window to the other monitor

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [x] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland_config_dump.txt](https://github.com/user-attachments/files/18629557/hyprland_config_dump.txt)

video is hard to capture as multi-monitor, so here's just an image of a high-to-low scaling move:

Image

[hyprland.log](https://github.com/user-attachments/files/18629575/hyprland.log)

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
#### Describe your PR, what does it fix/add?

Made so many mistakes in the animation PR...
I removed this from `tick` when playing around with damage:
```cpp
// set size and pos if valid, but only if damage policy entire (dont if border for example)
if (validMapped(PWINDOW) && av->m_eDamagePolicy == AVARDAMAGE_ENTIRE && !PWINDOW->isX11OverrideRedirect())
    g_pXWaylandManager->setWindowSize(PWINDOW, PWINDOW->m_vRealSize.goal());

```
Had the intention to move that to a update callback for the window size, except - well - I didn't.
Worst thing about this is that some xwayland changes probably were only made because this was missing. Sorry for that.
I will go though other size/position related changes since and check if they are redundant tomorrow.

Closes https://github.com/hyprwm/Hyprland/issues/9269
Closes https://github.com/hyprwm/Hyprland/issues/9256
Closes #9279

~~CC @nnyyxxxx wanna verify that it fixes #9256?~~ :heavy_check_mark: 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

atlauncher import window still works ^^

#### Is it ready for merging, or does it need work?

Ready.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
sure

**Comment by nnyyxxxx** [comment]
fixed both issues but has minor visual glitches

**Comment by PaideiaDilemma** [comment]
wanna post a vid of the gitches?

**Comment by nnyyxxxx** [comment]
just disregard that, most instant window resizing in hyprland does have visual glitches.

For instance have a browser open alone (very sad) in one workspace and then open a terminal. The browser will have weird behaviour when adjusting. this is probably normal

File: src/desktop/Window.cpp [hunk 1]
```diff
@@ -559,6 +559,11 @@ void CWindow::onMap() {
         *m_fBorderAngleAnimationProgress = 1.f;
     }
 
+    m_vRealSize->setUpdateCallback([this](auto) {
+        if (validMapped(m_pSelf) && m_bIsFloating)
+            sendWindowSize();
+    });
```
Comment (PaideiaDilemma) [inline src/desktop/Window.cpp:565]: This is the relevant part.

Comment (PaideiaDilemma) [reply src/desktop/Window.cpp:565]: This is to mimic the snipped I posted in the description.
But now I am thinking using a callback on animation begin would be enough. Going to try that.

Comment (PaideiaDilemma) [reply src/desktop/Window.cpp:565]: It does seem slightly smoother with a update callback. Begin callback might be too early in some cases is my guess (when setting size twice for example, update will only be called during tick, but begin right away)

**Comment by nnyyxxxx** [comment]
what happened?

**Comment by PaideiaDilemma** [comment]
I am trying out jujutsu and pushed the wrong bookmark after a rebase. Leaving my main to be in sync with Hyprland main and that seems to autoclose a PR ^^

File: src/desktop/Window.cpp [hunk 2]
```diff
@@ -561,6 +561,19 @@ void CWindow::onMap() {
...
+    m_vRealSize->setCallbackOnBegin(
+        [this](auto) {
+            m_vRealSize->setUpdateCallback([this](auto) {
+                if (m_bIsMapped && m_bIsFloating)
+                    sendWindowSize();
+
+                m_vRealSize->setUpdateCallback(nullptr);
+            });
+        },
+        false);
```
Comment (nnyyxxxx) [inline src/desktop/Window.cpp:575]: holy fuck...

Comment (PaideiaDilemma) [reply src/desktop/Window.cpp]: xD I removed that again

File: src/desktop/Window.cpp (hunk 1 above)
Comment (PaideiaDilemma) [reply src/desktop/Window.cpp]: Opted for begin callback again. Looking at the UV stretches too much might have made me hallucinate that it's different. I think it's the same.
But honestly having this trigger only for floating size updates only is kinda weird.
So I am suggesting we either sendWindowSize via the animation begin callback for all size updates,
or we add sendWindowSize in the places that are now missing e.g. when updating floating size.

**Review by nnyyxxxx — APPROVED** [review]

**Comment by nnyyxxxx** [comment]
this is finished right?

**Comment by PaideiaDilemma** [comment]
Ok so in the latest commit i moved most of the sendWindowSize calls to the animation begin update. (Also gets called when animations are disabled)

I think that makes sense because
- the animation begin corresponds to actual visual size changes
- it is easier to maintain

Caveats:
- setValueAndWarp does NOT trigger the animation begin cb. If size updates should still be sent, call it afterwards (like on window drag resizes without animations)
- position updates don't use the same mechanism, but sendWindowSize configures x11 windows with position and size. would be nice to decouple it like the TODO mentions, but idk where and how we want to configure the x11 surface in that case.

sendWindowSize is still manually called in the following places:
- layout/IHyprLayout.cpp in `onMouseMove`
- events/Windows.cpp in `listener_unmanagedSetGeometry`
- Compositor.cpp in `setWindowFullscreenState` with `force = true`
- managersXwaylandManager.cpp in `activateWindow` with `force = true`
- desktop/Window.cpp in `onX11Configure` when dragging with `force=true`
- desktop/Workspace.cpp in `forceResportSizesToWindows` with `force=true`

File: src/events/Windows.cpp [hunk 3]
```diff
@@ -986,6 +979,7 @@ void Events::listener_unmanagedSetGeometry(void* owner, void* data) {
 
         PWINDOW->m_vPosition = PWINDOW->m_vRealPosition->goal();
         PWINDOW->m_vSize     = PWINDOW->m_vRealSize->goal();
+        PWINDOW->sendWindowSize();
```
Comment (nnyyxxxx) [inline src/events/Windows.cpp:982]: race condition?

File: src/desktop/Window.cpp [hunk 4]
```diff
@@ -1695,15 +1698,16 @@ Vector2D CWindow::requestedMaxSize() {
...
 }
 
-void CWindow::sendWindowSize(Vector2D size, bool force, std::optional<Vector2D> overridePos) {
+void CWindow::sendWindowSize(bool force) {
     static auto PXWLFORCESCALEZERO = CConfigValue<Hyprlang::INT>("xwayland:force_zero_scaling");
     const auto  PMONITOR           = m_pMonitor.lock();
 
-    size = size.clamp(Vector2D{1, 1}, Vector2D{std::numeric_limits<double>::infinity(), std::numeric_limits<double>::infinity()});
+    Debug::log(TRACE, "sendWindowSize: window:{:x},title:{} with real pos {}, real size {} (force: {})", (uintptr_t)this, this->m_szTitle, m_vRealPosition->goal(),
+               m_vRealSize->goal(), force);
```
Comment (nnyyxxxx) [inline src/desktop/Window.cpp:1706]: would it be a problem if:

an animation is in progress
and
a size update is sent

Comment (PaideiaDilemma) [reply src/desktop/Window.cpp:1706]: No I don't think so? since the size we send is always the goal size of the animation.

Comment (nnyyxxxx) [reply src/desktop/Window.cpp:1706]: okay

**Review by nnyyxxxx — APPROVED** [review]

**Review by vaxerski — APPROVED** [review]
39
