### PR TITLE
fix: ioctl use /dev/tty instead of fd 0 for VT_GETSTATE

### LINKED ISSUE #2460: If started with GDM, pressing ctrl-alt-f<vt number of Hyprland> will freeze Hyprland.
## Steps to reproduce

1. Launch Hyprland session from GDM.
2. Get current vt number with `fgconsole`, e.g. 3
3. press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>f3<kbd>
4. Hyprland freezes

## Notes

Cannot be reproduced in `sway` and `gnome-shell`.
Can be reproduced in a virtual machine using `virgl`.

### PR DESCRIPTION
**Pull request by memchr**
ioctl VT_GETSTATE on stdin fails if it is not console, such as when using GDM.  `/dev/tty` should be used instead.

- `/dev/tty` is a synonym for the controlling terminal of a process, if there is one.

---

Fixes #2460

### CODE REVIEW

**Comment by vaxerski** [comment]
@jbeich for bsd

File: src/managers/KeybindManager.cpp [hunk 1]
```diff
@@ -519,9 +520,13 @@ bool CKeybindManager::handleVT(xkb_keysym_t keysym) {
         // vtnr is bugged for some reason.
         unsigned int ttynum = 0;
 #if defined(VT_GETSTATE)
+        int            fd;
         struct vt_stat st;
-        if (!ioctl(0, VT_GETSTATE, &st))
-            ttynum = st.v_active;
+        if ((fd = open("/dev/tty", O_RDONLY | O_NOCTTY)) >= 0) {
```
Comment (jbeich) [inline src/managers/KeybindManager.cpp:525]: Can you apply to both `VT_GETSTATE` and `VT_GETACTIVE`?

<details><summary>example diff</summary>

```diff
diff --git a/src/managers/KeybindManager.cpp b/src/managers/KeybindManager.cpp
index d676001cd841..2a44137e74f8 100644
--- a/src/managers/KeybindManager.cpp
+++ b/src/managers/KeybindManager.cpp
@@ -519,19 +519,19 @@ bool CKeybindManager::handleVT(xkb_keysym_t keysym) {
 
         // vtnr is bugged for some reason.
         unsigned int ttynum = 0;
-#if defined(VT_GETSTATE)
-        int            fd;
-        struct vt_stat st;
+        int          fd;
         if ((fd = open("/dev/tty", O_RDONLY | O_NOCTTY)) >= 0) {
+#if defined(VT_GETSTATE)
+            struct vt_stat st;
             if (!ioctl(fd, VT_GETSTATE, &st))
                 ttynum = st.v_active;
-            close(fd);
-        }
 #elif defined(VT_GETACTIVE)
-        int vt;
-        if (!ioctl(0, VT_GETACTIVE, &vt))
-            ttynum = vt;
+            int vt;
+            if (!ioctl(fd, VT_GETACTIVE, &vt))
+                ttynum = vt;
 #endif
+            close(fd);
+        }
 
         if (ttynum == TTY)
             return true;
```
</details>

**Review by jbeich — CHANGES_REQUESTED** [review]
Inconsistent: `VT_GETSTATE` (Linux, NetBSD, OpenBSD) vs. `VT_GETACTIVE` (DragonFly, FreeBSD). I've tested a modifed version of this on FreeBSD, and it works fine.

File: src/managers/KeybindManager.cpp (hunk 1 above)
Comment (memchr) [reply src/managers/KeybindManager.cpp:523]: done.

File: src/managers/KeybindManager.cpp [hunk 2]
```diff
@@ -519,19 +519,19 @@ bool CKeybindManager::handleVT(xkb_keysym_t keysym) {
...
             if (!ioctl(fd, VT_GETSTATE, &st))
                 ttynum = st.v_active;
-            close(fd);
-        }
 #elif defined(VT_GETACTIVE)
-        int vt;
-        if (!ioctl(0, VT_GETACTIVE, &vt))
-            ttynum = vt;
+            int vt;
+            if (!ioctl(0, VT_GETACTIVE, &vt))
```
Comment (jbeich) [inline src/managers/KeybindManager.cpp:530]: Missed `0` -> `fd`:
```suggestion
            if (!ioctl(fd, VT_GETACTIVE, &vt))
```

**Review by jbeich — APPROVED** [review]

**Review by vaxerski — APPROVED** [review]
top g
