### PR TITLE
Set preferred scale on monitor config reload

### LINKED ISSUE #4363: Hyprland does not resend wp_fractional_scale_v1 preferred scale events
### Hyprland Version

```sh
Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).
Tag: v0.33.1

flags: (if any)
debug

```

### Bug or Regression?

Bug

### Description

This causes a bug in alacritty and in Qt applications in which the font becomes blurry when scale is changed, because when the scale is changed Hyprland is not sending a new event to change the scale factor, requiring these applications to open new windows to render properly.
https://github.com/alacritty/alacritty/issues/7572#issuecomment-1879556143

The following is the output of Alacritty, during which I changed the scale from 1 to 1.25. Alacritty only received a single event of preferred scale 120 (1.0) and never received the new scale.
```
➜  ~ WAYLAND_DEBUG=1 alacritty --print-events
[ 930207.653]  -> wl_display@1.get_registry(new id wl_registry@2)
[ 930207.686]  -> wl_display@1.sync(new id wl_callback@3)
[ 930207.920] wl_display@1.delete_id(3)
[ 930207.947] wl_registry@2.global(1, "wl_shm", 1)
[ 930207.962] wl_registry@2.global(2, "wl_drm", 2)
[ 930207.967] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 4)
[ 930207.973] wl_registry@2.global(4, "wl_compositor", 6)
[ 930207.978] wl_registry@2.global(5, "wl_subcompositor", 1)
[ 930207.984] wl_registry@2.global(6, "wl_data_device_manager", 3)
[ 930207.992] wl_registry@2.global(7, "zwlr_export_dmabuf_manager_v1", 1)
[ 930207.998] wl_registry@2.global(8, "zwlr_data_control_manager_v1", 2)
[ 930208.004] wl_registry@2.global(9, "zwp_primary_selection_device_manager_v1", 1)
[ 930208.011] wl_registry@2.global(10, "wp_viewporter", 1)
[ 930208.019] wl_registry@2.global(11, "zwlr_gamma_control_manager_v1", 1)
[ 930208.031] wl_registry@2.global(12, "zwlr_output_power_manager_v1", 1)
[ 930208.042] wl_registry@2.global(13, "xdg_wm_base", 5)
[ 930208.053] wl_registry@2.global(14, "wl_seat", 8)
[ 930208.065] wl_registry@2.global(15, "wp_presentation", 1)
[ 930208.071] wl_registry@2.global(16, "ext_idle_notifier_v1", 1)
[ 930208.080] wl_registry@2.global(17, "zwlr_layer_shell_v1", 4)
[ 930208.091] wl_registry@2.global(18, "org_kde_kwin_server_decoration_manager", 1)
[ 930208.102] wl_registry@2.global(19, "zxdg_decoration_manager_v1", 1)
[ 930208.111] wl_registry@2.global(20, "zwlr_output_manager_v1", 4)
[ 930208.123] wl_registry@2.global(21, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 930208.133] wl_registry@2.global(22, "zwp_pointer_constraints_v1", 1)
[ 930208.143] wl_registry@2.global(23, "zwp_relative_pointer_manager_v1", 1)
[ 930208.153] wl_registry@2.global(24, "zwp_virtual_keyboard_manager_v1", 1)
[ 930208.163] wl_registry@2.global(25, "zwlr_virtual_pointer_manager_v1", 2)
[ 930208.175] wl_registry@2.global(26, "zwlr_foreign_toplevel_manager_v1", 3)
[ 930208.186] wl_registry@2.global(27, "wp_drm_lease_device_v1", 1)
[ 930208.196] wl_registry@2.global(28, "zwp_tablet_manager_v2", 1)
[ 930208.206] wl_registry@2.global(29, "zwp_idle_inhibit_manager_v1", 1)
[ 930208.214] wl_registry@2.global(30, "zxdg_exporter_v1", 1)
[ 930208.221] wl_registry@2.global(31, "zxdg_importer_v1", 1)
[ 930208.231] wl_registry@2.global(32, "zxdg_exporter_v2", 1)
[ 930208.241] wl_registry@2.global(33, "zxdg_importer_v2", 1)
[ 930208.253] wl_registry@2.global(34, "zwp_pointer_gestures_v1", 3)
[ 930208.264] wl_registry@2.global(35, "zwp_text_input_manager_v3", 1)
[ 930208.275] wl_registry@2.global(36, "zwp_input_method_manager_v2", 1)
[ 930208.286] wl_registry@2.global(37, "xdg_activation_v1", 1)
[ 930208.297] wl_registry@2.global(38, "ext_session_lock_manager_v1", 1)
[ 930208.308] wl_registry@2.global(39, "wp_cursor_shape_manager_v1", 1)
[ 930208.318] wl_registry@2.global(40, "wp_tearing_control_manager_v1", 1)
[ 930208.330] wl_registry@2.global(41, "wp_single_pixel_buffer_manager_v1", 1)
[ 930208.341] wl_registry@2.global(42, "xwayland_shell_v1", 1)
[ 930208.352] wl_registry@2.global(43, "hyprland_toplevel_export_manager_v1", 2)
[ 930208.363] wl_registry@2.global(44, "wp_fractional_scale_manager_v1", 1)
[ 930208.374] wl_registry@2.global(45, "zwp_text_input_manager_v1", 1)
[ 930208.386] wl_registry@2.global(46, "hyprland_global_shortcuts_manager_v1", 1)
[ 930208.396] wl_registry@2.global(47, "zwlr_screencopy_manager_v1", 3)
[ 930208.408] wl_registry@2.global(48, "zxdg_output_manager_v1", 3)
[ 930208.419] wl_registry@2.global(49, "wl_output", 4)
[ 930208.430] wl_callback@3.done(21471)
[ 930208.543]  -> wl_registry@2.bind(4, "wl_compositor", 6, new id [unknown]@3)
[ 930208.565]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@4)
[ 930208.586]  -> wl_registry@2.bind(49, "wl_output", 4, new id [unknown]@5)
[ 930208.613]  -> wl_registry@2.bind(48, "zxdg_output_manager_v1", 3, new id [unknown]@6)
[ 930208.642]  -> zxdg_output_manager_v1@6.get_xdg_output(new id zxdg_output_v1@7, wl_output@5)
[ 930208.669]  -> wl_registry@2.bind(14, "wl_seat", 7, new id [unknown]@8)
[ 930208.714]  -> wl_registry@2.bind(44, "wp_fractional_scale_manager_v1", 1, new id [unknown]@9)
[ 930208.730]  -> wl_registry@2.bind(10, "wp_viewporter", 1, new id [unknown]@10)
[ 930208.746]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@11)
[ 930208.760]  -> wl_registry@2.bind(13, "xdg_wm_base", 5, new id [unknown]@12)
[ 930208.774]  -> wl_registry@2.bind(19, "zxdg_decoration_manager_v1", 1, new id [unknown]@13)
[ 930208.793]  -> wl_registry@2.bind(37, "xdg_activation_v1", 1, new id [unknown]@14)
[ 930208.808]  -> wl_registry@2.bind(35, "zwp_text_input_manager_v3", 1, new id [unknown]@15)
[ 930208.820]  -> wl_registry@2.bind(23, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@16)
[ 930208.830]  -> wl_registry@2.bind(22, "zwp_pointer_constraints_v1", 1, new id [unknown]@17)
[ 930208.842]  -> wl_display@1.sync(new id wl_callback@18)
[ 930210.257] wl_display@1.delete_id(18)
[ 930210.270] wl_output@5.geometry(0, 0, 1190, 340, 0, "AOC", "AG493UG7R4", 0)
[ 930210.290] wl_output@5.mode(1, 5120, 1440, 120000)
[ 930210.298] wl_output@5.scale(1)
[ 930210.303] wl_output@5.name("DP-3")
[ 930210.314] wl_output@5.description("AOC AG493UG7R4 0x0000013D (DP-3)")
[ 930210.324] wl_output@5.done()
[ 930210.334] zxdg_output_v1@7.name("DP-3")
[ 930210.344] zxdg_output_v1@7.description("AOC AG493UG7R4 0x0000013D (DP-3)")
[ 930210.354] zxdg_output_v1@7.logical_position(0, 0)
[ 930210.369] zxdg_output_v1@7.logical_size(5120, 1440)
[ 930210.378] wl_output@5.done()
[ 930210.386] wl_seat@8.name("seat0")
[ 930210.395] wl_seat@8.capabilities(3)
[ 930210.405] wl_shm@11.format(0)
[ 930210.415] wl_shm@11.format(1)
[ 930210.422] wl_shm@11.format(875709016)
[ 930210.432] wl_shm@11.format(875708993)
[ 930210.450] wl_shm@11.format(875710274)
[ 930210.456] wl_shm@11.format(842094674)
[ 930210.463] wl_shm@11.format(842088786)
[ 930210.472] wl_shm@11.format(892426322)
[ 930210.480] wl_shm@11.format(892420434)
[ 930210.486] wl_shm@11.format(909199186)
[ 930210.495] wl_shm@11.format(808665688)
[ 930210.502] wl_shm@11.format(808665665)
[ 930210.519] wl_shm@11.format(1211384408)
[ 930210.528] wl_shm@11.format(1211384385)
[ 930210.537] wl_shm@11.format(942948952)
[ 930210.548] wl_shm@11.format(942948929)
[ 930210.557] wl_callback@18.done(21471)
[ 930210.626]  -> wl_seat@8.get_keyboard(new id wl_keyboard@18)
[ 930216.178]  -> zwp_text_input_manager_v3@15.get_text_input(new id zwp_text_input_v3@19, wl_seat@8)
[ 930216.203]  -> wl_compositor@3.create_surface(new id wl_surface@20)
[ 930216.210]  -> wl_seat@8.get_pointer(new id wl_pointer@21)
[ 930216.218]  -> wl_registry@2.bind(39, "wp_cursor_shape_manager_v1", 1, new id [unknown]@22)
[ 930216.224]  -> wp_cursor_shape_manager_v1@22.get_pointer(new id wp_cursor_shape_device_v1@23, wl_pointer@21)
[ 930216.238]  -> zwp_relative_pointer_manager_v1@16.get_relative_pointer(new id zwp_relative_pointer_v1@24, wl_pointer@21)
Created log file at "/tmp/Alacritty-14670.log"
[0.000002508s] [INFO ] [alacritty] Welcome to Alacritty
[0.000065939s] [INFO ] [alacritty] Version 0.14.0-dev (295ac412)
[0.000073546s] [INFO ] [alacritty] Running on Wayland
[0.000225622s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/z/.config/alacritty/alacritty.toml"
[0.000591374s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.000604152s] [INFO ] [alacritty] winit event: Resumed
[ 930216.896]  -> wl_display@1.get_registry(new id wl_registry@25)
[ 930216.905]  -> wl_display@1.sync(new id wl_callback@26)
[ 930216.993] wl_display@1.delete_id(26)
[ 930216.996] wl_registry@25.global(1, "wl_shm", 1)
[ 930217.001] wl_registry@25.global(2, "wl_drm", 2)
[ 930217.003] wl_registry@25.global(3, "zwp_linux_dmabuf_v1", 4)
[ 930217.005] wl_registry@25.global(4, "wl_compositor", 6)
[ 930217.007] wl_registry@25.global(5, "wl_subcompositor", 1)
[ 930217.009] wl_registry@25.global(6, "wl_data_device_manager", 3)
[ 930217.011] wl_registry@25.global(7, "zwlr_export_dmabuf_manager_v1", 1)
[ 930217.014] wl_registry@25.global(8, "zwlr_data_control_manager_v1", 2)
[ 930217.016] wl_registry@25.global(9, "zwp_primary_selection_device_manager_v1", 1)
[ 930217.018] wl_registry@25.global(10, "wp_viewporter", 1)
[ 930217.020] wl_registry@25.global(11, "zwlr_gamma_control_manager_v1", 1)
[ 930217.022] wl_registry@25.global(12, "zwlr_output_power_manager_v1", 1)
[ 930217.024] wl_registry@25.global(13, "xdg_wm_base", 5)
[ 930217.026] wl_registry@25.global(14, "wl_seat", 8)
[ 930217.028] wl_registry@25.global(15, "wp_presentation", 1)
[ 930217.030] wl_registry@25.global(16, "ext_idle_notifier_v1", 1)
[ 930217.033] wl_registry@25.global(17, "zwlr_layer_shell_v1", 4)
[ 930217.034] wl_registry@25.global(18, "org_kde_kwin_server_decoration_manager", 1)
[ 930217.037] wl_registry@25.global(19, "zxdg_decoration_manager_v1", 1)
[ 930217.040] wl_registry@25.global(20, "zwlr_output_manager_v1", 4)
[ 930217.042] wl_registry@25.global(21, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 930217.044] wl_registry@25.global(22, "zwp_pointer_constraints_v1", 1)
[ 930217.047] wl_registry@25.global(23, "zwp_relative_pointer_manager_v1", 1)
[ 930217.050] wl_registry@25.global(24, "zwp_virtual_keyboard_manager_v1", 1)
[ 930217.052] wl_registry@25.global(25, "zwlr_virtual_pointer_manager_v1", 2)
[ 930217.054] wl_registry@25.global(26, "zwlr_foreign_toplevel_manager_v1", 3)
[ 930217.057] wl_registry@25.global(27, "wp_drm_lease_device_v1", 1)
[ 930217.059] wl_registry@25.global(28, "zwp_tablet_manager_v2", 1)
[ 930217.061] wl_registry@25.global(29, "zwp_idle_inhibit_manager_v1", 1)
[ 930217.063] wl_registry@25.global(30, "zxdg_exporter_v1", 1)
[ 930217.067] wl_registry@25.global(31, "zxdg_importer_v1", 1)
[ 930217.069] wl_registry@25.global(32, "zxdg_exporter_v2", 1)
[ 930217.071] wl_registry@25.global(33, "zxdg_importer_v2", 1)
[ 930217.073] wl_registry@25.global(34, "zwp_pointer_gestures_v1", 3)
[ 930217.075] wl_registry@25.global(35, "zwp_text_input_manager_v3", 1)
[ 930217.077] wl_registry@25.global(36, "zwp_input_method_manager_v2", 1)
[ 930217.079] wl_registry@25.global(37, "xdg_activation_v1", 1)
[ 930217.081] wl_registry@25.global(38, "ext_session_lock_manager_v1", 1)
[ 930217.083] wl_registry@25.global(39, "wp_cursor_shape_manager_v1", 1)
[ 930217.086] wl_registry@25.global(40, "wp_tearing_control_manager_v1", 1)
[ 930217.088] wl_registry@25.global(41, "wp_single_pixel_buffer_manager_v1", 1)
[ 930217.090] wl_registry@25.global(42, "xwayland_shell_v1", 1)
[ 930217.092] wl_registry@25.global(43, "hyprland_toplevel_export_manager_v1", 2)
[ 930217.094] wl_registry@25.global(44, "wp_fractional_scale_manager_v1", 1)
[ 930217.096] wl_registry@25.global(45, "zwp_text_input_manager_v1", 1)
[ 930217.098] wl_registry@25.global(46, "hyprland_global_shortcuts_manager_v1", 1)
[ 930217.100] wl_registry@25.global(47, "zwlr_screencopy_manager_v1", 3)
[ 930217.102] wl_registry@25.global(48, "zxdg_output_manager_v1", 3)
[ 930217.104] wl_registry@25.global(49, "wl_output", 4)
[ 930217.106] wl_callback@26.done(21471)
[ 930217.121]  -> wl_registry@25.bind(6, "wl_data_device_manager", 3, new id [unknown]@26)
[ 930217.126]  -> wl_registry@25.bind(9, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@27)
[ 930217.129]  -> wl_registry@25.bind(14, "wl_seat", 7, new id [unknown]@28)
[ 930217.153] wl_seat@28.name("seat0")
[ 930217.156] wl_seat@28.capabilities(3)
[ 930217.161]  -> wl_seat@28.get_keyboard(new id wl_keyboard@29)
[ 930217.165]  -> wl_data_device_manager@26.get_data_device(new id wl_data_device@30, wl_seat@28)
[ 930217.170]  -> zwp_primary_selection_device_manager_v1@27.get_device(new id zwp_primary_selection_device_v1@31, wl_seat@28)
[ 930217.174]  -> wl_seat@28.get_pointer(new id wl_pointer@32)
[ 930217.191] wl_keyboard@29.keymap(1, fd 21, 70396)
[ 930217.195] wl_keyboard@29.repeat_info(25, 600)
[ 930217.911]  -> wl_display@1.get_registry(new id wl_registry@33)
[ 930217.920]  -> wl_display@1.sync(new id wl_callback@34)
[ 930218.016] wl_registry@33.global(1, "wl_shm", 1)
[ 930218.016] wl_display@1.delete_id(34)
[ 930218.020] wl_registry@33.global(2, "wl_drm", 2)
[ 930218.024] wl_registry@33.global(3, "zwp_linux_dmabuf_v1", 4)
[ 930218.027]  -> wl_registry@33.bind(3, "zwp_linux_dmabuf_v1", 4, new id [unknown]@35)
[ 930218.029] wl_registry@33.global(4, "wl_compositor", 6)
[ 930218.031] wl_registry@33.global(5, "wl_subcompositor", 1)
[ 930218.032] wl_registry@33.global(6, "wl_data_device_manager", 3)
[ 930218.035] wl_registry@33.global(7, "zwlr_export_dmabuf_manager_v1", 1)
[ 930218.036] wl_registry@33.global(8, "zwlr_data_control_manager_v1", 2)
[ 930218.038] wl_registry@33.global(9, "zwp_primary_selection_device_manager_v1", 1)
[ 930218.040] wl_registry@33.global(10, "wp_viewporter", 1)
[ 930218.042] wl_registry@33.global(11, "zwlr_gamma_control_manager_v1", 1)
[ 930218.043] wl_registry@33.global(12, "zwlr_output_power_manager_v1", 1)
[ 930218.045] wl_registry@33.global(13, "xdg_wm_base", 5)
[ 930218.047] wl_registry@33.global(14, "wl_seat", 8)
[ 930218.049] wl_registry@33.global(15, "wp_presentation", 1)
[ 930218.052] wl_registry@33.global(16, "ext_idle_notifier_v1", 1)
[ 930218.055] wl_registry@33.global(17, "zwlr_layer_shell_v1", 4)
[ 930218.057] wl_registry@33.global(18, "org_kde_kwin_server_decoration_manager", 1)
[ 930218.060] wl_registry@33.global(19, "zxdg_decoration_manager_v1", 1)
[ 930218.063] wl_registry@33.global(20, "zwlr_output_manager_v1", 4)
[ 930218.066] wl_registry@33.global(21, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 930218.068] wl_registry@33.global(22, "zwp_pointer_constraints_v1", 1)
[ 930218.071] wl_registry@33.global(23, "zwp_relative_pointer_manager_v1", 1)
[ 930218.073] wl_registry@33.global(24, "zwp_virtual_keyboard_manager_v1", 1)
[ 930218.076] wl_registry@33.global(25, "zwlr_virtual_pointer_manager_v1", 2)
[ 930218.078] wl_registry@33.global(26, "zwlr_foreign_toplevel_manager_v1", 3)
[ 930218.081] wl_registry@33.global(27, "wp_drm_lease_device_v1", 1)
[ 930218.083] wl_registry@33.global(28, "zwp_tablet_manager_v2", 1)
[ 930218.085] wl_registry@33.global(29, "zwp_idle_inhibit_manager_v1", 1)
[ 930218.087] wl_registry@33.global(30, "zxdg_exporter_v1", 1)
[ 930218.089] wl_registry@33.global(31, "zxdg_importer_v1", 1)
[ 930218.092] wl_registry@33.global(32, "zxdg_exporter_v2", 1)
[ 930218.093] wl_registry@33.global(33, "zxdg_importer_v2", 1)
[ 930218.096] wl_registry@33.global(34, "zwp_pointer_gestures_v1", 3)
[ 930218.098] wl_registry@33.global(35, "zwp_text_input_manager_v3", 1)
[ 930218.100] wl_registry@33.global(36, "zwp_input_method_manager_v2", 1)
[ 930218.102] wl_registry@33.global(37, "xdg_activation_v1", 1)
[ 930218.105] wl_registry@33.global(38, "ext_session_lock_manager_v1", 1)
[ 930218.107] wl_registry@33.global(39, "wp_cursor_shape_manager_v1", 1)
[ 930218.110] wl_registry@33.global(40, "wp_tearing_control_manager_v1", 1)
[ 930218.113] wl_registry@33.global(41, "wp_single_pixel_buffer_manager_v1", 1)
[ 930218.116] wl_registry@33.global(42, "xwayland_shell_v1", 1)
[ 930218.119] wl_registry@33.global(43, "hyprland_toplevel_export_manager_v1", 2)
[ 930218.122] wl_registry@33.global(44, "wp_fractional_scale_manager_v1", 1)
[ 930218.125] wl_registry@33.global(45, "zwp_text_input_manager_v1", 1)
[ 930218.127] wl_registry@33.global(46, "hyprland_global_shortcuts_manager_v1", 1)
[ 930218.130] wl_registry@33.global(47, "zwlr_screencopy_manager_v1", 3)
[ 930218.132] wl_registry@33.global(48, "zxdg_output_manager_v1", 3)
[ 930218.135] wl_registry@33.global(49, "wl_output", 4)
[ 930218.137] wl_callback@34.done(21471)
[ 930218.140]  -> zwp_linux_dmabuf_v1@35.get_default_feedback(new id zwp_linux_dmabuf_feedback_v1@34)
[ 930218.144]  -> wl_display@1.sync(new id wl_callback@36)
[ 930218.165] wl_display@1.delete_id(36)
[ 930218.167] zwp_linux_dmabuf_feedback_v1@34.main_device(array[8])
[ 930218.281] zwp_linux_dmabuf_feedback_v1@34.format_table(fd 20, 3824)
[ 930218.290] zwp_linux_dmabuf_feedback_v1@34.tranche_target_device(array[8])
[ 930218.292] zwp_linux_dmabuf_feedback_v1@34.tranche_flags(0)
[ 930218.293] zwp_linux_dmabuf_feedback_v1@34.tranche_formats(array[478])
[ 930218.299] zwp_linux_dmabuf_feedback_v1@34.tranche_done()
[ 930218.301] zwp_linux_dmabuf_feedback_v1@34.done()
[ 930218.303] wl_callback@36.done(21471)
[ 930218.306]  -> zwp_linux_dmabuf_feedback_v1@34.destroy()
[0.015039112s] [INFO ] [alacritty] Using EGL 1.5
[ 930231.555]  -> wl_compositor@3.create_surface(new id wl_surface@36)
[ 930231.565]  -> xdg_wm_base@12.get_xdg_surface(new id xdg_surface@37, wl_surface@36)
[ 930231.569]  -> xdg_surface@37.get_toplevel(new id xdg_toplevel@38)
[ 930231.573]  -> zxdg_decoration_manager_v1@13.get_toplevel_decoration(new id zxdg_toplevel_decoration_v1@39, xdg_toplevel@38)
[ 930231.577]  -> zxdg_toplevel_decoration_v1@39.set_mode(2)
[ 930231.582]  -> wp_viewporter@10.get_viewport(new id wp_viewport@40, wl_surface@36)
[ 930231.585]  -> wp_fractional_scale_manager_v1@9.get_fractional_scale(new id wp_fractional_scale_v1@41, wl_surface@36)
[ 930231.590]  -> wl_surface@36.set_opaque_region(nil)
[ 930231.594]  -> xdg_toplevel@38.set_app_id("Alacritty")
[ 930231.596]  -> xdg_toplevel@38.set_title("Alacritty")
[ 930231.599]  -> xdg_toplevel@38.set_min_size(2, 1)
[ 930231.604]  -> xdg_toplevel@38.set_max_size(0, 0)
[ 930231.606]  -> wl_surface@36.commit()
[ 930231.612]  -> wl_display@1.sync(new id wl_callback@42)
[ 930231.616] wl_keyboard@18.keymap(1, fd 17, 70396)
[ 930231.636] wl_keyboard@18.repeat_info(25, 600)
[ 930231.639] wl_keyboard@18.keymap(1, fd 22, 70396)
[ 930231.642] wl_keyboard@18.repeat_info(25, 600)
[ 930234.353] wl_display@1.delete_id(34)
[ 930234.397] wl_display@1.delete_id(42)
[ 930234.403] wp_fractional_scale_v1@41.preferred_scale(120)
[ 930234.408] wl_callback@42.done(21472)
[ 930234.412] xdg_toplevel@38.wm_capabilities(array[16])
[ 930234.415] xdg_toplevel@38.configure(0, 0, array[0])
[ 930234.418] zxdg_toplevel_decoration_v1@39.configure(2)
[ 930234.422] xdg_surface@37.configure(21472)
[ 930234.433]  -> xdg_surface@37.ack_configure(21472)
[ 930234.438]  -> wl_surface@36.set_opaque_region(nil)
[ 930234.440]  -> xdg_surface@37.set_window_geometry(0, 0, 800, 600)
[ 930234.444]  -> wp_viewport@40.set_destination(800, 600)
[ 930234.449]  -> wl_surface@36.set_opaque_region(nil)
[0.018166552s] [INFO ] [alacritty] Window scale factor: 1
[ 930283.451]  -> zwp_linux_dmabuf_v1@35.get_surface_feedback(new id zwp_linux_dmabuf_feedback_v1@42, wl_surface@36)
[ 930283.469]  -> wl_display@1.sync(new id wl_callback@34)
[ 930283.955] wl_callback@34.done(21473)
[ 930283.955] wl_display@1.delete_id(34)
[ 930284.234] zwp_linux_dmabuf_feedback_v1@42.main_device(array[8])
[ 930284.236] zwp_linux_dmabuf_feedback_v1@42.format_table(fd 17, 3824)
[ 930284.244] zwp_linux_dmabuf_feedback_v1@42.tranche_target_device(array[8])
[ 930284.245] zwp_linux_dmabuf_feedback_v1@42.tranche_flags(0)
[ 930284.247] zwp_linux_dmabuf_feedback_v1@42.tranche_formats(array[478])
[ 930284.250] zwp_linux_dmabuf_feedback_v1@42.tranche_done()
[ 930284.252] zwp_linux_dmabuf_feedback_v1@42.done()
[0.068578619s] [INFO ] [alacritty] Running on Mesa Intel(R) Xe Graphics (TGL GT2)
[0.068619363s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2, shader_version 4.60
[0.068627796s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.080844718s] [INFO ] [alacritty] Cell size: 10 x 21
[0.080872393s] [INFO ] [alacritty] Padding: 5 x 10
[0.080875988s] [INFO ] [alacritty] Width: 800, Height: 600
[0.080905146s] [INFO ] [alacritty] PTY dimensions: 27 x 79
[0.082736181s] [INFO ] [alacritty] Initialisation complete
[0.082755503s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: ScaleFactorChanged { scale_factor: 1.0, inner_size_writer: InnerSizeWriter { new_inner_size: (Weak) } } }
[0.082770621s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[0.082779403s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[0.125599747s] [INFO ] [alacritty] Font size changed to 16.0 px
[0.125648503s] [INFO ] [alacritty] Cell size: 10 x 21
[0.133926552s] [INFO ] [alacritty] Padding: 5 x 10
[0.133971497s] [INFO ] [alacritty] Width: 800, Height: 600
[ 930350.444]  -> wl_surface@36.frame(new id wl_callback@34)
[ 930350.790]  -> zwp_linux_dmabuf_v1@35.create_params(new id zwp_linux_buffer_params_v1@43)
[ 930350.821]  -> zwp_linux_buffer_params_v1@43.add(fd 30, 0, 0, 3584, 16777216, 8)
[ 930350.829]  -> zwp_linux_buffer_params_v1@43.add(fd 31, 1, 2228224, 448, 16777216, 8)
[ 930350.834]  -> zwp_linux_buffer_params_v1@43.add(fd 32, 2, 2240512, 64, 16777216, 8)
[ 930350.837]  -> zwp_linux_buffer_params_v1@43.create_immed(new id wl_buffer@44, 800, 600, 875713089, 0)
[ 930350.841]  -> zwp_linux_buffer_params_v1@43.destroy()
[ 930350.846]  -> wl_surface@36.attach(wl_buffer@44, 0, 0)
[ 930350.851]  -> wl_surface@36.damage_buffer(0, 0, 800, 600)
[ 930350.855]  -> wl_surface@36.commit()
[ 930350.858]  -> wl_display@1.sync(new id wl_callback@45)
[0.134606648s] [INFO ] [alacritty] winit event: AboutToWait
[0.134644194s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 88316163 }, requested_resume: None })
[0.134653130s] [INFO ] [alacritty] winit event: AboutToWait
[ 930351.592] wl_display@1.delete_id(43)
[ 930351.594] wl_display@1.delete_id(45)
[ 930351.611] wl_keyboard@18.enter(21477, wl_surface@36, array[0])
[ 930351.598] wl_keyboard@29.enter(21477, wl_surface@36, array[0])
[ 930351.619] wl_keyboard@18.modifiers(21478, 0, 0, 0, 0)
[ 930351.629] wl_keyboard@29.modifiers(21478, 0, 0, 0, 0)
[ 930351.637] wl_data_device@30.data_offer(new id wl_data_offer@4278190080)
[ 930351.642] wl_data_offer@4278190080.offer("text/plain;charset=utf-8")
[ 930351.646] wl_data_offer@4278190080.offer("UTF8_STRING")
[ 930351.650] wl_data_offer@4278190080.offer("text/plain")
[ 930351.633] wl_surface@36.enter(wl_output@5)
[ 930351.653] wl_data_device@30.selection(wl_data_offer@4278190080)
[ 930351.656] wp_fractional_scale_v1@41.preferred_scale(120)
[ 930351.659] zwp_primary_selection_device_v1@31.data_offer(new id zwp_primary_selection_offer_v1@4278190081)
[ 930351.663] wl_surface@36.preferred_buffer_scale(1)
[ 930351.667] zwp_primary_selection_offer_v1@4278190081.offer("text/plain;charset=utf-8")
[ 930351.670] wl_surface@36.preferred_buffer_transform(0)
[ 930351.671] zwp_primary_selection_offer_v1@4278190081.offer("UTF8_STRING")
[ 930351.672] wp_fractional_scale_v1@41.preferred_scale(120)
[ 930351.676] zwp_primary_selection_offer_v1@4278190081.offer("text/plain")
[ 930351.678] wl_pointer@21.enter(21480, wl_surface@36, -616.12890625, -159.35156250)
[ 930351.685] wl_pointer@21.frame()
[ 930351.682] zwp_primary_selection_device_v1@31.selection(zwp_primary_selection_offer_v1@4278190081)
[ 930351.688] xdg_toplevel@38.configure(1324, 679, array[24])
[ 930351.691] zwp_primary_selection_device_v1@31.data_offer(new id zwp_primary_selection_offer_v1@4278190082)
[ 930351.695] xdg_surface@37.configure(21474)
[ 930351.698] zwp_primary_selection_offer_v1@4278190082.offer("text/plain;charset=utf-8")
[ 930351.701] zwp_primary_selection_offer_v1@4278190082.offer("UTF8_STRING")
[ 930351.704] zwp_primary_selection_offer_v1@4278190082.offer("text/plain")
[ 930351.706] zwp_primary_selection_device_v1@31.selection(zwp_primary_selection_offer_v1@4278190082)
[ 930351.711] wl_pointer@32.enter(21480, wl_surface@36, -616.12890625, -159.35156250)
[ 930351.715] wl_pointer@32.frame()
[ 930351.716]  -> wp_cursor_shape_device_v1@23.set_shape(21480, 9)
[ 930351.726]  -> xdg_surface@37.ack_configure(21474)
[ 930351.731]  -> wl_surface@36.set_opaque_region(nil)
[ 930351.735]  -> xdg_surface@37.set_window_geometry(0, 0, 1324, 679)
[ 930351.740]  -> wp_viewport@40.set_destination(1324, 679)
[ 930351.749]  -> zwp_primary_selection_offer_v1@4278190081.destroy()
[0.135462989s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 88343453 }, requested_resume: None })
[0.135480275s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: ScaleFactorChanged { scale_factor: 1.0, inner_size_writer: InnerSizeWriter { new_inner_size: (Weak) } } }
[0.135489216s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: Resized(PhysicalSize { width: 1324, height: 679 }) }
[0.135495367s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: Focused(true) }
[0.135500504s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[0.135505918s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorEntered { device_id: DeviceId(Wayland(DeviceId)) } }
[0.135510930s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorMoved { device_id: DeviceId(Wayland(DeviceId)), position: PhysicalPosition { x: -616.12890625, y: -159.3515625 } } }
[0.135517363s] [INFO ] [alacritty] winit event: AboutToWait
[ 930357.658] wl_display@1.delete_id(34)
[0.178528248s] [INFO ] [alacritty] Font size changed to 16.0 px
[0.178575977s] [INFO ] [alacritty] Cell size: 10 x 21
[ 930395.620] wl_callback@34.done(144892094)
[0.179359285s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 132994561 }, requested_resume: None })
[0.179407089s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[0.184138778s] [INFO ] [alacritty] Padding: 5 x 10
[0.184191656s] [INFO ] [alacritty] Width: 1324, Height: 679
[ 930400.571] wl_callback@45.done(21480)
[ 930401.460]  -> wl_surface@36.frame(new id wl_callback@45)
[ 930401.638]  -> zwp_linux_dmabuf_v1@35.create_params(new id zwp_linux_buffer_params_v1@34)
[ 930401.654]  -> zwp_linux_buffer_params_v1@34.add(fd 30, 0, 0, 5632, 16777216, 8)
[ 930401.659]  -> zwp_linux_buffer_params_v1@34.add(fd 31, 1, 3997696, 704, 16777216, 8)
[ 930401.662]  -> zwp_linux_buffer_params_v1@34.add(fd 32, 2, 4014080, 64, 16777216, 8)
[ 930401.665]  -> zwp_linux_buffer_params_v1@34.create_immed(new id wl_buffer@43, 1324, 679, 875713089, 0)
[ 930401.668]  -> zwp_linux_buffer_params_v1@34.destroy()
[ 930401.671]  -> wl_surface@36.attach(wl_buffer@43, 0, 0)
[ 930401.673]  -> wl_surface@36.damage_buffer(0, 0, 1324, 679)
[ 930401.676]  -> wl_surface@36.commit()
[ 930401.678]  -> wl_display@1.sync(new id wl_callback@46)
[0.185406392s] [INFO ] [alacritty] winit event: AboutToWait
[0.185430877s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 139109414 }, requested_resume: None })
[0.185445874s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94135324546912))), payload: Terminal(Title(z@gentoo:~)) })
[0.185452812s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94135324546912))), payload: Terminal(Wakeup) })
[0.185457042s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94135324546912))), payload: Terminal(Wakeup) })
[0.185461204s] [INFO ] [alacritty] winit event: AboutToWait
[ 930401.754]  -> xdg_toplevel@38.set_title("z@gentoo:~")
[0.185477454s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 139159840 }, requested_resume: None })
[0.185482691s] [INFO ] [alacritty] winit event: AboutToWait
[ 930401.782] wl_display@1.delete_id(34)
[ 930401.784] wl_display@1.delete_id(46)
[ 930407.707] wl_callback@45.done(144892144)
[ 930407.707] wl_display@1.delete_id(45)
[0.191446118s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 139193498 }, requested_resume: None })
[0.191476893s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[ 930407.850] wl_buffer@44.release()
[ 930407.853]  -> wl_buffer@44.destroy()
[ 930407.856] wl_callback@46.done(21480)
[ 930408.436]  -> wl_surface@36.frame(new id wl_callback@46)
[ 930408.579]  -> zwp_linux_dmabuf_v1@35.create_params(new id zwp_linux_buffer_params_v1@45)
[ 930408.612]  -> zwp_linux_buffer_params_v1@45.add(fd 30, 0, 0, 5632, 16777216, 8)
[ 930408.618]  -> zwp_linux_buffer_params_v1@45.add(fd 31, 1, 3997696, 704, 16777216, 8)
[ 930408.622]  -> zwp_linux_buffer_params_v1@45.add(fd 32, 2, 4014080, 64, 16777216, 8)
[ 930408.625]  -> zwp_linux_buffer_params_v1@45.create_immed(new id wl_buffer@34, 1324, 679, 875713089, 0)
[ 930408.629]  -> zwp_linux_buffer_params_v1@45.destroy()
[ 930408.633]  -> wl_surface@36.attach(wl_buffer@34, 0, 0)
[ 930408.636]  -> wl_surface@36.damage_buffer(45, 0, 30, 41)
[ 930408.639]  -> wl_surface@36.commit()
[ 930408.642]  -> wl_display@1.sync(new id wl_callback@47)
[0.192372617s] [INFO ] [alacritty] winit event: AboutToWait
[ 930408.767] wl_display@1.delete_id(44)
[ 930408.769] wl_display@1.delete_id(45)
[ 930408.772] wl_display@1.delete_id(47)
[ 930416.235] wl_display@1.delete_id(46)
[ 930416.259] wl_callback@46.done(144892152)
[ 931402.897] wl_pointer@32.motion(144893138, 42.48828125, 177.64843750)
[ 931402.895] zwp_relative_pointer_v1@24.relative_motion(33, 3159217232, -0.88671875, 0.00000000, -1.00000000, 0.00000000)
[ 931402.941] wl_pointer@32.frame()
[ 931402.956] wl_pointer@21.motion(144893138, 42.48828125, 177.64843750)
[ 931402.958] wl_pointer@32.motion(144893138, 39.05078125, 179.36718750)
[ 931402.972] wl_pointer@21.frame()
[ 931402.980] wl_pointer@32.frame()
[ 931402.988] zwp_relative_pointer_v1@24.relative_motion(33, 3159217232, -3.43750000, 1.71875000, -2.00000000, 1.00000000)
[ 931402.996] wl_pointer@32.motion(144893138, 21.05078125, 189.36718750)
[ 931403.002] wl_pointer@21.motion(144893138, 39.05078125, 179.36718750)
[ 931403.006] wl_pointer@32.frame()
[ 931403.014] wl_pointer@21.frame()
[ 931403.023] wl_pointer@32.motion(144893138, 7.05078125, 197.36718750)
[ 931403.032] zwp_relative_pointer_v1@24.relative_motion(33, 3159217232, -18.00000000, 10.00000000, -9.00000000, 5.00000000)
[ 931403.039] wl_pointer@32.frame()
[ 931403.045] wl_pointer@21.motion(144893138, 21.05078125, 189.36718750)
[ 931403.049] wl_keyboard@29.leave(21482, wl_surface@36)
[ 931403.055] wl_pointer@21.frame()
[ 931403.063] wl_pointer@32.leave(21486, wl_surface@36)
[ 931403.064] zwp_relative_pointer_v1@24.relative_motion(33, 3159217232, -14.00000000, 8.00000000, -7.00000000, 4.00000000)
[ 931403.084] wl_pointer@21.motion(144893138, 7.05078125, 197.36718750)
[ 931403.074] wl_pointer@32.frame()
[ 931403.095] wl_pointer@21.frame()
[ 931403.122] zwp_relative_pointer_v1@24.relative_motion(33, 3159217232, -88.00000000, 42.00000000, -44.00000000, 21.00000000)
[ 931403.149] wl_keyboard@18.leave(21482, wl_surface@36)
[ 931403.161] wl_pointer@21.leave(21486, wl_surface@36)
[ 931403.172] wl_pointer@21.frame()
[ 931403.195] xdg_toplevel@38.configure(1324, 679, array[20])
[ 931403.210] xdg_surface@37.configure(21481)
[ 931403.273]  -> xdg_surface@37.ack_configure(21481)
[1.187022418s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144892, tv_nsec: 153673475 }, requested_resume: None })
[1.187098178s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(Wayland(DeviceId)), event: MouseMotion { delta: (-1.0, 0.0) } }
[1.187121697s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorMoved { device_id: DeviceId(Wayland(DeviceId)), position: PhysicalPosition { x: 42.48828125, y: 177.6484375 } } }
[1.187146075s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(Wayland(DeviceId)), event: MouseMotion { delta: (-2.0, 1.0) } }
[1.187163386s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorMoved { device_id: DeviceId(Wayland(DeviceId)), position: PhysicalPosition { x: 39.05078125, y: 179.3671875 } } }
[1.187181622s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(Wayland(DeviceId)), event: MouseMotion { delta: (-9.0, 5.0) } }
[1.187198891s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorMoved { device_id: DeviceId(Wayland(DeviceId)), position: PhysicalPosition { x: 21.05078125, y: 189.3671875 } } }
[1.187216737s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(Wayland(DeviceId)), event: MouseMotion { delta: (-7.0, 4.0) } }
[1.187233057s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorMoved { device_id: DeviceId(Wayland(DeviceId)), position: PhysicalPosition { x: 7.05078125, y: 197.3671875 } } }
[1.187250618s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(Wayland(DeviceId)), event: MouseMotion { delta: (-44.0, 21.0) } }
[1.187267476s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[1.187286510s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: Focused(false) }
[1.187302351s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: CursorLeft { device_id: DeviceId(Wayland(DeviceId)) } }
[1.187342278s] [INFO ] [alacritty] winit event: AboutToWait
[1.187395558s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144893, tv_nsec: 141063281 }, requested_resume: None })
[1.187415667s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[ 931403.945] wl_buffer@43.release()
[ 931403.966] wl_callback@47.done(21480)
[ 931404.109]  -> wl_surface@36.frame(new id wl_callback@47)
[ 931404.327]  -> wl_surface@36.attach(wl_buffer@43, 0, 0)
[ 931404.343]  -> wl_surface@36.damage_buffer(45, 0, 30, 41)
[ 931404.389]  -> wl_surface@36.commit()
[ 931404.399]  -> wl_display@1.sync(new id wl_callback@46)
[1.188135946s] [INFO ] [alacritty] winit event: AboutToWait
[ 931405.364] wl_display@1.delete_id(46)
[ 931417.070] wl_display@1.delete_id(47)
[ 931417.104] wl_callback@47.done(144893152)
[ 937977.825] wl_keyboard@29.keymap(1, fd 29, 70396)
[ 937977.919] wl_keyboard@18.keymap(1, fd 30, 70396)
[ 937977.930] wl_output@5.scale(2)
[ 937977.934] zxdg_output_v1@7.logical_position(0, 0)
[ 937977.938] zxdg_output_v1@7.logical_size(4096, 1152)
[ 937977.941] zxdg_output_v1@7.logical_position(0, 0)
[ 937977.944] zxdg_output_v1@7.logical_size(4096, 1152)
[ 937977.947] zxdg_output_v1@7.logical_position(0, 0)
[ 937977.950] zxdg_output_v1@7.logical_size(4096, 1152)
[ 937977.953] wl_output@5.done()
[ 937977.956] xdg_toplevel@38.configure(1057, 535, array[20])
[ 937977.960] xdg_surface@37.configure(21536)
[ 937979.952]  -> xdg_surface@37.ack_configure(21536)
[ 937979.964]  -> wl_surface@36.set_opaque_region(nil)
[ 937979.969]  -> xdg_surface@37.set_window_geometry(0, 0, 1057, 535)
[ 937979.974]  -> wp_viewport@40.set_destination(1057, 535)
[7.763702102s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144893, tv_nsec: 154530723 }, requested_resume: None })
[7.763739634s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: Resized(PhysicalSize { width: 1057, height: 535 }) }
[7.763759973s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[7.763818881s] [INFO ] [alacritty] Padding: 5 x 10
[7.763826318s] [INFO ] [alacritty] Width: 1057, Height: 535
[ 937981.461] wl_buffer@34.release()
[ 937981.468]  -> wl_buffer@34.destroy()
[ 937981.472] wl_callback@46.done(21487)
[ 937982.620]  -> wl_surface@36.frame(new id wl_callback@46)
[ 937982.844]  -> zwp_linux_dmabuf_v1@35.create_params(new id zwp_linux_buffer_params_v1@47)
[ 937982.863]  -> zwp_linux_buffer_params_v1@47.add(fd 30, 0, 0, 4608, 16777216, 8)
[ 937982.870]  -> zwp_linux_buffer_params_v1@47.add(fd 31, 1, 2555904, 576, 16777216, 8)
[ 937982.875]  -> zwp_linux_buffer_params_v1@47.add(fd 32, 2, 2568192, 64, 16777216, 8)
[ 937982.879]  -> zwp_linux_buffer_params_v1@47.create_immed(new id wl_buffer@45, 1057, 535, 875713089, 0)
[ 937982.883]  -> zwp_linux_buffer_params_v1@47.destroy()
[ 937982.887]  -> wl_surface@36.attach(wl_buffer@45, 0, 0)
[ 937982.891]  -> wl_surface@36.damage_buffer(0, 0, 1057, 535)
[ 937982.894]  -> wl_surface@36.commit()
[ 937982.898]  -> wl_display@1.sync(new id wl_callback@44)
[7.766628283s] [INFO ] [alacritty] winit event: AboutToWait
[7.768793968s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144899, tv_nsec: 720343151 }, requested_resume: None })
[7.768825436s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94135324546912))), payload: Terminal(Wakeup) })
[7.768837662s] [INFO ] [alacritty] winit event: AboutToWait
[7.768845951s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144899, tv_nsec: 722527834 }, requested_resume: None })
[7.768851353s] [INFO ] [alacritty] winit event: AboutToWait
[ 938235.879] wl_display@1.delete_id(34)
[ 938235.882] wl_display@1.delete_id(47)
[ 938235.897] wl_display@1.delete_id(44)
[ 938257.973] wl_display@1.delete_id(46)
[ 938257.976] wl_callback@46.done(144899994)
[8.041728069s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 144899, tv_nsec: 973311650 }, requested_resume: None })
[8.041773354s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94135324546912)), event: RedrawRequested }
[ 938258.175] wl_buffer@43.release()
[ 938258.202]  -> wl_buffer@43.destroy()
[ 938258.221] wl_callback@44.done(21538)
[ 938258.867]  -> wl_surface@36.frame(new id wl_callback@44)
[ 938259.240]  -> zwp_linux_dmabuf_v1@35.create_params(new id zwp_linux_buffer_params_v1@46)
[ 938259.301]  -> zwp_linux_buffer_params_v1@46.add(fd 30, 0, 0, 4608, 16777216, 8)
[ 938259.311]  -> zwp_linux_buffer_params_v1@46.add(fd 31, 1, 2555904, 576, 16777216, 8)
[ 938259.318]  -> zwp_linux_buffer_params_v1@46.add(fd 32, 2, 2568192, 64, 16777216, 8)
[ 938259.323]  -> zwp_linux_buffer_params_v1@46.create_immed(new id wl_buffer@47, 1057, 535, 875713089, 0)
[ 938259.332]  -> zwp_linux_buffer_params_v1@46.destroy()
[ 938259.338]  -> wl_surface@36.attach(wl_buffer@47, 0, 0)
[ 938259.343]  -> wl_surface@36.damage_buffer(0, 0, 1057, 535)
[ 938259.349]  -> wl_surface@36.commit()
[ 938259.355]  -> wl_display@1.sync(new id wl_callback@34)
[8.043106276s] [INFO ] [alacritty] winit event: AboutToWait
[ 938259.830] wl_display@1.delete_id(46)
[ 938259.827] wl_display@1.delete_id(43)
[ 938259.841] wl_display@1.delete_id(34)
[ 938274.455] wl_display@1.delete_id(44)
[ 938274.482] wl_callback@44.done(144900011)
```

### How to reproduce

1. Open an Alacritty window or a Qt5 program of some kind, e.g. KeepassXC.
2. Change the scale factor.
3. Observe the window is blurry.

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by 1over137**
#### Describe your PR, what does it fix/add?
Fix #4363

Send preferred scale to surfaces on monitor config change. This is needed for
some applications to adjust their rendered scale properly, including
KeepassXC, alacritty, and mpv, otherwise the rendered scale is not updated for
the applications, resulting in blurry windows due to nearest neighbor or
linear scaling.  

Fix is confirmed to work as a patch on v0.34.0

### CODE REVIEW

File: src/render/Renderer.cpp [hunk 1]
```diff
@@ -2039,6 +2039,19 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
 
     wlr_output_set_scale(pMonitor->output, pMonitor->scale);
 
+    // Set scale for all surfaces on this monitor, needed for some clients
+    for (const auto& window : g_pCompositor->m_vWindows) {
```
Comment (vaxerski) [inline src/render/Renderer.cpp:2043]: we use `w` for an interator.

File: src/render/Renderer.cpp [hunk 2]
```diff
@@ -2039,6 +2039,19 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
...
+        if (window->m_iMonitorID == pMonitor->ID) {
+            wlr_surface_for_each_surface(
```
Comment (vaxerski) [inline src/render/Renderer.cpp:2045]: you can use the updatesurfacescaletransform iirc function in CWindow (I dont remember the exact name) 

worth noting its not const so you'll have to de-const the iterator

**Comment by 1over137** [comment]
Edit: this seems to cause a crash sometimes when all monitors are disconnected, I'll need to fix that.

**Comment by 1over137** [comment]
Should be fixed now, checked as a patch on current master. Scale is changed successfully and no more crashing when switching monitors.

File: src/render/Renderer.cpp [hunk 3]
```diff
@@ -2039,6 +2039,14 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
 
     wlr_output_set_scale(pMonitor->output, pMonitor->scale);
 
+    // Set scale for all surfaces on this monitor, needed for some clients
+    // but not on unsafe state to avoid crashes
+    if (!g_pCompositor->m_bUnsafeState) {
```
Comment (vaxerski) [inline src/render/Renderer.cpp:2044]: last nit: I'd move this below. Probably after `wlr_damage_ring_set_bounds`, to avoid frankenstein states should anything change around here or in the func.

File: src/render/Renderer.cpp [hunk 4]
```diff
@@ -2039,6 +2039,9 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
 
     wlr_output_set_scale(pMonitor->output, pMonitor->scale);
 
+    // Set scale for all surfaces on this monitor, needed for some clients
```
Comment (vaxerski) [inline src/render/Renderer.cpp:2042]: you missed moving the comment xD

Comment (1over137) [reply src/render/Renderer.cpp]: lol I'm dumb

**Comment by vaxerski** [comment]
I told you 20 times to not force push and you broke the diff again

**Comment by 1over137** [comment]
Was just trying to rebase, never knew you were working on this, sorry. What to do now?

**Comment by vaxerski** [comment]
rebase against master and stop force pushing

**Comment by 1over137** [comment]
I just did a git reset and re-applied the patch on master, shouldn't have conflicts now.

**Review by vaxerski — APPROVED** [review]
lgtm
