### PR TITLE
Fixed window not taking focus on scroll after workspace switch

### LINKED ISSUE #8180: Scrolling doesn't take focus
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit 0e630e9e74ad34683194a07cfe6afe55a2c0685f  (session-lock: reset seat grab on a new session lock (8147)).
Date: Thu Oct 17 22:05:55 2024
Tag: v0.44.0-53-g0e630e9e, commits: 5352
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: Laptop-Nico
Release: 6.11.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:02 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprtrails by Vaxry ver 1.0
  hyprwinwrap by Vaxry ver 1.0

======Config-Start======


Config File: /home/nico/.config/hypr/hyprland.conf: Read Succeeded
# Source every file in the config/ directory
source = ~/.config/hypr/config/*


Config File: /home/nico/.config/hypr/config/autostart.conf: Read Succeeded
# Everything to be executed at startup
exec-once = waybar &
exec-once = hyprpaper &
exec-once = xwaylandvideobridge &
exec-once = hyprpm reload &
exec-once = nm-applet &
exec-once = dunst -config ~/.config/dunst/dunstrc &
exec-once = ~/.config/hypr/scripts/startxdhp.sh &
exec-once = udiskie &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = hypridle &
exec-once = floorp &
exec-once = keepassxc &
exec-once = webcord --ozone-platform=wayland &
exec-once = whatstron &
exec-once = alacritty & alacritty &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
# exec-once = ~/.config/hypr/scripts/cava.sh &


Config File: /home/nico/.config/hypr/config/binds.conf: Read Succeeded
$mainMod = SUPER

# General keybinds
bind = $mainMod, RETURN, exec, alacritty
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, thunar
bind = $mainMod, V, togglefloating, 
bind = $mainMod, D, exec, tofi-drun | xargs hyprctl dispatch exec
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, togglesplit, # dwindle
bind = $mainMod, X, exec, wlogout
bind = $mainMod, Print, exec, grimblast save area
bind =, Print, exec, grimblast copy area
bind = $mainMod, F, fullscreen
bind = $mainMod, O, exec, hyprctl dispatch fullscreen 1

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Move focus with mainMod + vim keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Swap windows with vim keys
bind = $mainMod SHIFT, h, swapwindow, l
bind = $mainMod SHIFT, l, swapwindow, r
bind = $mainMod SHIFT, k, swapwindow, u
bind = $mainMod SHIFT, j, swapwindow, d

# Swap windows with arrow keys
bind = $mainMod SHIFT, left, swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, up, swapwindow, u
bind = $mainMod SHIFT, down, swapwindow, d

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Keyboard shortcuts
binde=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
binde=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl=, XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindl=, XF86AudioPlay, exec, playerctl play
bindl=, XF86AudioPause, exec, playerctl pause
bindl=, XF86AudioNext, exec, playerctl next
bindl=, XF86AudioPrev, exec, playerctl previous
bindl=, XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
binde=, XF86MonBrightnessUp, exec, brightnessctl set +5%
binde=, XF86MonBrightnessDown, exec, brightnessctl set 5%-
binde=, XF86Search, exec, fuzzel
bindl=, XF86Calculator, exec, speedcrunch


# For screen sharing
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

# Autoclicker shortcut
bind = $mainMod, ESCAPE, exec, ~/.config/hypr/scripts/autoclicker.sh

# Scratchpad
bind = $mainMod, B, exec, ~/.config/hypr/scripts/scratchpad.sh "Btop"
bind = $mainMod, T, exec, ~/.config/hypr/scripts/scratchpad.sh "ScratchTerm"


Config File: /home/nico/.config/hypr/config/decoration.conf: Read Succeeded
# Window decorations
decoration {
    blur {
        enabled = true
        size = 2
        passes = 3
    }
		inactive_opacity = 0.98
    rounding = 10
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

# Window animations
animations {
    enabled = yes

    bezier = myBezier, 0.01, 0.9, 0.1, 1.05
		bezier = cubic-bezier, 0.68, -0.6, 0.32, 1.6

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, myBezier
}


Config File: /home/nico/.config/hypr/config/enviroment-variables.conf: Read Succeeded
# Some enviroment variables
env = XCURSOR_SIZE,24
env = GDK_BACKEND=wayland,x11
env = QT_QPA_PLATFORM="wayland;xcb"
env = SDL_VIDEODRIVER=wayland
env = CLUTTER_BACKEND=wayland
env = XDG_CURRENT_DESKTOP=Hyprland
env = XDG_SESSION_TYPE=wayland
env = XDG_SESSION_DESKTOP=Hyprland
env = QT_AUTO_SCREEN_SCALE_FACTOR=1
env = QT_QPA_PLATFORM=wayland;xcb
env = MOZ_ENABLE_WAYLAND=1
env = SDL_VIDEODRIVER=wayland
env = HYPRCURSOR_THEME,HyprBibataModernClassicSVG
env = XCURSOR_THEME=Bibata-Modern-Classic
env = ELECTRON_OZONE_PLATFORM_HINT=wayland
env = force_integer_tex_nearest=true ./suyu


Config File: /home/nico/.config/hypr/config/general.conf: Read Succeeded
# General settings
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(17bae1ee) rgba(aae8e8ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}


Config File: /home/nico/.config/hypr/config/input.conf: Read Succeeded
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

device {
	name = elan2097:00-2575:c300
	enabled = false
}


Config File: /home/nico/.config/hypr/config/layouts.conf: Read Succeeded
dwindle {
    pseudotile = yes
    preserve_split = yes
}

gestures {
    workspace_swipe = off
}


Config File: /home/nico/.config/hypr/config/monitors.conf: Read Succeeded
monitor=,preferred,auto,auto

monitor=eDP-1, 1920x1080@60, 0x0, 1
monitor=HDMI-A-1, 1920x2560@60, 1920x0, 1


Config File: /home/nico/.config/hypr/config/plugins.conf: Read Succeeded
# Plugins
plugin {
    hyprtrails {
      color = rgba(17BAE1ee)
    }
}
plugin {
		hyprwinwrap {
			class = alacritty-bg
		}
}


Config File: /home/nico/.config/hypr/config/rules.conf: Read Succeeded
# Workspace rules
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:eDP-1

# Window rules
windowrulev2= workspace 1, class:^(floorp)$
windowrulev2= workspace 3, class:^(Alacritty)$
windowrulev2= workspace 10, initialTitle:^(Spotify Premium)$
windowrulev2= workspace 9, initialClass:^(WebCord)$
windowrulev2= workspace 8, class:^(org.keepassxc.KeePassXC)$
windowrulev2= workspace 6, initialClass:^(Lxappearance)$
windowrulev2= workspace 6, class:^(blueberry.py)$
windowrulev2= workspace 9, initialClass:^(Whatstron)$
windowrulev2= workspace 4, class:^(thunar)$
windowrulev2= workspace 2, initialClass:^(unityhub)$
windowrulev2= workspace 2, initialClass:^(VSCodium)$
windowrulev2= workspace 2, initialClass:^(com-jetbrains-toolbox-entry-ToolboxEntry)$
windowrulev2= workspace 5, title:Waydroid

windowrulev2= fullscreen, title:Waydroid
windowrulev2= float, class:^(org.speedcrunch.speedcrunch)$

# Scratchpad rules
windowrulev2= float,size 30% 30%,class:(Btop)
windowrulev2= float,size 40% 40%,class:(ScratchTerm)

# Blur window rules
windowrulev2 = opacity 0.95, class:^(floorp)$
windowrulev2 = opacity 0.8, class:^(thunar)$
windowrulev2 = opacity 0.9, class:^(com.obsproject.Studio)$
windowrulev2 = opacity 0.85, class:^(WebCord)$
windowrulev2 = opacity 0.85 , class:^(Whatstron)$
windowrulev2 = opacity 0.85, class:^(org.keepassxc.KeePassXC)$
windowrulev2 = opacity 0.7, initialTitle:^(Spotify Premium)$

# Xwaylandvideobridge rules
windowrulev2 = opacity 0.0 override,initialClass:^(xwaylandvideobridge)$
windowrulev2 = noanim,initialClass:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,initialClass:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,initialClass:^(xwaylandvideobridge)$
windowrulev2 = noblur,initialClass:^(xwaylandvideobridge)$

======Config-End========


```

</details>

### Description

When having more then one visible windows in a single workspace open and having the cursor above the non-active window, you can make it active by moving your cursor or clicking with any button. However, when you scroll, it will scroll in the original active window and will not make the window under the cursor active. I would expect it to take focus when scrolling since clicking or moving the cursor will also take focus.

### How to reproduce

1. Have a workspace with more than 1 visible window
2. Go to another workspace and move your workspace to the position of the unfocused window
3. Go back to the original workspace
4. Scroll

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/3960303a-3486-493a-82df-60716a85c70d

### PR DESCRIPTION
**Pull request by nickodei**
#### Describe your PR, what does it fix/add?

Refocus on the hovered window with the scroll wheel after you switched back to the workspace. This works on mouse movement and on button clicks but not with the scroll wheel. This fixes #8180 (Which describes it in detail).

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

I tested it on my pc and it seems to work. But I have the feeling that this is to "simple" of a solution.

- Should I check if I'm not on the currently focused window to perform the `refocus()`?
- Is there a better place to perform the `refocus()`?

I would appreciate a more detailed guidance on how to improve it (I'm new to this codebase) when this is insufficient

#### Is it ready for merging, or does it need work?
From my side yes

### CODE REVIEW

File: src/managers/input/InputManager.cpp [hunk 1]
```diff
@@ -825,6 +825,8 @@ void CInputManager::onMouseWheel(IPointer::SAxisEvent e) {
 
             delta = 15.0 * discrete * factor;
         }
+
+        refocus();
```
Comment (vaxerski) [inline src/managers/input/InputManager.cpp:829]: this should not be refocus, because on focus follows mouse 0 or 2 it shouldnt refocus

additionally, why only on source of 0?

Comment (nickodei) [reply src/managers/input/InputManager.cpp:829]: Ahh, okay. So refocus forces it despite mouse_follow 0 or 1. Didnt think about it.

Then I would need a little help, because I thought `mouseMoveUnified` would handle the focusing but I'm not making it through this code-snippet because the mouse in fact didnt move (and refocuse = false):

```c++
    if (MOUSECOORDSFLOORED == m_vLastCursorPosFloored && !refocus)
        return;
``` 

Im still learning about this code-base but I dont know another way

Comment (nickodei) [reply src/managers/input/InputManager.cpp:829]: And for the source of 0: I just wanted to make the minimum change to fix this bug and not introduce others by changing their behavior. For source = 1 it still registers a click  (at least on my surface) as well as 4 when side clicking with the wheel. But yea sure, It could be probably done on all sources

Comment (vaxerski) [reply src/managers/input/InputManager.cpp:829]: `simulateMouseMovement`

Comment (nickodei) [reply src/managers/input/InputManager.cpp]: Done. Tested it with follow_mouse = 0 aswell.

**Review by vaxerski — APPROVED** [review]

**Comment by vaxerski** [comment]
see, much cleaner :)

**Comment by nickodei** [comment]
There isnt that much variety on cleanliness but sure I agree its cleaner :sweat_smile:

**Comment by nickodei** [comment]
Okay, I was thinking about it and I would say the best strategy would be to only call `simulateMouseMovement` once, when the windows differ. This code snipped seemed promising and would it be something that is okay?

```c++
void onMouseWheel(...) {
   if (!m_bLastFocusOnLS) {
          const auto MOUSECOORDS = g_pInputManager->getMouseCoordsInternal();
          const auto PWINDOW     = g_pCompositor->vectorToWindowUnified(MOUSECOORDS, RESERVED_EXTENTS | INPUT_EXTENTS | ALLOW_FLOATING);
          
          ...
          
          // new code: Only call simulateMouseMovement() when you are on a new Window
          const auto P_CURR_WINDOW = g_pCompositor->getWindowFromSurface(g_pCompositor->m_pLastFocus.lock());
          if(PWINDOW && P_CURR_WINDOW && PWINDOW != P_CURR_WINDOW) {
              simulateMouseMovement();
          }
    }
    ...
}
```

**Comment by vaxerski** [comment]
.... and focus follows mouse is 1 but ye

**Comment by vaxerski** [comment]
> But on nested-Hyprland my firefox spawns on main compositor and not on my nested on ...

cuz you already have firefox running in your hl it does that

**Comment by nickodei** [comment]
Is now implemented on the new PR #8361.
