### PR TITLE
#6098: Add Config Flag to `hyprctl systeminfo`

### LINKED ISSUE #6098: Add Config to systeminfo or bug reports.
### Description

I've ran into a bunch of bug reports recently that would have been a lot easier to repro if their config was in the bug report. I'm fine to add a config dump at the top of systeminfo so that its included when people include `hyprctl systeminfo` in their report. Another option is just adding a field for config in bug reports.

I feel like people don't really include personal info in configs but we can definitely warn people to take their social security number out of their config before submitting lol.

Thoughts on adding this? Is there a reason it hasn't been added?

### PR DESCRIPTION
**Pull request by The-Briel-Deal**
Closes #6098

#### Describe your PR, what does it fix/add?
Frequently I will look through issues on Github and be unable to repro the issue because there is no config attached to the issue. My hope is that by adding a --config/-c flag to systeminfo and asking for config files will significantly improve this problem and hopefully save developer time from time wasted trying to repro unclear issues.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Should be fine. Let me know if I should correct wording in the template.

#### Is it ready for merging, or does it need work?
Should be ready.

### CODE REVIEW

File: src/debug/HyprCtl.cpp [hunk 1]
```diff
@@ -895,6 +895,12 @@ std::string systemInfoRequest(eHyprCtlOutputFormat format, std::string request)
         result += std::format("  {} by {} ver {}\n", pl->name, pl->author, pl->version);
     }
 
+    if (g_pHyprCtl->m_sCurrentRequestParams.sysInfoConfig) {
+        result += "\n======Config-Start======\n";
+        result += "Config: " + execAndGet(std::string("cat " + g_pConfigManager->configCurrentPath).c_str()) + "\n";
```
Comment (vaxerski) [inline src/debug/HyprCtl.cpp:900]: needs to handle sourced files too

Comment (The-Briel-Deal) [reply src/debug/HyprCtl.cpp:900]: Yea, my hope was originally that I could just dump the in memory config easily, but it looks like there isn't a clean way to do that without checking a ton of different fields and objects that the different config is stored into.

I'll probably just keep all parsed config lines saved in a buffer on the ConfigManager object so that its easy to print out when this is called.

Lmk if you have a better way.

Comment (vaxerski) [reply src/debug/HyprCtl.cpp:900]: you can `cat` all files in the stat map in cconfigmanager

Comment (The-Briel-Deal) [reply src/debug/HyprCtl.cpp]: Done!

File: .github/ISSUE_TEMPLATE/bug.yml [hunk 2]
```diff
@@ -12,8 +12,8 @@ body:
   - type: textarea
     id: ver
     attributes:
-      label: Hyprland Version
-      description: "Paste the output of `hyprctl systeminfo` here."
+      label: System Info and Version
+      description: "Paste the output of `hyprctl systeminfo -c` here. If you have configs outside of the main config shown here, please attach or paste them below."
```
Comment (vaxerski) [inline .github/ISSUE_TEMPLATE/bug.yml:16]: what if someone isnt on git yet? -c will throw

File: .github/ISSUE_TEMPLATE/bug.yml [hunk 3]
```diff
@@ -25,6 +25,26 @@ body:
...
+    attributes:
+      label: Config Info
+      description: "If you replace your config with https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.conf can you reproduce this issue? If yes please let us know below. If not Please make sure to include ALL hyprland config files here. *Issues that do not follow this will be closed.*"
+      value: "<details>
+        <summary>Config Info</summary>
+
+
+        ```sh
+
+        <Paste all Hyprland config files here, if you attach the configs as files, please note that here.>
```
Comment (vaxerski) [inline .github/ISSUE_TEMPLATE/bug.yml:43]: I'd rather they attach by default

File: .github/ISSUE_TEMPLATE/bug.yml [hunk 4]
```diff
@@ -25,6 +25,26 @@ body:
...
 
+        </details>"
+    validations:
+      required: true
+
+  - type: textarea
+    id: ver
+    attributes:
+      label: Config Info
+      description: "If you replace your config with https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.conf can you reproduce this issue? If yes please let us know below. If not Please make sure to include ALL hyprland config files here. *Issues that do not follow this will be closed.*"
```
Comment (vaxerski) [inline .github/ISSUE_TEMPLATE/bug.yml:36]: if yes leave empty I guess?

File: src/config/ConfigManager.cpp [hunk 5]
```diff
@@ -633,6 +633,26 @@ std::string CConfigManager::getMainConfigPath() {
     return getConfigDir() + "/hypr/" + (ISDEBUG ? "hyprlandd.conf" : "hyprland.conf");
 }
 
+const std::string CConfigManager::getConfigString() {
+    std::string configString;
+    std::string line;
+
+    for (auto path : this->configPaths) {
```
Comment (vaxerski) [inline src/config/ConfigManager.cpp:640]: no `this->`

File: src/config/ConfigManager.cpp [hunk 6]
```diff
@@ -633,6 +633,26 @@ std::string CConfigManager::getMainConfigPath() {
...
+        std::ifstream configFile(path.c_str());
```
Comment (vaxerski) [inline src/config/ConfigManager.cpp:641]: c_str redundant

File: src/config/ConfigManager.cpp [hunk 7]
```diff
@@ -633,6 +633,26 @@ std::string CConfigManager::getMainConfigPath() {
...
+        configString += ("\n\nConfig File: " + path + ": ");
+        if (!configFile.is_open()) {
+            Debug::log(LOG, "Config file not readable/found!");
+            configString += "Read Failed\n";
+            continue;
+        }
+        configString += "Read Succeeded\n";
+        while (std::getline(configFile, line)) {
```
Comment (vaxerski) [inline src/config/ConfigManager.cpp:649]: brudda
```cpp
std::string content(std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>());
```

Comment (The-Briel-Deal) [reply src/config/ConfigManager.cpp:649]: Lol I was looking for this in the standard library. ty for pointing this out.

**Review by vaxerski — APPROVED** [review]
thanks :)
