### PR TITLE
handle file errors when loading xcursor themes

### LINKED ISSUE #7325: hyprland crashes on startup after 0.42.0 update
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

can't run hyprland to supply systeminfo output, it's version 0.42.0-1 on Arch.

</details>

### Description

hyprland constantly crashes on startup after upgrade to 0.42.0.

### How to reproduce

on my system, 100% of the time. last line of the crash log just said it loaded my xcursor theme, there's no obvious errors, so it's unclear what's happening or why. was working fine on 0.41 before I upgraded.

### Crash reports, logs, images, videos

[hyprlandCrashReport116828.txt](https://github.com/user-attachments/files/16605298/hyprlandCrashReport116828.txt)

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes #7325

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

File: src/managers/XCursorManager.cpp [hunk 1]
```diff
@@ -511,8 +511,13 @@ std::vector<SP<SXCursors>> CXCursorManager::loadAllFromDir(std::string const& pa
 
     if (std::filesystem::exists(path) && std::filesystem::is_directory(path)) {
         for (const auto& entry : std::filesystem::directory_iterator(path)) {
-            if (!entry.is_regular_file() && !entry.is_symlink())
+            try {
```
Comment (vaxerski) [inline src/managers/XCursorManager.cpp:514]: instead of try catch which kinda sucks can't you just `std::error_code e1, e2;` and pass them to the `is_*` fns?

then just `if (e1 || e2) continue`

**Review by vaxerski — APPROVED** [review]
thanks!
