### PR TITLE
Avoid rounding errors in window position on dwindle

### LINKED ISSUE #3511: Uncommon resolution - bottom row of pixels not used for windows
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

On my laptops internal screen Hyprland doesn't use the bottom row of pixels to display windows. Instead only the wallpaper is shown there. If your wallpaper is black this doesn't really hurt (except that you loose a row of pixels), but if there is something colorful on your wallpaper (like our beloved hypr-chan) it gets annoying really fast, especially for fullscreen applications (e.g. when watching a movie, playing a game, etc.)

I am using Hyprland on a Framework Laptop 13 whose internal display has a quite uncommon resolution:
```
> hyprctl monitors
Monitor eDP-1 (ID 0):
	2256x1504@59.99900 at 0x0
	description: BOE 0x095F (eDP-1)
	make: BOE
	model: 0x095F
	serial:
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

### How to reproduce

Use Hyprland on a similar display. Fractional scale doesn't matter (I have tried 1 and 1.5), neither does the type of application. Nothing gets displayed on the bottom row except the desktop wallpaper and the mouse (if I move it to the bottom). 
This bug isn't new (it exists since at least v0.27.2) and I was able to reproduce it on both Arch and NixOS.

### Crash reports, logs, images, videos

I attached some pictures that I took with my smartphone (taking screenshots was not possible since grim doesn't capture those pixels either). As an example I just used alacritty 

IMG_20231006_201744_063
IMG_20231006_201758_102
IMG_20231006_201821_660
IMG_20231006_201827_269
IMG_20231006_201836_299
I took this last image just that you see that this line of pixels is from the hypr-chan background.

### PR DESCRIPTION
**Pull request by FakeMichau**
#### Describe your PR, what does it fix/add?
Avoids rounding errors in window position and size which can result in wallpaper being visible between windows when it shouldn't. Simply gives second children the rest of the space instead of calculating again.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Should resolve #3511 

#### Is it ready for merging, or does it need work?
It's ready

### CODE REVIEW

File: src/layout/DwindleLayout.cpp [hunk 1]
```diff
@@ -24,16 +21,20 @@ void SDwindleNodeData::recalcSizePosRecursive(bool force, bool horizontalOverrid
 
         if (SPLITSIDE) {
             // split left/right
+            int space_0 = size.x / 2 * splitRatio;
```
Comment (vaxerski) [inline src/layout/DwindleLayout.cpp:24]: no snake pls, also can be const, in which case CAPS too

**Comment by FakeMichau** [comment]
Just realized it's only for the dwindle layout but I've seen this issue on master as well. Will make a commit soon hopefully

**Review by vaxerski — APPROVED** [review]
lgtm
