### PR TITLE
fix crash on monitor removed with gammaControl

### LINKED ISSUE #7537: Monitors: crash on wayland output removal with gammastep
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit eb42adc4c090918ad6be9fcb24066da8cdfd9bd0  (Fix missing include needed by clang).
Date: Mon Aug 26 20:36:43 2024
Tag: v0.42.0-76-geb42adc4, commits: 5145

flags: (if any)


System Information:
System name: Linux
Node name: crab
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/abc/.config/hyprland/hyprland.conf: Read Succeeded
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,32

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto
monitor= HDMI-A-1,2560x1440@60,0x0,1 # external monitor HDMI
monitor= desc:AU Optronics 0x5B2D,1920x1080@60,auto,1
monitor= desc:BNQ BenQ PD2705U 89P03368019,3840x2160@60,0x0,1.5
monitor= DP-2,disable # charging from BNQ
monitor= desc:BOE 0x094C,1920x1200@60,0x1440,1 # X1 Carbon
monitor= desc:BOE 0x0809,3840x2160@60,0x1440,2 # X1 Extreme

# workspace binding
workspace=1, monitor:HDMI-A-1
workspace=2, monitor:eDP-1
workspace=3, monitor:HDMI-A-1
workspace=4, monitor:eDP-1
workspace=6, monitor:HDMI-A-1
workspace=8, monitor:HDMI-A-1
workspace=9, monitor:HDMI-A-1

# Window Rules
windowrule = workspace 1 silent,firefox
windowrule = workspace 2 silent,org.telegram.desktop
windowrule = workspace 3 silent,jetbrains-phpstorm
windowrule = workspace 4 silent,Google-chrome
windowrule = workspace 4 silent,google-chrome
windowrule = workspace 5 silent,Microsoft-edge
windowrule = workspace 6 silent,thunderbird
windowrule = workspace 7 silent,syncthingtray
windowrule = workspace 9 silent,KeePassXC
windowrule = workspace 10 silent,workspace10

# custom classes to attach window to workspace
windowrulev2 = workspace 3 silent,class:^(wp-3)$
windowrulev2 = workspace 4 silent,class:^(wp-4)$
windowrulev2 = workspace 5 silent,class:^(wp-5)$
windowrulev2 = workspace 6 silent,class:^(wp-6)$

# firefox Picture-in-Picture
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$

# Telegram media viewer
windowrulev2 = fullscreen,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = workspace unset,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = monitor 1,class:^(org.telegram.desktop)$,title:^(Media viewer)$

# syncthingtray popup window
windowrulev2 = float,class:^(syncthingtray)$,title:^(Syncthing Tray)$
windowrulev2 = workspace unset,class:^(syncthingtray)$,title:^(Syncthing Tray)$
windowrulev2 = move 60% 30px,class:^(syncthingtray)$,title:^(Syncthing Tray)$
windowrulev2 = size 40% 50%,class:^(syncthingtray)$,title:^(Syncthing Tray)$

# file-roller
windowrulev2 = float,class:^(file-roller)$
windowrulev2 = center,class:^(file-roller)$

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$
windowrulev2 = float,class:^(google-chrome)$,title:^(Open Files)$
windowrulev2 = float,class:^(google-chrome)$,title:^(Open File)$

# taskwarrior
windowrule = center,^(task-floating)$
windowrule = float,^(task-floating)$
windowrule = dimaround,^(task-floating)$
windowrule = noborder,^(task-floating)$

windowrule = center,pavucontrol
windowrule = float,pavucontrol

windowrulev2 = dimaround,class:^(jetbrains-phpstorm)$,title:^(License )
windowrulev2 = float,class:^(jetbrains-phpstorm)$,title:^(License )
windowrulev2 = center,class:^(jetbrains-phpstorm)$,title:^(License )

# window rules to prevent screen from turning off
windowrule = idleinhibit fullscreen,firefox
windowrule = idleinhibit fullscreen,mpv

# Execute apps at launch
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dunst
exec-once = wbg ~/Pictures/wallpapers/karsten-wurth-7BjhtdogU3A-unsplash.jpg || swaybg -i ~/Pictures/wallpapers/bridge.jpg
exec-once = ~/.config/hyprland/xdg.sh >> xdg.sh.log 2>&1
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# exec-once = RUST_LOG='debug' /usr/bin/hyprland-per-window-layout > /tmp/hyprland-per-window-layout.log 2>&1
exec-once = alacritty --class workspace10 -e zsh -c "pull-dotfiles"
exec-once = ~/.config/hyprland/start-in-tray.sh
exec-once = /bin/sh -c "secret-tool lookup 'keepass' 'default' | keepassxc --pw-stdin ~/KeePass/database.kdbx"
exec-once = /bin/bash ~/Downloads/Telegram\ Desktop/unzip_here.sh
exec-once = swayidle -w timeout 600 swaylock before-sleep swaylock
exec-once = wl-paste -t text --watch clipman store --no-persist
exec-once = /usr/bin/hyprland-monitor-attached ~/.config/hyprland/monadd.sh
exec-once = gammastep -l 49:
exec-once = Thunar --daemon
exec-once = /usr/lib/thunderbird/thunderbird
exec-once = /usr/bin/easyeffects --gapplication-service

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
  kb_layout = us,ua,us
  kb_variant = ,,intl
  kb_model =
  kb_options = grp:alt_shift_toggle,caps:backspace
  kb_rules =

  follow_mouse = 1

  touchpad {
    natural_scroll = no
    tap_button_map = lmr
  }

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more

  gaps_in = 2
  gaps_out = 0
  border_size = 1
  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border = rgba(595959aa)

  layout = dwindle
  no_border_on_floating = yes
}

decoration {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more

  rounding = 0

  drop_shadow = no
  shadow_range = 4
  shadow_render_power = 3
  col.shadow = rgba(1a1a1aee)

  blur {
    enabled = no
  }
}

animations {
  enabled = no
}

dwindle {
  # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = yes # you probably want this
}

master {
  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
}

gestures {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  workspace_swipe = on
  workspace_swipe_invert = no
  workspace_swipe_cancel_ratio = 0.1
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  disable_autoreload = true
}

debug {
  disable_logs = false
}

# Bindings
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

bind = $mainMod, Return, exec, alacritty
bind = ALT, space, killactive,
bind = CONTROL, Space, togglefloating,
bind = $mainMod, D, exec, wofi --show run
bind = $mainMod, B, pseudo, # dwindle
bind = ALT, J, togglesplit, # dwindle
bind = $mainMod, F, fullscreen,

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# next workspace on monitor
bind = CONTROL_ALT, right, workspace, m+1
bind = CONTROL_ALT, left, workspace, m-1

# lock
bind = CONTROL_ALT, L, exec, swaylock

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = SUPER,Print,exec,ksnip
bind = ,Print,exec,~/.local/bin/grim-screenshot
bind = SHIFT,Print,exec,~/.local/bin/grim-screenshot screen

bind = ALT, F, exec, ~/lua/wm-keymap.lua f
bind = ALT, B, exec, ~/lua/wm-keymap.lua b
bind = ALT, C, exec, clipman pick -t wofi && wtype -M ctrl v -m ctrl
bind = ALT, M, exec, movies
bind = ALT,I,exec, /usr/bin/sh ~/PhpStorm/bin/phpstorm.sh & hyprctl dispatch workspace 3
bind = ALT, T, exec, ~/lua/wm-keymap.lua t
bind = $mainMod, E, exec, alacritty --class="nvim" -e "nvim"
bind = $mainMod, S, exec, syncthingtray --webui & hyprctl dispatch workspace 7
bind = $mainMod, T, exec, alacritty --class="task-floating" -t 'taskwarrior' -o window.opacity=1 -e "taskwarrior-tui"
bind = $mainMod, P, exec, pull-dotfiles
bind = $mainMod, M, exec, ~/.config/hyprland/menu.sh
# Mod+` ssh connect in the alacritty window
bind = $mainMod, Grave, exec, ~/ssh.py 'alacritty -e zsh -c'

# fn buttons
binde=,XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde=,XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind =,XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =,XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
binde=,XF86MonBrightnessUp,   exec, brightnessctl s 10%+
binde=,XF86MonBrightnessDown, exec, brightnessctl s 10%-
bind =,XF86AudioPlay,         exec, playerctl play-pause
bind =,XF86AudioPrev,         exec, playerctl previous
bind =,XF86AudioNext,         exec, playerctl next

# mouse side buttons
bind=,mouse:275,exec,wl-copy $(wl-paste -p) # copy selected text
bind=,mouse:276,exec,wtype -M ctrl -M shift v -m ctrl -m shift # paste by Ctrl+Shift+v

# resize submap (mode)
bind=SUPER,R,submap,resize
submap=resize
binde=,L,resizeactive,40 0
binde=,H,resizeactive,-40 0
binde=,K,resizeactive,0 -40
binde=,J,resizeactive,0 40
bind=,escape,submap,reset
bind=,Return,submap,reset
submap=reset

# exit mode
bind=SUPER,escape,exec,hyprctl dispatch submap logout; notify-send -a Hyprland -t 3500 $'\ne - exit\n\nr - reboot\n\ns - suspend\n\nS - poweroff\n\nl - lock' -i /usr/share/icons/breeze-dark/actions/32/system-suspend.svg
submap=logout
bindr =,E,exec,~/.config/hyprland/exit.sh &
bindr =,S,exec,hyprctl dispatch submap reset && systemctl suspend
bindr =,R,exec,systemctl reboot
bindr =SHIFT,S,exec,systemctl poweroff -i
bindr =,L,exec,hyprctl dispatch submap reset && swaylock
bindr=,escape,submap,reset
bind=,Return,submap,reset
submap=reset

# vpn mode
bind=ALT,V,exec,hyprctl dispatch submap vpn; notify-send -t 2500 -c vpn -i /usr/share/icons/breeze-dark/apps/48/alienarena.svg -a 'VPN' $'\n1 - wireguard GB\n\n2 - Openvpn US\n\n0 - Disable VPN'
submap=vpn
bind =, 1, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 1
bind =, 2, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 2
bind =, 3, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 3
bind =, 4, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 4
bind =, 5, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 5
bind =, 0, exec, hyprctl dispatch submap reset ; ~/lua/vpn.lua 0
bind=,escape,submap,reset
bind=,Return,submap,reset
submap=reset

======Config-End========
```

</details>

### Description

1. Crash when I disconnect an external display. I have no nvidia (Intel).
Actually notice this bug many months ago, but it is not stable to reproduce.  

2. And second problem with the monitor:
when i start hyprland, 50/50 monitor will show a black screen (workspaces there, but I can't see them), so I need to restart hyprland, or pull the cable and put it again 

### How to reproduce

Pull the cable before save important work 

UPD: [gammastep](https://gitlab.com/chinstrap/gammastep) need to be running 

### Crash reports, logs, images, videos

HDMI-A-1 disconnected - crash after 1-2 seconds
```
[LOG] [AQ] drm: Explicit sync supported
[LOG] [AQ] drm: Connector 313 connection state: 1
[LOG] [AQ] drm: Scanning connector id 322
[LOG] [AQ] drm: Connector id 322 already initialized
[LOG] [AQ] drm: connector HDMI-A-1 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
[LOG] [AQ] drm: Explicit sync supported
[LOG] [AQ] drm: Connector 322 connection state: 2
[LOG] [AQ] drm: Connector HDMI-A-1 disconnected
[LOG] Destroy called for monitor HDMI-A-1
[LOG] onDisconnect called for HDMI-A-1
[LOG] Removed monitor HDMI-A-1!
[LOG] [CLinuxDMABufV1Protocol] Resetting format table
[LOG] moveWorkspaceToMonitor: Moving 1 to monitor 0
[LOG] moveWorkspaceToMonitor: Plugging gap with existing 9
[LOG] [hookSystem] New hook event registered: workspace
[LOG] [hookSystem] New hook event registered: moveWorkspace
[LOG] moveWorkspaceToMonitor: Moving 9 to monitor 0
[LOG] moveWorkspaceToMonitor: Plugging gap with existing 6
[LOG] moveWorkspaceToMonitor: Moving 6 to monitor 0
[LOG] moveWorkspaceToMonitor: Plugging gap with new 3
[LOG] moveWorkspaceToMonitor: Plugging gap with existing 3
[LOG] [AQ] drm: Disabling output HDMI-A-1
[LOG] Removing monitor HDMI-A-1 from realMonitors
[LOG] [AQ] drm: Scanning connector id 331
[LOG] [AQ] drm: Connector id 331 already initialized
[LOG] [AQ] drm: Connector 331 connection state: 2
[LOG] [AQ] drm: Scanning connector id 340
[LOG] [AQ] drm: Connector id 340 already initialized
[LOG] [AQ] drm: Connector 340 connection state: 2
[LOG] [AQ] drm: Scanning connector id 344
[LOG] [AQ] drm: Connector id 344 already initialized
[LOG] [AQ] drm: connector DP-2 crtc is incapable of vrr: props.vrr_capable -> 351, crtc->props.vrr_enabled -> 24
[LOG] [AQ] drm: Explicit sync supported
[LOG] [AQ] drm: Connector 344 connection state: 1
[LOG] [AQ] drm: Scanning connector id 352
[LOG] [AQ] drm: Connector id 352 already initialized
[LOG] [AQ] drm: Connector 352 connection state: 2
[LOG] [AQ] drm: Scanning connector id 356
[LOG] [AQ] drm: Connector id 356 already initialized
[LOG] [AQ] drm: Connector 356 connection state: 2
[LOG] [AQ] drm: Scanning connector id 365
[LOG] [AQ] drm: Connector id 365 already initialized
[LOG] [AQ] drm: Connector 365 connection state: 2
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 376
[LOG] Destroying workspace ID 3
[LOG] LayerSurface 558456903ee0 destroyed
[WARN] Layersurface destroyed on an invalid monitor (removed?)
[LOG] Forcing an unmap of a LS that did a straight destroy!
[LOG] LayerSurface 558456903ee0 unmapped
[WARN] Layersurface unmapping on invalid monitor (removed?) ignoring.
[LOG] CWLSurface 5584569043e0 called destroy()
[LOG] [CGammaControl] setGamma for eDP-1
[LOG] [CGammaControl] setting to monitor eDP-1
[LOG] [CGammaControl] setGamma for HDMI-A-1
[LOG] [CGammaControl] setting to monitor HDMI-A-1
```

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes #7537

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

File: src/protocols/GammaControl.cpp [hunk 1]
```diff
@@ -26,7 +26,7 @@ CGammaControl::CGammaControl(SP<CZwlrGammaControlV1> resource_, wl_resource* out
     }
 
     for (auto const& g : PROTO::gamma->m_vGammaControllers) {
-        if (g->pMonitor == pMonitor) {
+        if (g->pMonitor.get() == pMonitor.get()) {
```
Comment (vaxerski) [inline src/protocols/GammaControl.cpp:29]: ?? shouldnt this do the same

Comment (ikalco) [reply src/protocols/GammaControl.cpp:29]: i guess

**Review by vaxerski — APPROVED** [review]
