### PR TITLE
properly use software cursors with zoom_factor

### LINKED ISSUE #6242: cursor:zoom_factor doesn't work unless cursor is hidden
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 2ff95bba3fec58b9f1a127fe72dda84b1420a7af  (flake.lock: update).
Date: Sat May 25 04:51:08 2024
Tag: v0.40.0-132-g2ff95bba, commits: 4738

flags: (if any)


System Information:
System name: Linux
Node name: oyster
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0
```

config:
```
#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#
group {
    groupbar {
        font_family = sans-serif
        render_titles = true
        font_size = 13

        col.active = 0x66ffff00
    }
}

debug {
    disable_logs = false
    enable_stdout_logs = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch


# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env XIM_PROGRAM=fcitx
env XIM=fcitx
env QT_IM_MODULE=fcitx
env XMODIFIERS="@im=fcitx"

env = XCURSOR_SIZE,24
env = GTK_IM_MODULE,
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.7
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 1
    gaps_out = 0
    border_size = 3
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
    resize_on_border = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 2
    blur {
        size = 5
        passes = 4
        new_optimizations = true
    }

    drop_shadow = yes
    shadow_range = 50
    shadow_render_power = 3
    col.shadow = rgba(00000050)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    animation = windows, 1, 2, default
    animation = windowsOut, 1, 2, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 20, default, once
    animation = fade, 1, 5, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
# device:epic-mouse-v1 {
#     sensitivity = -0.5
# }

misc {
    disable_hyprland_logo = true
    focus_on_activate = true
}

XWayland {
#    force_zero_scaling = true
}

layerrule = blur, waybar
layerrule = blur, lockscreen
layerrule = blur, notifications

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = ALT

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, alacritty
bind = $mainMod, D, exec, dmenu_run -l 16
bind = $mainMod SHIFT, D, exec, j4-dmenu-desktop --dmenu="dmenu -l 16 -i"
bind = $mainMod, b, exec, firefox
bind = $mainMod, u, exec, systemctl suspend
# bind = $mainMod ALT, l, exec, swaylock-my
binde = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
binde = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
binde = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
# binde = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SINK@ toggle
binde = , XF86MonBrightnessUp, exec, brightnessctl set 3000+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 3000-
bind = $mainMod SHIFT, n, exec, makoctl restore
bind = $mainMod, n, exec, makoctl dismiss
bind = $mainMod ALT, n, exec, mako-toggle
bind = $mainMod SHIFT, s, exec, grimblast copysave area ~/screen.png
bind = , Print, exec, grimblast copysave area ~/screen.png
bind = $mainMod, x, exec, sxiv ~/screen.png
bind = $mainMod SHIFT, x, exec, emacsclient -nc
bind = $mainMod, comma, exec, rofi -show window
bind = $mainMod SHIFT, o, exec, ocr_screen.sh
bind = $mainMod , g, exec, goldendict

bind = $mainMod, v, exec, killall -SIGUSR1 waybar

bind = $mainMod SHIFT, Q, killactive, 
# bind = $mainMod SHIFT, E, exit, 
bind = $mainMod SHIFT, SPACE, togglefloating, 
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, E, togglesplit, # dwindle
bind = $mainMod, F, fullscreen
bind = $mainMod, t, togglegroup

# Move focus with mainMod + arrow keys
bind = $mainMod, left, exec, hyprland-move.sh focus l
bind = $mainMod, right, exec, hyprland-move.sh focus r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, h, exec, hyprland-move.sh focus l
bind = $mainMod, l, exec, hyprland-move.sh focus r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d
bind = $mainMod, m, movecurrentworkspacetomonitor, +1

bind = $mainMod SHIFT, left, exec, hyprland-move.sh move l
bind = $mainMod SHIFT, right, exec, hyprland-move.sh move r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d
bind = $mainMod SHIFT, h, exec, hyprland-move.sh move l
bind = $mainMod SHIFT, l, exec, hyprland-move.sh move r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod, o, workspace, previous

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

monitor=,preferred,auto,1

```

</details>

### Bug or Regression?

Bug

### Description

cursor:zoom_factor is ignored unless the cursor is hidden.

### How to reproduce

```bash
hyprctl keyword cursor:zoom_factor 2
```

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes  #6242

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
tested on my system using hyprctl and editing config file

#### Is it ready for merging, or does it need work?
Yes

### CODE REVIEW

File: src/render/Renderer.cpp [hunk 1]
```diff
@@ -1265,10 +1265,6 @@ void CHyprRenderer::renderMonitor(CMonitor* pMonitor) {
         pMonitor->forceFullFrames                      = 10;
     }
 
-    bool lockSoftware = pMonitor == g_pCompositor->getMonitorFromCursor() && *PZOOMFACTOR != 1.f;
```
Comment (vaxerski) [inline src/render/Renderer.cpp:1268]: why not do it here?

```cpp
static bool zoomLock = false;
if (zoomlock && !zoom) {
    unlock();
    zoomlock = false;
} else if (!zoomlock && zoom) {
    lock();
    zoomlock = true;
}
```

Comment (ikalco) [reply src/render/Renderer.cpp:1268]: you right lol, i was thinking too hard

Comment (ikalco) [reply src/render/Renderer.cpp:1268]: wait actually. the reason is because we need to lock software cursors for all monitors or else hardware cursors breaks stuff by not disabling correctly

**Review by vaxerski — APPROVED** [review]
tanks!
