### PR TITLE
tablet: send `motion`s on tip events

### LINKED ISSUE #8751: Wacom pen jumping
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: nialand
Release: 6.12.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.77  Wed Nov 27 23:33:08 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.2.0

======Config-Start======


Config File: /home/vivy/.config/hypr/hyprland.conf: Read Succeeded

# #######################################################################################
# AUTOGENERATED HYPR CONFIG.
# PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
# OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################

autogenerated = 0 # remove this line to remove the warning

# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DVI-D-1,1920x1080@144,0x0,1
monitor=HDMI-A-1,1440x900@60,1920x180,1
# monitor=HDMI-A-2,1920x1080@60,0x0,1


###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun -I -W 500 -L 7



#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = nm-applet &
exec-once = waybar &
exec-once = hyprpaper &
exec-once = blueman-applet &
exec-once = corectrl &
exec-once = [workspace special silent] obs --startreplaybuffer --disable-shutdown-check &
exec-once = deluged &
exec-once = syncthing &
# exec-once = easyeffects --gapplication-service &
exec-once = hyprpm reload -n

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

cursor {
  # no_hardware_cursors = false
  # allow_dumb_copy = true
}

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 10
    gaps_out = 10

    # gaps_in = 0
    # gaps_out = 0

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border = rgba(00ffcc88)
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    # drop_shadow = true
    # shadow_range = 4
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slidefadevert 100%
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    enable_swallow = true
    swallow_regex = ^(kitty)$
}


#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = en
    kb_variant = us
    kb_model =
    kb_options = 
    kb_rules =
    repeat_delay = 250
    repeat_rate = 75
    numlock_by_default = true

    follow_mouse = 1

    sensitivity = -0.75 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

device{
  name = logitech-g502-hero-gaming-mouse
  sensitivity = -1
}

device{
  name = 2.4g-composite-devic-mouse
  sensitivity = 1
}


####################
### KEYBINDINGSS ###
####################

$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, F4, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, N, togglesplit, # dwindle
bind = $mainMod, B, exec, killall -SIGUSR1 waybar

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# bind = $mainMod, N, split-changemonitor, next
# bind = $mainMod SHIFT, N, split-changemonitor, prev

bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5
bind = $mainMod, 6, split-workspace, 6
bind = $mainMod, 7, split-workspace, 7
bind = $mainMod, 8, split-workspace, 8
bind = $mainMod, 9, split-workspace, 9
bind = $mainMod, 0, split-workspace, 10

bind = $mainMod SHIFT, 1, split-movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, split-movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, split-movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, split-movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, split-movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, split-movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, split-movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, split-movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, split-movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, split-movetoworkspacesilent, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspacesilent, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# MY GLOBAL SHORTCUTS
bind = CTRL_SHIFT, F10, pass, ^(com\.obsproject\.Studio)$

# MY EXTRA BINDS
bind = , Print, exec, /bin/fish /home/vivy/gitRepos/wlshot/wlshot.fish -f ppm -c png -m region
bind = $mainMod, XF86AudioRaiseVolume, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if(factor < 1) {factor = 1}; print factor * 1.25}')"

bind = $mainMod, XF86AudioLowerVolume, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if(factor < 1) {factor = 1}; print factor / 1.25}')"

bind = $mainMod SHIFT, ESCAPE, exec, hyprlock

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrulev2 = float,class:^(rofi)$,title:^(rofi)$


windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

layerrule=noanim, hyprpicker
layerrule=noanim, selection

# windowrulev2 = opacity 0.0 override,class:^(xwaylandvideobridge)$
# windowrulev2 = noanim,class:^(xwaylandvideobridge)$
# windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
# windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
# windowrulev2 = noblur,class:^(xwaylandvideobridge)$

# THE FOLLOWING 6 RULES ARE FOR SMART GAPS, SMART BORDERS AND SMART ROUNDING
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]

======Config-End========
```

</details>

### Description

When drawing with a wacom tablet there's a jumping line. 
I recorded a video first showing it functioning normally on awesomewm and then with the issue on hyprland.

https://github.com/user-attachments/assets/842ae277-daba-4083-995f-074c1e6b7bf1

### How to reproduce

Connect a wacom tablet, open up krita or xournalpp, draw straight lines.

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by MikeWalrus**
Typically, the position of the tool tip also changes on tool tip events, so we should forward this update to the clients.

Otherwise, strokes can be too messy for tablets to be functional, even at moderate writing speeds.

Before:

https://github.com/user-attachments/assets/0317a98a-ff5a-483f-861e-131e1ef03f91

After:

https://github.com/user-attachments/assets/10eb961e-dd62-4e7e-8e6c-fd4c9d1ad96e

fixes #8751 .

### CODE REVIEW

**Comment by fufexan** [comment]
Does this also fix navigating menus with the pen? It's a notorious pain in Xournal++ at least.

File: src/managers/input/Tablets.cpp [hunk 1]
```diff
@@ -159,10 +159,11 @@ void CInputManager::onTabletAxis(CTablet::SAxisEvent e) {
...
     const auto PTOOL = ensureTabletToolPresent(e.tool);
+    const auto POS = e.tip;
+    g_pPointerManager->warpAbsolute(POS, PTAB);
+    refocusTablet(PTAB, PTOOL, true);
 
     if (e.in) {
-        simulateMouseMovement();
-        refocusTablet(PTAB, PTOOL);
         PROTO::tablet->down(PTOOL);
     } else
```
Comment (fufexan) [inline src/managers/input/Tablets.cpp:168]: Remove the `{}` around the if to make CI happy again.

Comment (vaxerski) [reply src/managers/input/Tablets.cpp:168]: the brace isnt why c-f fails, but yes, please nuke it and clang-format xD

**Comment by MikeWalrus** [comment]
> Does this also fix navigating menus with the pen? It's a notorious pain in Xournal++ at least.

No, it doesn't.

**Comment by m2neral** [comment]
Thank you! This was driving me insane.

**Comment by y47s5s68tq870r7tc1xpp755pabopg** [comment]
This line ( `src/managers/input/Tablets.cpp:163` )
```c++
g_pPointerManager->warpAbsolute(POS, PTAB);
```
makes config `input:tablet:relative_input = true` completely non functional.
You can move cursor as you're supposed to, but wraps on press, as if `relative_input = false`

Changing to this should fix it, but not tested.
```c++
if (PTAB->relativeInput)
    g_pPointerManager->move({0, 0});
else
    g_pPointerManager->warpAbsolute(POS, PTAB);
```

Sorry that it's not pull request, git/github isn't really something that i use.

**Comment by vaxerski** [comment]
if someone can make a MR in place of you, it'd be great

**Comment by clamydo** [comment]
@vaxerski Incorporated into my other fix PR https://github.com/hyprwm/Hyprland/pull/9325, which fixes an regression (see https://github.com/hyprwm/Hyprland/issues/9322) introduced by this PR.

Do you want me to split this up in two PRs?

**Comment by vaxerski** [comment]
no, one is fine. check my review

**Comment by MikeWalrus** [comment]
I'm sorry for the regression. Haven't got the bandwidth to deal with it in the past few weeks. @clamydo Thank you for fixing it. Happy to know that other people are also actively using tablets on Hyprland.

**Comment by m2neral** [comment]
@MikeWalrus I'm still having the same issue on 0.47.2. I've been looking at Tablets.cpp to figure out why this didn't fix it for me but nothing seems to make a difference. Do you have any ideas?
